<?php
/** Completion review 2: spaces, presence and advanced message operations. */
declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$checks=0;
$read=static function(string $path):string{$v=file_get_contents($path);if($v===false)throw new RuntimeException('Missing '.$path);return $v;};
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok)$failures[]=$message;};
$spaces='';foreach(glob($root.'/includes/class-sn-spaces*.php')?:[] as $space_file)$spaces.=$read($space_file);$presence=$read($root.'/includes/class-sn-presence-devices.php');$ops=$read($root.'/includes/class-sn-message-operations.php');
$check(str_contains($spaces,"private const VISIBILITIES = ['public','discoverable_private','invite_only','hidden']"),'Space visibility modes must be explicit.');
$check(str_contains($spaces,"private const STATES = ['active','restricted','locked','archived','closed','deletion_requested']"),'Space lifecycle states must be explicit.');
$check(str_contains($spaces,"private const JOIN_POLICIES = ['open','request','invite']"),'Join policies must be allowlisted.');
$check(str_contains($spaces,"private const POSTING_POLICIES = ['members','approved','roles','disabled']"),'Posting policies must be allowlisted.');
$check(str_contains($spaces,'UNIQUE KEY space_user (space_id,user_id)'),'Space membership must be unique.');
$check(substr_count($spaces,'UNIQUE KEY active_key (active_key)')>=2&&str_contains($spaces,"'active_key'=>hash('sha256',\$id.':'.\$user)"),'Join requests and invitations must use nullable active idempotency keys.');
$check(str_contains($spaces,'UNIQUE KEY token_hash (token_hash)'),'Invitation tokens must be unique.');
$check(str_contains($spaces,'Only the invited recipient may accept or reject'),'Invitation consent must belong to the recipient.');
$check(str_contains($spaces,'Only the inviter or a space manager may cancel')||str_contains($spaces,'Only the inviter or a current space manager may cancel'),'Managers may cancel but not accept invitations for recipients.');
$check(str_contains($spaces,"\$action==='cancel'")&&str_contains($spaces,'requester_id=%d'),'Join request cancellation must belong to the requester.');
$check(str_contains($spaces,"['accept','reject']")&&str_contains($spaces,'can_manage($space_id,$actor'),'Join decisions must belong to managers.');
$check(str_contains($spaces,"SN_Policy::can_contact((int)\$invite->inviter_id,\$actor,'group')"),'Invitation acceptance must recheck contact policy.');
$check(str_contains($spaces,'member_limit')&&str_contains($spaces,'sn_space_capacity_reached'),'Member capacity must be enforced under a locked space row.');
$check(str_contains($spaces,'anti_raid_until')&&str_contains($spaces,'sn_space_anti_raid_join_pause'),'Anti-raid mode must pause joins.');
$check(str_contains($spaces,'invite_pause_until')&&str_contains($spaces,'sn_space_invites_paused'),'Invitation pause must be enforced.');
$check(str_contains($spaces,'new_member_delay_seconds')&&str_contains($spaces,'sn_space_new_member_delay'),'New-member posting delay must be enforced.');
$check(str_contains($spaces,'slow_mode_seconds')&&str_contains($spaces,'sn_space_slow_mode'),'Slow mode must be enforced.');
$check(str_contains($spaces,'sn_space_observer_read_only'),'Observers must remain read-only.');
$check(str_contains($spaces,'sn_space_restricted_mode'),'Restricted mode must allow managers only.');
$check(str_contains($spaces,'can_manage_target')&&str_contains($spaces,'ROLE_RANK'),'Role hierarchy must be server enforced.');
$check(str_contains($spaces,'sn_space_owner_successor_required'),'Owners must not leave orphaned spaces.');
$check(str_contains($spaces,"self::space(\$id,true)")||str_contains($spaces,"self::space(\$space_id,true)"),'Governance mutations must lock authoritative rows.');
$check(str_contains($spaces,"\$wpdb->query('START TRANSACTION')")&&str_contains($spaces,"\$wpdb->query('ROLLBACK')"),'Space mutations must have commit/rollback paths.');
$check(str_contains($spaces,'wp_privacy_personal_data_exporters')&&str_contains($spaces,'wp_privacy_personal_data_erasers'),'Space memberships must participate in privacy lifecycle.');
$check(str_contains($presence,'presence_devices')&&str_contains($presence,'UNIQUE KEY user_device'),'Presence must be unique per user-scoped device key.');
$check(str_contains($presence,"hash_hmac('sha256',\$user.'|'.\$raw"),'Raw device IDs must be converted to user-scoped keyed hashes.');
$check(str_contains($presence,'MAX_DEVICES = 25'),'Device count must be bounded.');
$check(str_contains($presence,'MAX_TTL = 300')&&str_contains($presence,'MIN_TTL = 30'),'Heartbeat lifetime must be bounded.');
$check(str_contains($presence,'FUTURE_SKEW = 60')&&str_contains($presence,"return'offline'"),'Implausible future/stale heartbeats must derive offline.');
$check(str_contains($presence,'SN_Policy::can_view_presence'),'Aggregate presence must revalidate viewer authorization.');
$check(str_contains($presence,'device_ref')&&str_contains($presence,'verify_ref'),'Device revocation must use signed scoped references.');
$check(str_contains($presence,'revoked_at')&&str_contains($presence,'presence_device_revoked'),'Revocation must be durable and audited.');
$check(str_contains($presence,'wp_privacy_personal_data_exporters')&&str_contains($presence,'wp_privacy_personal_data_erasers'),'Presence devices must support export and erasure.');
$check(str_contains($ops,'message_mentions')&&str_contains($ops,'MAX_MENTIONS = 20'),'Mentions must be native and bounded.');
$check(str_contains($ops,'Every mentioned account must be an active conversation member'),'Mention targets must be active members.');
$check(str_contains($ops,'message.forwarded')&&str_contains($ops,'source_scope_hash'),'Forwarding must emit audience-minimized evidence.');
$check(str_contains($ops,'Private attachments must be re-uploaded rather than reusing their identifier or bytes'),'Forwarding must not reuse private attachment IDs or bytes.');
$check(str_contains($ops,'all_target_members_share_source')&&str_contains($ops,"\$metadata['source_message_id']"),'Source identity may be exposed only to a shared audience.');
$check(str_contains($ops,'message_pins')&&str_contains($ops,'message_stars'),'Conversation pins and private stars must remain distinct domains.');
$check(str_contains($ops,'message_folders')&&str_contains($ops,'message_folder_items'),'Private folders must organize pointers without duplicating conversations.');
$check(str_contains($ops,'message_hides')&&str_contains($ops,'hidden_for_self'),'Delete/hide-for-self must be a private projection.');
if($checks!==41)$failures[]='Review contract count changed: expected 41, got '.$checks;
if($failures){fwrite(STDERR,"Completion review 2 failures (".count($failures)."/$checks):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "Completion review 2 spaces/presence/messages: PASS ($checks checks)\n";