<?php
/** Historical forty-round ledger + current release-truth boundary. */
declare(strict_types=1);
$root=dirname(__DIR__);$repo=dirname($root);$fail=[];$checks=0;$read=static fn(string $p):string=>(string)file_get_contents($p);$check=static function(bool $ok,string $msg)use(&$fail,&$checks):void{$checks++;if(!$ok)$fail[]=$msg;};
$main=$read($root.'/sabri-network.php');$wpreadme=$read($root.'/readme.txt');$pluginreadme=$read($root.'/README.md');$rootreadme=$read($repo.'/README.md');$status=$read($repo.'/STATUS.md');$system=$read($root.'/SYSTEM-STATUS.txt');$complete=$read($repo.'/CODING-COMPLETENESS.md');$audit=$read($repo.'/FORTY-ROUND-AUDIT-2026-08-07.md');$quality=$read($root.'/tools/quality-check.sh');$package=$read($root.'/tools/package.sh');$workflow=$read($repo.'/.github/workflows/quality.yml');
$check(str_contains($main,'Version: 2.1.0')&&str_contains($main,"define('SN_VERSION', '2.1.0')"),'Current plugin header and runtime must be immutable 2.1.0.');
$check(str_contains($wpreadme,'Stable tag: 2.1.0')&&str_contains($wpreadme,'= 2.1.0 ='),'Current WordPress readme must be 2.1.0 aligned.');
$check(str_contains($package,'17-sabri-network-and-messages-2.1.0')&&str_contains($quality,"BASE='17-sabri-network-and-messages-2.1.0'"),'Package and quality gate must target 2.1.0.');
$check(str_contains($workflow,'Upload governed 2.1.0 candidate')&&str_contains($workflow,'file-17-complete-2.1.0-'),'Workflow artifact identity must be 2.1.0.');
foreach(['forty-round-review-1-governance-identity-crypto-contracts.php','forty-round-review-2-transfer-smail-privacy-contracts.php','forty-round-review-3-canonical-safety-resilience-contracts.php','forty-round-review-4-release-truth-contracts.php','two-plan-completion-contracts.php'] as $suite){$check(str_contains($quality,$suite)&&str_contains($workflow,$suite),"Both quality paths must invoke $suite.");}
$check(str_contains($audit,'**Review rounds performed:** **40**')&&str_contains($audit,'**Rounds in which one or more defects were found and corrected:** **18**')&&str_contains($audit,'**Rounds in which no new defect was found:** **22**'),'Historical audit ledger must retain 40 = 18 defect-bearing + 22 clean rounds.');
$check(str_contains($rootreadme,'Historical review ledgers')&&str_contains($audit,'**Review rounds performed:** **40**'),'Root README must explicitly classify historical ledgers while the historical ledger itself preserves the founder-requested 40-round count.');
$check(str_contains($status,'review suites')&&str_contains($status,'**55**')&&str_contains($complete,'review suites')&&str_contains($complete,'**55**'),'Current repository status and coding assessment must publish the current 55-suite gate.');
$check(str_contains($system,'not staging-accepted')&&str_contains($pluginreadme,'**Staging-Accepted:** pending')&&str_contains($rootreadme,'**Live-Deployed:** not claimed'),'Release documentation must preserve staging/live separation.');
$check(str_contains($main,"'global_search_owner' => 'file-26'")&&str_contains($rootreadme,'File 26 global search/ranking'),'Latest File 26 ownership must be reflected in runtime and documentation.');
$all=$rootreadme."\n".$pluginreadme."\n".$status."\n".$system."\n".$complete;
$check(!preg_match('/(?:100% secure|unhackable|E2EE enabled)/i',$all)&&!preg_match('/(?:is|status:)\s+production-ready/i',$all),'Current release documents must not make a positive unsupported security/production claim.');
$check(substr_count($quality,'forty-round-review-')===4&&substr_count($workflow,'forty-round-review-')===4,'Exactly four historical forty-round suite invocations must remain explicit in each quality path.');
$check(str_contains($audit,'**Known unresolved repository/current-wave coding defects after round 40:** **0**'),'Historical audit must retain its exact freeze result.');
$check(str_contains($package,'includes/class-sn-compatibility-hardening.php')&&str_contains($package,'includes/class-sn-two-plan-completion.php')&&str_contains($quality,'includes/class-sn-two-plan-completion.php'),'Current corrective/completion hardening must be required by package and full quality gate.');
$check(str_contains($audit,'2.0.3')&&stripos($audit,'historical')!==false&&str_contains($complete,'2.1.0')&&stripos($complete,'prior-cycle')!==false&&str_contains($rootreadme,'Historical review ledgers'),'Historical 2.0.3 evidence must remain attributable to its own ledger while current documents publish 2.1.0 without reusing stale counts.');
if($fail){fwrite(STDERR,"Forty-round suite 4 failures (".count($fail)."/$checks):\n - ".implode("\n - ",$fail)."\n");exit(1);}echo "Forty-round review 4 historical/current release truth: PASS ($checks checks)\n";
