<?php
declare(strict_types=1);
$root=dirname(__DIR__);$main=file_get_contents($root.'/sabri-network.php');$body=file_get_contents($root.'/includes/class-sn-message-body.php');$integrity=file_get_contents($root.'/includes/class-sn-message-integrity.php');$runtime=file_get_contents($root.'/includes/class-sn-message-runtime-hardening.php');$search=file_get_contents($root.'/includes/class-sn-message-search.php');$smail=file_get_contents($root.'/includes/class-sn-smail-part-2.php');$hard=file_get_contents($root.'/includes/class-sn-central-plan-hardening.php');$compat=file_get_contents($root.'/includes/class-sn-compatibility-hardening.php');$r7=file_get_contents($root.'/includes/class-sn-fresh20-r7-message-read-hardening.php');$loader=file_get_contents($root.'/includes/class-sn-future24-review-hardening.php');$fails=[];$checks=0;
function fpr3(bool $c,string $m):void{global $fails,$checks;$checks++;if(!$c)$fails[]=$m;}
fpr3(str_contains($main,"class-sn-message-body.php")&&str_contains($main,"class-sn-central-plan-hardening.php")&&str_contains($main,"class-sn-compatibility-hardening.php"),'Message encryption and corrective hardening classes are loaded.');
fpr3(str_contains($body,"PREFIX = 'SNE1:'")&&str_contains($body,'SN_Communication_Crypto::encrypt')&&str_contains($body,'SN_Communication_Crypto::decrypt'),'Canonical message bodies use authenticated at-rest envelopes.');
fpr3(str_contains($body,'ensure_encrypted_row')&&str_contains($body,'write_cas')&&str_contains($hard,'migrate_message_bodies'),'Legacy plaintext has bounded non-destructive migration rather than permanent plaintext fallback.');
fpr3(str_contains($integrity,'SN_Message_Body::encrypt($body, $conversation_id, $user_id)'),'New canonical messages encrypt before database insertion.');
fpr3(str_contains($integrity,'SN_Message_Body::encrypt($body, (int) $message->conversation_id'),'Edits re-encrypt before database update.');
fpr3(str_contains($search,'SN_Message_Body::decrypt_row($message)')&&str_contains($search,'self::terms($plain'),'Private search tokenizes plaintext only after authorized in-memory decryption.');
fpr3(str_contains($smail,'SN_Message_Integrity::send_message')&&!str_contains($smail,'SN_REST::send_message'),'Smail cannot bypass the atomic canonical message path.');
fpr3(str_contains($smail,'resolve_smail_conversation'),'Smail retries use an idempotent canonical conversation resolver.');
fpr3(str_contains($hard,"'recipient_hash' => \$recipient_hash")&&str_contains($hard,'smail_idempotency_conflict'),'Multi-recipient Smail retries bind the same key to the same audience.');
fpr3(str_contains($compat,'SN_Message_Body::decrypt_row($source)')&&str_contains($compat,'SN_Message_Body::encrypt($plain, $target_id, $actor)'),'Active forwarding decrypts only authorized source content in memory and re-encrypts target content.');
fpr3(str_contains($compat,"'source_visible' => \$shared")&&str_contains($compat,'source_scope_hash'),'Forwarded metadata minimizes source identity across audience boundaries.');
fpr3(str_contains($hard,'MIGRATION_BATCH = 100'),'At-rest migration is bounded per pass.');
fpr3(str_contains($runtime,'if($race){')&&str_contains($runtime,"(int)\$attachment['id'] !== (int)\$race->attachment_id")&&str_contains($runtime,"SN_Private_Files::delete((int)\$attachment['id'],\$user_id)"),'A losing idempotent attachment race must revoke/delete its orphan private attachment before returning the winner.');
fpr3(str_contains($r7,"READ_METHODS = ['get_row','get_var','get_col','get_results']")&&str_contains($r7,'message_database_read_failed')&&str_contains($r7,"['status'=>503]"),'Fresh20 R7: authoritative message SQL read failure must fail closed with retryable 503 truth.');
fpr3(str_contains($r7,"add_action('rest_api_init', [self::class, 'override_routes'], 4200)")&&str_contains($r7,'SN_Fourth_Fresh_Review_Hardening::send_message')&&str_contains($r7,'SN_Fourth_Fresh_Review_Hardening::edit_message')&&str_contains($r7,'SN_Fourth_Fresh_Review_Hardening::delete_message'),'Fresh20 R7: the final message mutation routes must delegate to canonical owners under the read-truth guard.');
fpr3(str_contains($loader,"class-sn-fresh20-r7-message-read-hardening.php")&&str_contains($loader,'SN_Fresh20_R7_Message_Read_Hardening::register()'),'Fresh20 R7: message read-truth hardening must be loaded and registered.');
if($fails){fwrite(STDERR,"Four-plan review 3 failures (".count($fails)."/$checks):\n - ".implode("\n - ",$fails)."\n");exit(1);}echo "Four-plan review 3 message/Smail security: PASS ($checks checks)\n";