<?php
declare(strict_types=1);
$root=dirname(__DIR__);$main=file_get_contents($root.'/sabri-network.php');$readme=file_get_contents($root.'/readme.txt');$arch=file_get_contents($root.'/ARCHITECTURE.md');$quality=file_get_contents($root.'/tools/quality-check.sh');$package=file_get_contents($root.'/tools/package.sh');$repo=file_get_contents(dirname($root).'/README.md');$audit=file_get_contents(dirname($root).'/FORTY-ROUND-AUDIT-2026-08-07.md');$status=file_get_contents(dirname($root).'/STATUS.md');$fails=[];$checks=0;
function fpr4(bool $c,string $m):void{global $fails,$checks;$checks++;if(!$c)$fails[]=$m;}
fpr4(str_contains($main,'Version: 2.1.0')&&str_contains($main,"define('SN_VERSION', '2.1.0')"),'Plugin header/runtime version are both 2.1.0.');
fpr4(str_contains($readme,'Stable tag: 2.1.0')&&str_contains($readme,'= 2.1.0 ='),'Installable readme is version/changelog aligned.');
fpr4(str_contains($package,'17-sabri-network-and-messages-2.1.0')&&str_contains($package,"grep -q 'Version: 2.1.0'"),'Deterministic package contract targets immutable 2.1.0.');
foreach(['four-plan-review-1-governance-contracts.php','four-plan-review-2-transfer-concurrency-contracts.php','four-plan-review-3-message-smail-security-contracts.php','four-plan-review-4-fresh-release-contracts.php','two-plan-completion-contracts.php','future24-forty-round-corrective-static-contracts.php','fourth-fresh-twenty-round-contracts.php','fifth-fresh-twenty-round-contracts.php','fifth-fresh-migration-contracts.php','fifth-fresh-closure-contracts.php','fifth-fresh-release-truth-contracts.php','sixth-fresh-twenty-round-contracts.php','seventh-fresh-ten-round-contracts.php'] as $suite){fpr4(str_contains($quality,$suite),"Quality gate invokes $suite.");}
fpr4(str_contains($audit,'**Rounds in which one or more defects were found and corrected:** **18**')&&str_contains($repo,'Historical review ledgers'),'Historical forty-round evidence must remain preserved without being presented as current HEAD truth.');
fpr4(str_contains($status,'review suites')&&str_contains($status,'**54**'),'Repository status records the current explicit 54-suite gate.');
fpr4(str_contains($arch,'File 19 is the only notification-center')&&str_contains($arch,'SNE1'),'Architecture reflects notification ownership and message confidentiality.');
fpr4(str_contains($repo,'**Staging-Accepted:**')&&str_contains($repo,'**Live-Deployed:** not claimed')&&str_contains($repo,'**Operational:** not claimed'),'Repository documentation preserves the seven-status truth boundary.');
fpr4(str_contains($status,'Staging-Accepted')&&str_contains($status,'Live-Deployed')&&str_contains($status,'Operational'),'Current roadmap/release statuses remain explicit rather than falsely promoted.');
fpr4(str_contains($readme,'message requests')&&str_contains($readme,'scheduled and disappearing-message lifecycle'),'Current two-plan completion remains represented in installable release documentation.');
if($fails){fwrite(STDERR,"Four-plan review 4 failures (".count($fails)."/$checks):\n - ".implode("\n - ",$fails)."\n");exit(1);}echo "Four-plan review 4 fresh release: PASS ($checks checks)\n";
