<?php
/** Review 2: fresh adversarial privacy, concurrency and failure-path contracts. */
declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$checks=0;
$read=static function(string $path):string{$v=file_get_contents($path);if($v===false)throw new RuntimeException('Missing '.$path);return $v;};
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok)$failures[]=$message;};
$search=$read($root.'/includes/class-sn-message-search.php');$outbox=$read($root.'/includes/class-sn-outbox.php');$integrity=$read($root.'/includes/class-sn-message-integrity.php');$js=$read($root.'/assets/js/message-search.js');$quality=$read($root.'/tools/quality-check.sh');
$check(!preg_match('/message_search_tokens[^;]+body/is',$search),'Search index schema must not store message bodies.');
$check(!preg_match('/message_search_tokens[^;]+query/is',$search),'Search index schema must not store plaintext queries.');
$check(str_contains($search,"strlen(\$cursor) > 2048"),'Oversized cursors must fail closed.');
$check(str_contains($search,"hash_equals(\$expected, \$sig)"),'Cursor signatures must be timing-safe verified.');
$check(str_contains($search,"(int) (\$data['viewer'] ?? 0) !== \$viewer"),'A cursor must not cross viewers.');
$check(str_contains($search,"(int) (\$data['conversation'] ?? 0) !== \$conversation"),'A cursor must not cross conversations.');
$check(str_contains($search,"!hash_equals(\$filter, (string) (\$data['filter'] ?? ''))"),'A cursor must not cross filter scopes.');
$check(str_contains($search,"(int) (\$data['exp'] ?? 0) < time()"),'Expired cursors must fail closed.');
$check(str_contains($search,'SELECT * FROM')&&str_contains($search,'conversation_id=%d'),'Context queries must remain conversation scoped.');
$check(str_contains($search,'SN_Private_Files::formatted'),'Search results must reuse authorized private-file delivery.');
$check(str_contains($search,"\$request->get_param('confirm') !== true"),'Truthy strings must not authorize index destruction.');
$check(str_contains($outbox,"payload_hash")&&str_contains($outbox,"hash_equals((string) \$row->payload_hash"),'Event payload integrity must be checked before dispatch.');
$check(str_contains($outbox,"status='processing' AND locked_at<%s"),'Stale worker claims must be recoverable.');
$check(str_contains($outbox,"attempts=attempts+1")&&str_contains($outbox,'min(HOUR_IN_SECONDS'),'Retry attempts and backoff must be bounded.');
$check(str_contains($outbox,"private const DEFAULT_MAX_ATTEMPTS = 8")&&str_contains($outbox,'min(20,max(3'),'Maximum attempts must be bounded.');
$check(str_contains($outbox,"WHERE id=%d AND lock_token=%s"),'Only the current worker token may finalize a claim.');
$check(str_contains($outbox,"version=%d AND status IN ('dead','retry')"),'Manual retry must use optimistic version control.');
$adminSection=substr($outbox,strpos($outbox,'public static function admin_events'),3500);
$check(!str_contains($adminSection,"'payload'=>")&&!str_contains($adminSection,"'payload' =>"),'Administrator inventory must not expose raw event payload.');
$check(str_contains($outbox,"\$blocked = ['body','message_body','content','token','secret','password','credential','ice','sdp','candidate','storage_key','attachment_path']"),'Sensitive fields must be stripped from event metadata.');
$check(str_contains($outbox,"wp_is_uuid(\$event_uuid, 4)"),'Incoming events must use canonical UUIDv4 identities.');
$check(str_contains($outbox,"if (\$existing && (string) \$existing->status === 'processed') return true"),'Processed incoming events must be idempotent.');
$check(str_contains($outbox,"ROLLBACK")&&str_contains($outbox,"INSERT INTO \$table")&&str_contains($outbox,"'failed'"),'Failed inbox attempts must remain observable after rollback.');
$send=substr($integrity,strpos($integrity,'public static function send_message'),6000);
$check(strpos($send,'SN_Private_Files::create_from_upload')<strpos($send,'START TRANSACTION'),'Attachment bytes/ledger must exist before the message transaction so rollback cleanup remains addressable.');
$check(strpos($send,'SN_Message_Search::index_message')<strpos($send,"\$wpdb->query('COMMIT')"),'Message indexing must precede send commit.');
$check(strpos($send,"SN_Outbox::enqueue('message.sent'")<strpos($send,"\$wpdb->query('COMMIT')"),'Message event enqueue must precede send commit.');
$check(str_contains($send,'if ($attachment) SN_Private_Files::delete'),'A failed new-message transaction must clean its pre-created private attachment.');
$edit=substr($integrity,strpos($integrity,'public static function edit_message'),5200);
$check(str_contains($edit,"'message.edited:' . \$id . ':' . hash('sha256', \$body)"),'Distinct edits must not collide on one event identity.');
$check(strpos($edit,'SN_Message_Search::index_message')<strpos($edit,"\$wpdb->query('COMMIT')"),'Edit reindexing must be atomic.');
$delete=substr($integrity,strpos($integrity,'public static function delete_message'),5200);
$check(strpos($delete,"\$wpdb->query('COMMIT')")<strpos($delete,'SN_Private_Files::delete'),'Private bytes must be removed only after durable deletion commit.');
$check(strpos($delete,'SN_Message_Search::remove_message')<strpos($delete,"\$wpdb->query('COMMIT')"),'Search tokens must disappear in the deletion transaction.');
$receipt=substr($integrity,strpos($integrity,'public static function record_receipt'),9000);
$check(str_contains($receipt,'ORDER BY id ASC LIMIT %d'),'Receipt reconciliation must process ascending bounded ranges.');
$check(str_contains($receipt,'last_read_message_id=GREATEST(last_read_message_id,%d)'),'Read pointers must advance monotonically.');
$check(strpos($receipt,"SN_Outbox::enqueue('message.' . \$state")<strpos($receipt,"\$wpdb->query('COMMIT')"),'Receipt events must be atomic with receipt/pointer writes.');
$check(str_contains($receipt,"hash('sha256', \$user_id . '|' . \$raw . '|' . wp_salt('auth'))"),'Raw device identifiers must not be persisted.');
$check(str_contains($js,"credentials: 'same-origin'")&&str_contains($js,"'X-WP-Nonce'"),'Search requests must be same-origin and nonce authenticated.');
$check(str_contains($js,'encodeURIComponent(cursor)'),'Signed context cursors must be URL encoded.');
$check(str_contains($js,"event.key === 'Escape'")&&str_contains($js,"trigger.focus()"),'Search panel must close by keyboard and restore focus.');
$check(str_contains($quality,'search-outbox-review-1-static-contracts.php')&&str_contains($quality,'search-outbox-review-2-adversarial-contracts.php'),'Both independent reviews must run in the quality gate.');
if($failures){fwrite(STDERR,"Search/outbox review 2 failures (".count($failures)."/$checks):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "Search/outbox review 2 adversarial contracts: PASS ($checks checks)\n";
