<?php
/** Review 1: complete static contracts for indexed search and reliable event delivery. */
declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];$checks=0;
$read=static function(string $path):string{$v=file_get_contents($path);if($v===false)throw new RuntimeException('Missing '.$path);return $v;};
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok)$failures[]=$message;};
$main=$read($root.'/sabri-network.php');$search=$read($root.'/includes/class-sn-message-search.php');$outbox=$read($root.'/includes/class-sn-outbox.php');$integrity=$read($root.'/includes/class-sn-message-integrity.php');$js=$read($root.'/assets/js/message-search.js');$css=$read($root.'/assets/css/message-search.css');
$check(str_contains($main,"require_once SN_DIR . 'includes/class-sn-message-search.php'"),'Search authority must load.');
$check(str_contains($main,"require_once SN_DIR . 'includes/class-sn-outbox.php'"),'Outbox authority must load.');
$check(str_contains($main,"require_once SN_DIR . 'includes/class-sn-message-integrity.php'"),'Atomic mutation authority must load.');
$check(str_contains($main,'SN_Message_Search::register()'),'Search hooks must register.');
$check(str_contains($main,'SN_Outbox::register()'),'Outbox hooks must register.');
$check(str_contains($main,'SN_Message_Integrity::register()'),'Atomic route overrides must register.');
$check(str_contains($main,"'message_search_route'"),'Published File-17 contract must expose search.');
$check(str_contains($main,"'event_delivery_contract' => 'sn_network_event_dispatched'"),'Published contract must expose reliable event hook.');
$check(str_contains($search,"'/conversations/(?P<id>\\d+)/search'"),'Conversation search route must exist.');
$check(str_contains($search,"'/conversations/(?P<id>\\d+)/search/context'"),'Signed context route must exist.');
$check(str_contains($search,'message_search_tokens'),'Search token table must be File-17-owned.');
$check(str_contains($search,'UNIQUE KEY message_token'),'Search index must be idempotent per message/token.');
$check(str_contains($search,'conversation_token_message'),'Search index must support scoped token lookup.');
$check(str_contains($search,"private const MAX_QUERY_CHARS = 160"),'Query length must be bounded.');
$check(str_contains($search,"private const MAX_TERMS = 8"),'Search term count must be bounded.');
$check(str_contains($search,"private const MAX_RESULTS = 50"),'Result pages must be bounded.');
$check(str_contains($search,"private const MAX_SCAN = 500"),'Search scan budget must be bounded.');
$check(str_contains($search,"private const MAX_CONTEXT = 25"),'Context windows must be bounded.');
$check(str_contains($search,"hash_hmac('sha256', \$term"),'Index tokens must be keyed hashes.');
$check(str_contains($search,"wp_salt('auth') . '|sn-message-search-v1'"),'Search hashes must use a server secret.');
$check(str_contains($search,'SN_DB::is_member($conversation_id, $viewer_id)'),'Every search must revalidate active membership.');
$check(str_contains($search,"'viewer' => \$viewer_id")&&str_contains($search,"'conversation' => \$conversation_id")&&str_contains($search,"'filter' => \$filter_hash"),'Search cursor must bind viewer, conversation and filters.');
$check(str_contains($search,"'snapshot' => \$snapshot")&&str_contains($search,"m.id<=%d"),'Search must preserve a stable snapshot.');
$check(str_contains($search,"['quarantined','moderation_removed','removed','unsent','expired','rejected']"),'Hidden lifecycle states must be excluded.');
$check(str_contains($search,"'filter_hash' => \$filter_hash")&&!str_contains($search,"'query' => \$query"),'Search audit must retain only non-plaintext query evidence.');
$check(str_contains($search,"\$request->get_param('confirm') !== true"),'Destructive rebuild must require exact boolean confirmation.');
$check(str_contains($outbox,'event_outbox')&&str_contains($outbox,'event_inbox'),'Outbox and inbox persistence must exist.');
$check(str_contains($outbox,'UNIQUE KEY event_key')&&str_contains($outbox,'UNIQUE KEY event_uuid'),'Outgoing events must be idempotent.');
$check(str_contains($outbox,'UNIQUE KEY producer_event'),'Incoming events must be idempotent by producer/UUID.');
$check(str_contains($outbox,"status='processing'")&&str_contains($outbox,'lock_token'),'Workers must claim events atomically.');
$check(str_contains($outbox,"status='dead'")||str_contains($outbox,"\$dead ? 'dead' : 'retry'"),'Terminal/dead-letter state must exist.');
$check(str_contains($outbox,"do_action('sn_network_event_dispatched'"),'Consumers must receive canonical event facts.');
$check(str_contains($outbox,"apply_filters('sn_network_outbox_delivery_result'"),'Delivery must require an explicit acknowledgement contract.');
$check(str_contains($outbox,"status='processed'")&&str_contains($outbox,"START TRANSACTION"),'Inbox processing must be transactional.');
$check(str_contains($outbox,"ON DUPLICATE KEY UPDATE status=IF(status='processed','processed','failed')"),'Failed inbox state must survive rollback without overwriting processed truth.');
$check(str_contains($integrity,'register_rest_route')&&str_contains($integrity,'], true);'),'Canonical mutation routes must be overridden intentionally.');
$check(substr_count($integrity,"SN_Outbox::enqueue('message.")>=4,'Send/edit/delete/receipt events must enter the outbox.');
$check(str_contains($integrity,'SN_Message_Search::index_message($message_id)')&&str_contains($integrity,'SN_Message_Search::remove_message($id)'),'Message mutations must maintain the search index.');
$check(str_contains($integrity,"\$wpdb->query('COMMIT')")&&str_contains($integrity,"\$wpdb->query('ROLLBACK')"),'Message/search/event mutations must commit or roll back together.');
$check(str_contains($js,'textContent =')&&!str_contains($js,'insertAdjacentHTML'),'Dynamic search rendering must avoid HTML injection.');
$check(str_contains($css,'@media(max-width:900px)')&&str_contains($css,'@media(prefers-reduced-motion:reduce)'),'Search UI must be mobile and reduced-motion ready.');
if($failures){fwrite(STDERR,"Search/outbox review 1 failures (".count($failures)."/$checks):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "Search/outbox review 1 static contracts: PASS ($checks checks)\n";
