<?php
/** Seventh fresh 10-round permanent regression contracts plus later release-truth guards. */
declare(strict_types=1);
$root=dirname(__DIR__);$repo=dirname($root);$fail=[];$checks=0;
$read=static fn(string $p):string=>(string)file_get_contents($root.'/'.$p);
$readRepo=static fn(string $p):string=>(string)file_get_contents($repo.'/'.$p);
$check=static function(bool $ok,string $m)use(&$fail,&$checks):void{$checks++;if(!$ok)$fail[]=$m;};
$q=$read('tools/quality-check.sh');
$p=$read('tools/package.sh');
$workflow=(string)file_get_contents($repo.'/.github/workflows/quality.yml');
$r=$read('includes/class-sn-round20-correction.php');
$m=$read('includes/class-sn-membership-assertions.php');
$msg=$read('includes/class-sn-message-runtime-hardening.php');
$attach=$read('includes/class-sn-attachment-runtime-hardening.php');
$smailFinal=$read('includes/class-sn-fourth-fresh-smail-hardening.php');
$smailRuntime=$read('includes/class-sn-smail-runtime-hardening.php');
$voiceFinal=$read('includes/class-sn-fifth-fresh-feature-hardening.php');
$callRuntime=$read('includes/class-sn-call-runtime-hardening.php');
$privacyFinal=$read('includes/class-sn-sixth-fresh-privacy-hardening.php');
$migration=$read('includes/class-sn-fifth-fresh-migration-hardening.php');
$admin=$read('includes/class-sn-admin.php');
$searchHardening=$read('includes/class-sn-fourth-fresh-search-hardening.php');
$space7=$read('includes/class-sn-spaces-part-7.php');
$space5=$read('includes/class-sn-spaces-part-5.php');
$space6=$read('includes/class-sn-spaces-part-6.php');
$space9=$read('includes/class-sn-spaces-part-9.php');
$readme=$read('readme.txt');
$changelog=$read('CHANGELOG.md');
$repoReadme=$readRepo('README.md');
$status=$readRepo('STATUS.md');
$coding=$readRepo('CODING-COMPLETENESS.md');
$manifest=$readRepo('MANIFEST.md');
$qa=$read('QA-INVENTORY.txt');
$boundary=$read('CURRENT-CANDIDATE-BOUNDARY.txt');
$check(str_contains($r,"assets/js/round20-correction.js"),'R1: Round-20 correction must retain its registered browser runtime asset.');
$check(str_contains($q,'assets/js/round20-correction.js')&&str_contains($q,'includes/class-sn-round20-correction.php'),'R1: source quality gate must require the Round-20 PHP/JS runtime surfaces.');
$check(str_contains($q,'round20-correction.js'),'R1: source quality gate must syntax-check the Round-20 browser runtime.');
$check(str_contains($p,'assets/js/round20-correction.js')&&str_contains($p,'includes/class-sn-round20-correction.php'),'R1: package gate must require the Round-20 PHP/JS runtime surfaces.');
$check(str_contains($p,'round20-correction.js'),'R1: package gate must syntax-check the Round-20 browser runtime.');
$check(str_contains($m,'return self::available();'),'R2: canonical File-00 contract functions must establish base identity-authority availability.');
$check(!str_contains($m,'return self::available() && $available !== false;'),'R2: a legacy heuristic false seed must not veto a valid File-00 communication contract.');
$check(str_contains($m,"add_filter('sn_network_identity_authority_available', [self::class, 'filter_authority_available'], PHP_INT_MIN)"),'R2: canonical contract discovery must run first so later filters can still deny availability.');
$check(substr_count($msg,'SN_Membership_Assertions::clear_cache(')>=2,'R3: both new-message and duplicate-reconciliation mutation paths must refresh File-00 assertion state.');
$check(substr_count($msg,'$fresh_access=SN_Policy::access();')>=2,'R3: both mutation paths must rerun canonical access policy at the mutation point.');
$check(strpos($msg,'SN_Membership_Assertions::clear_cache($user_id);')<strpos($msg,'$locked=SN_Spaces::assert_post_allowed_in_transaction'),'R3: new-message File-00 revalidation must precede locked mutation side effects.');
$hashPos=strpos($attach,"hash_file('sha256', \$candidate)");
$authPos=strpos($attach,'if (!is_user_logged_in()) return;');
$noncePos=strpos($attach,"wp_verify_nonce(\$nonce, 'sn_private_file_'");
$accessPos=strpos($attach,'SN_DB::user_can_access_attachment($attachment_id, $user_id)');
$check($authPos!==false&&$noncePos!==false&&$accessPos!==false&&$hashPos!==false&&$authPos<$hashPos&&$noncePos<$hashPos&&$accessPos<$hashPos,'R4: private-file integrity hashing must happen only after login, nonce and object authorization checks.');
$check(str_contains($smailFinal,'return SN_Smail_Runtime_Hardening::send($request);'),'Later R5: final Smail send route must delegate to the hardened Smail runtime.');
$check(str_contains($smailFinal,'return SN_Smail_Runtime_Hardening::save_draft($request);'),'Later R5: final Smail draft route must preserve hardened locking/version semantics.');
$check(!str_contains($smailFinal,'return SN_Smail::send($request);'),'Later R5: final Smail route must not fall back to the legacy Smail mutation path.');
$check(str_contains($voiceFinal,'SN_Fourth_Fresh_Review_Hardening::send_message($forward)'),'Later R5: final voice-note route must use the canonical hardened message owner.');
$check(!str_contains($voiceFinal,'SN_Message_Integrity::send_message($forward)'),'Later R5: final voice-note route must not bypass current point-of-action authorization/idempotency hardening.');
$check(str_contains($callRuntime,'private static function append_space_owner_lock'),'Later R7: call/meeting runtime must resolve the canonical space-owner lock for space-backed conversations.');
$check(substr_count($callRuntime,'self::append_space_owner_lock($locks,')>=4,'Later R7: creation and existing call/meeting mutation paths must join the canonical space lock.');
$check(str_contains($callRuntime,"'SELECT id FROM ' . SN_DB::table('spaces') . ' WHERE conversation_id=%d LIMIT 1'")&&str_contains($callRuntime,"'sn:f17:space:'"),'Later R7: media mutation locking must use the same canonical space lock namespace as space governance.');
$check(str_contains($privacyFinal,"add_action('sn_network_retry_private_delete', [self::class, 'ensure_private_byte_retry'], PHP_INT_MAX, 1)"),'Later R8: final privacy hardening must run after canonical private-byte retry attempts.');
$check(str_contains($privacyFinal,'public static function ensure_private_byte_retry(int $attachment_id): void'),'Later R8: revoked private bytes need a durable retry owner after the initial retry budget.');
$check(str_contains($privacyFinal,"wp_schedule_single_event(time() + HOUR_IN_SECONDS, 'sn_network_retry_private_delete', [\$attachment_id])"),'Later R8: a still-existing revoked private object must remain scheduled for canonical deletion.');
$check(str_contains($privacyFinal,"do_action('sn_network_private_bytes_delete_stalled'")&&str_contains($privacyFinal,"SN_DB::audit('attachment_delete_stalled'"),'Later R8: exhausted initial private-byte retries must emit durable stalled-deletion evidence without abandoning cleanup.');
$check(str_contains($migration,"'completion_path'=>'post-lock-fast-path'")&&str_contains($migration,"'status'=>'complete'")&&str_contains($migration,'if (!$force && (string)get_option(\'sn_plugin_version\',\'\') === SN_VERSION && self::verify_schema()) {'),'Fresh R1: verified post-lock migration fast-path must republish complete migration state before returning.');
$check(str_contains($migration,"'sn_message_receipts_schema_version'")&&!str_contains($migration,"'sn_conference_provider_schema_version','sn_messages_schema_version'"),'Fresh R1: migration rollback snapshot must track the actual Messages receipt schema-version option rather than the obsolete key.');
$check(str_contains($admin,'SN_Fifth_Fresh_Migration_Hardening::upgrade(true)')&&!str_contains($admin,'SN_DB::install();')&&!str_contains($admin,"update_option('sn_plugin_version', SN_VERSION"),'Fresh R2: administrator repair must use the governed full migration and must not publish plugin-version truth independently.');
$check(str_contains($admin,"esc_html__('Sabri Network repair failed', 'sabri-network')")&&str_contains($admin,"['response' => 503]"),'Fresh R2: governed repair migration failure must fail closed instead of reporting success.');
$check(str_contains($searchHardening,"add_action('rest_api_init', [self::class, 'override_routes'], 2300)")&&str_contains($searchHardening,"'/admin/message-search/rebuild'")&&str_contains($searchHardening,"'callback'=>[self::class, 'rebuild']"),'Fresh R3: final administrator search-rebuild route must be owned by the lossless search hardening layer.');
$check(str_contains($searchHardening,"update_option(self::REBUILD_OPTION, true, false)")&&str_contains($searchHardening,"update_option(self::ERROR_OPTION")&&str_contains($searchHardening,"return new WP_Error('search_rebuild_deferred'"),'Fresh R3: manual rebuild must publish fail-closed rebuild/error state and defer rather than skip an unindexable row.');
$check(str_contains($searchHardening,"self::backfill();")&&str_contains($searchHardening,"self::finish_rebuild();")&&!str_contains($searchHardening,'SN_Message_Search::backfill();'),'Fresh R3: manual/final rebuild must stay on the monotonic hardening owner and never delegate to the lossy legacy backfill.');
$check(str_contains($smailRuntime,'private static function same_send_request')&&substr_count($smailRuntime,'self::same_send_request(')>=3,'Fresh R4: every Smail duplicate/race reconciliation path must prove exact recipients, subject and body before returning success.');
$check(str_contains($smailRuntime,"new WP_Error('smail_idempotency_conflict'")&&str_contains($smailRuntime,"SELECT user_id FROM '.SN_DB::table('smail_states')")&&str_contains($smailRuntime,'SN_Message_Body::decrypt_row($message)'),'Fresh R4: Smail request identity must be reconstructed from committed recipient state and canonical body and conflict explicitly on mismatch.');
$check(str_contains($migration,"'space_governance'")&&!str_contains($migration,"'space_bans','space_audit','presence_devices'"),'Fresh R5: governed schema verification must require the actual SN_Spaces governance table, not the nonexistent space_audit name.');
$check(str_contains($space9,"return SN_DB::table('space_governance');"),'Fresh R5: the spaces audit owner must remain the canonical space_governance table.');
$check(str_contains($space7,'private static function communication_eligible')&&str_contains($space7,'SN_Membership_Assertions::clear_cache($user)')&&str_contains($space7,"(\$assertion['eligible']??false)!==true")&&str_contains($space7,"(\$assertion['can_message']??false)!==true"),'Fresh R5: space target eligibility must be freshly proven from File-00 eligible/can_message assertions.');
$check(str_contains($space7,'$identity=self::communication_eligible($user);if(is_wp_error($identity))return $identity;'),'Fresh R5: every join/invite activation eligibility path must enforce current File-00 communication eligibility.');
$check(str_contains($space5,'$identity=self::communication_eligible($target);if(is_wp_error($identity)')&&str_contains($space6,'$identity=self::communication_eligible($target);if(is_wp_error($identity)'),'Fresh R5: positive role and ownership transitions must revalidate the target while removal/ban paths remain available.');
$check(str_contains($workflow,'run_test seventh-fresh-ten-round-contracts.php'),'R10: PHP 8.1 current-boundary job must execute the seventh-fresh regression suite.');
$check(str_contains($workflow,'php sabri-network/tests/seventh-fresh-ten-round-contracts.php'),'R10: PHP 8.3 release job must explicitly execute the seventh-fresh suite after the full quality gate.');
$check(str_contains($readme,'54 PHP review suites')&&str_contains($readme,'10 JavaScript syntax entry points'),'Later R1: readme release truth must match the current explicit QA inventory.');
$check(str_contains($changelog,'54 PHP review suites')&&str_contains($changelog,'10 JavaScript syntax entry points'),'Later R1: changelog release truth must match the current explicit QA inventory.');
$check(str_contains($readme,'f832f7b2d4bb4cf67fc9749e1eb9d3219f5fc0a2'),'Later R1: readme must identify the latest completed reviewed source candidate instead of silently reusing sixth-cycle evidence.');
foreach(['root README'=>$repoReadme,'STATUS'=>$status,'CODING-COMPLETENESS'=>$coding,'QA-INVENTORY'=>$qa,'CURRENT-CANDIDATE-BOUNDARY'=>$boundary] as $name=>$text){
    $check(str_contains($text,'54')&&str_contains($text,'10'),"Later R2: $name must reflect the current 54-suite/10-JS quality truth.");
    $check(!str_contains($text,'53 PHP review suites')&&!str_contains($text,'9 JavaScript syntax entry points'),"Later R2: $name must not retain stale 53/9 current-state claims.");
}
$check(!file_exists($repo.'/CHECKSUMS.sha256'),'Later R2: obsolete committed root CHECKSUMS.sha256 must not masquerade as current package truth.');
$check(str_contains($manifest,'generated from the exact staged release tree')&&str_contains($manifest,'MANIFEST.sha256'),'Later R2: repository manifest must describe the generated exact staged-source manifest.');
$check(!str_contains($manifest,'CHECKSUMS.sha256 is the canonical integrity manifest'),'Later R2: manifest must not revive the obsolete static-checksum claim.');
if($fail){fwrite(STDERR,"Seventh/later fresh contract failures (".count($fail)."/$checks):\n - ".implode("\n - ",$fail)."\n");exit(1);}echo "Seventh/later fresh contracts: PASS ($checks checks)\n";
