<?php
/** Seventh fresh 10-round permanent regression contracts plus later release-truth guards. */
declare(strict_types=1);
$root=dirname(__DIR__);$repo=dirname($root);$fail=[];$checks=0;
$read=static fn(string $p):string=>(string)file_get_contents($root.'/'.$p);
$readRepo=static fn(string $p):string=>(string)file_get_contents($repo.'/'.$p);
$check=static function(bool $ok,string $m)use(&$fail,&$checks):void{$checks++;if(!$ok)$fail[]=$m;};
$q=$read('tools/quality-check.sh');
$p=$read('tools/package.sh');
$workflow=(string)file_get_contents($repo.'/.github/workflows/quality.yml');
$r=$read('includes/class-sn-round20-correction.php');
$m=$read('includes/class-sn-membership-assertions.php');
$msg=$read('includes/class-sn-message-runtime-hardening.php');
$attach=$read('includes/class-sn-attachment-runtime-hardening.php');
$smailFinal=$read('includes/class-sn-fourth-fresh-smail-hardening.php');
$voiceFinal=$read('includes/class-sn-fifth-fresh-feature-hardening.php');
$callRuntime=$read('includes/class-sn-call-runtime-hardening.php');
$readme=$read('readme.txt');
$changelog=$read('CHANGELOG.md');
$repoReadme=$readRepo('README.md');
$status=$readRepo('STATUS.md');
$coding=$readRepo('CODING-COMPLETENESS.md');
$manifest=$readRepo('MANIFEST.md');
$qa=$read('QA-INVENTORY.txt');
$boundary=$read('CURRENT-CANDIDATE-BOUNDARY.txt');
$check(str_contains($r,"assets/js/round20-correction.js"),'R1: Round-20 correction must retain its registered browser runtime asset.');
$check(str_contains($q,'assets/js/round20-correction.js')&&str_contains($q,'includes/class-sn-round20-correction.php'),'R1: source quality gate must require the Round-20 PHP/JS runtime surfaces.');
$check(str_contains($q,'round20-correction.js'),'R1: source quality gate must syntax-check the Round-20 browser runtime.');
$check(str_contains($p,'assets/js/round20-correction.js')&&str_contains($p,'includes/class-sn-round20-correction.php'),'R1: package gate must require the Round-20 PHP/JS runtime surfaces.');
$check(str_contains($p,'round20-correction.js'),'R1: package gate must syntax-check the Round-20 browser runtime.');
$check(str_contains($m,'return self::available();'),'R2: canonical File-00 contract functions must establish base identity-authority availability.');
$check(!str_contains($m,'return self::available() && $available !== false;'),'R2: a legacy heuristic false seed must not veto a valid File-00 communication contract.');
$check(str_contains($m,"add_filter('sn_network_identity_authority_available', [self::class, 'filter_authority_available'], PHP_INT_MIN)"),'R2: canonical contract discovery must run first so later filters can still deny availability.');
$check(substr_count($msg,'SN_Membership_Assertions::clear_cache(')>=2,'R3: both new-message and duplicate-reconciliation mutation paths must refresh File-00 assertion state.');
$check(substr_count($msg,'$fresh_access=SN_Policy::access();')>=2,'R3: both mutation paths must rerun canonical access policy at the mutation point.');
$check(strpos($msg,'SN_Membership_Assertions::clear_cache($user_id);')<strpos($msg,'$locked=SN_Spaces::assert_post_allowed_in_transaction'),'R3: new-message File-00 revalidation must precede locked mutation side effects.');
$hashPos=strpos($attach,"hash_file('sha256', \$candidate)");
$authPos=strpos($attach,'if (!is_user_logged_in()) return;');
$noncePos=strpos($attach,"wp_verify_nonce(\$nonce, 'sn_private_file_'");
$accessPos=strpos($attach,'SN_DB::user_can_access_attachment($attachment_id, $user_id)');
$check($authPos!==false&&$noncePos!==false&&$accessPos!==false&&$hashPos!==false&&$authPos<$hashPos&&$noncePos<$hashPos&&$accessPos<$hashPos,'R4: private-file integrity hashing must happen only after login, nonce and object authorization checks.');
$check(str_contains($smailFinal,'return SN_Smail_Runtime_Hardening::send($request);'),'Later R5: final Smail send route must delegate to the hardened Smail runtime.');
$check(str_contains($smailFinal,'return SN_Smail_Runtime_Hardening::save_draft($request);'),'Later R5: final Smail draft route must preserve hardened locking/version semantics.');
$check(!str_contains($smailFinal,'return SN_Smail::send($request);'),'Later R5: final Smail route must not fall back to the legacy Smail mutation path.');
$check(str_contains($voiceFinal,'SN_Fourth_Fresh_Review_Hardening::send_message($forward)'),'Later R5: final voice-note route must use the canonical hardened message owner.');
$check(!str_contains($voiceFinal,'SN_Message_Integrity::send_message($forward)'),'Later R5: final voice-note route must not bypass current point-of-action authorization/idempotency hardening.');
$check(str_contains($callRuntime,'private static function append_space_owner_lock'),'Later R7: call/meeting runtime must resolve the canonical space-owner lock for space-backed conversations.');
$check(substr_count($callRuntime,'self::append_space_owner_lock($locks,')>=4,'Later R7: creation and existing call/meeting mutation paths must join the canonical space lock.');
$check(str_contains($callRuntime,"'SELECT id FROM ' . SN_DB::table('spaces') . ' WHERE conversation_id=%d LIMIT 1'")&&str_contains($callRuntime,"'sn:f17:space:'"),'Later R7: media mutation locking must use the same canonical space lock namespace as space governance.');
$check(str_contains($workflow,'run_test seventh-fresh-ten-round-contracts.php'),'R10: PHP 8.1 current-boundary job must execute the seventh-fresh regression suite.');
$check(str_contains($workflow,'php sabri-network/tests/seventh-fresh-ten-round-contracts.php'),'R10: PHP 8.3 release job must explicitly execute the seventh-fresh suite after the full quality gate.');
$check(str_contains($readme,'54 PHP review suites')&&str_contains($readme,'10 JavaScript syntax entry points'),'Later R1: readme release truth must match the current explicit QA inventory.');
$check(str_contains($changelog,'54 PHP review suites')&&str_contains($changelog,'10 JavaScript syntax entry points'),'Later R1: changelog release truth must match the current explicit QA inventory.');
$check(str_contains($readme,'f832f7b2d4bb4cf67fc9749e1eb9d3219f5fc0a2'),'Later R1: readme must identify the latest completed reviewed source candidate instead of silently reusing sixth-cycle evidence.');
foreach(['root README'=>$repoReadme,'STATUS'=>$status,'CODING-COMPLETENESS'=>$coding,'QA-INVENTORY'=>$qa,'CURRENT-CANDIDATE-BOUNDARY'=>$boundary] as $name=>$text){
    $check(str_contains($text,'54')&&str_contains($text,'10'),"Later R2: $name must reflect the current 54-suite/10-JS quality truth.");
    $check(!str_contains($text,'53 PHP review suites')&&!str_contains($text,'9 JavaScript syntax entry points'),"Later R2: $name must not retain stale 53/9 current-state claims.");
}
$check(!file_exists($repo.'/CHECKSUMS.sha256'),'Later R2: obsolete committed root CHECKSUMS.sha256 must not masquerade as current package truth.');
$check(str_contains($manifest,'generated from the exact staged release tree')&&str_contains($manifest,'MANIFEST.sha256'),'Later R2: repository manifest must describe the generated exact staged-source manifest.');
$check(!str_contains($manifest,'CHECKSUMS.sha256 is the canonical integrity manifest'),'Later R2: manifest must not revive the obsolete static-checksum claim.');
if($fail){fwrite(STDERR,"Seventh/later fresh contract failures (".count($fail)."/$checks):\n - ".implode("\n - ",$fail)."\n");exit(1);}echo "Seventh/later fresh contracts: PASS ($checks checks)\n";
