<?php
/** File 17 current governing-plan completion contracts. */
declare(strict_types=1);
$root=dirname(__DIR__);$repo=dirname($root);$fail=[];$checks=0;
$read=static fn(string $p):string=>(string)file_get_contents($p);
$check=static function(bool $ok,string $msg)use(&$fail,&$checks):void{$checks++;if(!$ok)$fail[]=$msg;};
$main=$read($root.'/sabri-network.php');
$compat=$read($root.'/includes/class-sn-compatibility-hardening.php');
$runtime=$read($root.'/includes/class-sn-two-plan-runtime-hardening.php');
$completion=$read($root.'/includes/class-sn-two-plan-completion.php');
$firewall=$read($root.'/includes/class-sn-two-plan-contract-firewall.php');
$future=$read($root.'/includes/class-sn-future-superset.php').$read($root.'/includes/class-sn-future-superset-part-1.php').$read($root.'/includes/class-sn-future-superset-part-2.php').$read($root.'/includes/class-sn-future-superset-part-3.php').$read($root.'/includes/class-sn-future-superset-core.php');
$review_loader=$read($root.'/includes/class-sn-future24-review-hardening.php');
$review_o=$read($root.'/includes/class-sn-future24-review-hardening-o.php');
$future_js=$read($root.'/assets/js/future-superset.js');$future_css=$read($root.'/assets/css/future-superset.css');
$quality=$read($root.'/tools/quality-check.sh');

$check(str_contains($main,'Version: 2.1.0')&&str_contains($main,"define('SN_VERSION', '2.1.0')"),'File 17 completion release must have an immutable 2.1.0 runtime identity.');
$check(str_contains($compat,"require_once SN_DIR . 'includes/class-sn-two-plan-completion.php'")&&str_contains($compat,'SN_Two_Plan_Completion::register()'),'Completion layer must be loaded through the existing canonical backend.');
$check(str_contains($completion,'message-requests')&&str_contains($completion,"'accept','decline','report','cancel'"),'Unknown-sender message request quarantine and decisions must exist.');
$check(str_contains($completion,'message_request_recipient')&&str_contains($completion,'message_request_sender'),'Message requests must protect both sender and recipient with rate limits.');
$check(str_contains($completion,"SN_Communication_Crypto::encrypt(\$body,'message-request|")&&str_contains($completion,"SN_Communication_Crypto::decrypt((string)\$locked->body_cipher"),'Message-request content must be authenticated-encrypted at rest.');
$check(str_contains($completion,"SN_Policy::can_contact(\$actor, \$recipient, 'request')")&&str_contains($completion,'SN_DB::is_blocked'),'Fresh policy/block checks must govern message-request actions.');
$check(str_contains($completion,'scheduled-messages')&&str_contains($completion,'dispatch_due_scheduled')&&str_contains($completion,"'scheduled'=>true"),'Scheduled messages must have create/cancel/delivery paths.');
$check(str_contains($completion,"'scheduled-message|'" )&&str_contains($completion,'SN_Message_Body::encrypt'),'Scheduled plaintext must be encrypted before storage and canonical delivery.');
$check(str_contains($completion,'/polls')&&str_contains($completion,'poll-vote')&&str_contains($completion,'/checklists')&&str_contains($completion,'toggle_checklist'),'Poll and collaborative-checklist workflows must exist.');
$check(str_contains($completion,"clinical_decision_substitute'=>false"),'Polls/checklists must not become clinical-decision authority.');
$check(str_contains($completion,'/expiry')&&str_contains($completion,'message_has_legal_hold')&&str_contains($completion,'SN_Message_Search::remove_message'),'Disappearing messages must preserve legal holds and remove search projection.');
$check(str_contains($completion,'/translate')&&str_contains($completion,"apply_filters('sn_network_translate_message',null")&&str_contains($completion,"'source_persisted'=>false"),'Translation must be fail-closed and transient through an approved adapter.');
$check(str_contains($completion,'voice-notes')&&str_contains($completion,'playback_speeds')&&str_contains($completion,'transcript_available'),'Voice-note workflow must expose playback/transcript capability metadata.');
$check(str_contains($completion,"register_rest_route('sabri-network/v2', '/updates'")&&str_contains($completion,"SN_Communication_Crypto::encrypt(\$body,'temporary-update|"),'Temporary-update body must use encrypted-at-rest replacement routes.');
$check(str_contains($completion,"'forum_question','ama_session','wiki_page','event'")&&str_contains($completion,'community_health'),'Forum, AMA, wiki, events/cohorts and aggregate community-health features must exist.');
$check(str_contains($completion,'community-settings')&&str_contains($completion,'join_questions')&&str_contains($completion,"['owner','administrator','moderator']"),'Community rules/onboarding and moderator roles must be enforceable.');
$check(str_contains($completion,"'notification_owner'=>'file-19'")&&str_contains($completion,"'global_search_owner'=>'file-26'")&&str_contains($completion,"'identity_owner'=>'file-00/file-02'"),'Canonical cross-file owners must remain explicit.');
$check(str_contains($main,"'file_transfer_max_bytes' => SN_File_Transfer::MAX_FILE_BYTES")&&str_contains($completion,"'message_requests'=>true"),'The completion layer must extend, not replace, the existing 1 GiB canonical transfer system.');
$check(!str_contains($completion,'wp_insert_attachment')&&!str_contains($completion,'media_handle_upload'),'New private communication must not use the public WordPress media library.');
$check(!preg_match('/(?:E2EE enabled|end-to-end encrypted by default|production-ready)/i',$completion),'The completion source must not make unsupported E2EE/production claims.');
$check(str_contains($completion,'register_exporter')&&str_contains($completion,'register_eraser'),'New personal-data domains must participate in privacy export/erasure.');
$check(str_contains($completion,'admin/two-plan-completion')&&str_contains($completion,"'staging_acceptance'=>false")&&str_contains($completion,"'live_deployment'=>false"),'Runtime health must preserve staging/live separation.');
$check(str_contains($quality,'two-plan-completion-contracts.php'),'The explicit quality gate must execute this suite.');
$check(str_contains($compat,'class-sn-two-plan-contract-firewall.php')&&str_contains($compat,'SN_Two_Plan_Contract_Firewall::register()'),'The completion contract firewall must be loaded by the canonical hardening layer.');
$check(str_contains($firewall,'sn_idempotency_key_required')&&str_contains($firewall,"get_header('Idempotency-Key')")&&str_contains($firewall,"'state' => 'processing'"),'New completion mutations must require caller-supplied idempotency and fail closed while an outcome is uncertain.');
$check(str_contains($firewall,'response_cipher')&&str_contains($firewall,"SN_Communication_Crypto::encrypt(\$json, 'two-plan-idempotency|"),'Idempotency replay cache must encrypt successful response payloads at rest.');
$check(str_contains($firewall,"visibility !== 'discoverable_private'")&&str_contains($firewall,"\$item['body'] = ''")&&str_contains($firewall,"\$item['body_withheld'] = true"),'Discoverable-private community listings must expose metadata only to non-members.');

$check(str_contains($runtime,"require_once SN_DIR . 'includes/class-sn-future-superset.php'")&&str_contains($runtime,'SN_Future_Superset::register()'),'Future-24 must be loaded through the existing canonical runtime hardening layer.');
$check(str_contains($future,'FEATURE_COUNT=24'),'Future superset must declare all 24 approved enhancements.');
for($i=1;$i<=24;$i++)$check(str_contains($future,sprintf('F17-FUT-%02d',$i)),sprintf('F17-FUT-%02d must be implemented.',$i));
$check(str_contains($future,'sn_network_e2ee_provider_status')&&str_contains($future,'audited'),'E2EE must remain audited-provider gated rather than falsely claimed.');
$check(str_contains($future,'sn_network_step_up_verified')&&str_contains($future,'capture_message_version')&&str_contains($future,'_sn_future_snapshot_id'),'Sensitive lock and prior-revision capture must execute server-side.');
$check(str_contains($future,'sn_network_notification_requested'),'Reminders must delegate delivery to File 19.');
$check(str_contains($future,"['file-06','file-12']")&&str_contains($future,'sn_network_case_discussion_professional_allowed'),'Scholarly citations and case discussions must preserve owner/safety boundaries.');
$check(str_contains($future,'sn_network_breakout_create_result')&&str_contains($future,'sn_network_call_host_transfer_result'),'Breakouts and host transfer must stay conference-provider gated.');
$check(str_contains($future,'sn_network_ai_assistant_result')&&str_contains($future,"'ai_owner'=>'file-16'"),'AI authority must remain File 16.');
$check(str_contains($future,'sn_network_private_semantic_search_result')&&str_contains($future,"'exported_to_file26'=>false"),'Private semantic search must remain File 17 and must not feed File 26.');
$check(str_contains($future,'sn_network_interop_provider_ready')&&str_contains($future,'sn_network_interop_remote_allowed'),'Interoperability must require approved provider and remote destination.');
$check(!str_contains($future,'wp_insert_attachment')&&!str_contains($future,'media_handle_upload'),'Future-24 must not create a parallel public-media backend.');
$check(str_contains($future_js,'future/capabilities')&&str_contains($future_js,'future/reminders')&&str_contains($future_js,'future/templates'),'Future-24 must have practical user-facing workspace controls.');
$check(str_contains($future_css,'prefers-reduced-motion')&&str_contains($future_css,'44px')&&str_contains($future_css,'#087a4e'),'Future-24 CSS must preserve accessibility and Sabri Green.');
$check(str_contains($future,"usort(\$participants")&&str_contains($future,"'f17-safety-v1|'"),'Safety-number derivation must canonically order both peers so both directions match.');
$check(str_contains($firewall,'/future/e2ee-policy')&&str_contains($firewall,'/future/community-invites')&&str_contains($firewall,'/future/ai-assistant')&&str_contains($firewall,'/future/interop'),'Future-24 mutations must be covered by the canonical caller-supplied idempotency firewall.');

$check(substr_count($runtime,'SN_Future_Superset::register();')===1,'Runtime hardening must be the single Future-24 registration owner.');
$check(substr_count($compat,'SN_Future_Superset::register();')===0,'Compatibility hardening must not register Future-24 a second time.');
$check(str_contains($review_loader,"class-sn-future24-review-hardening-o.php")&&str_contains($review_loader,'SN_Future24_Review_Hardening_O::register()'),'Round-38 hardening O must be loaded and registered.');
$check(str_contains($review_o,'future24_mutation')&&str_contains($review_o,'sn_future24_rate_limited'),'Advanced Future-24 mutations must have a global abuse budget.');
$check(str_contains($review_o,"feature_id='F17-FUT-10'")&&str_contains($review_o,"state='processing'")&&str_contains($review_o,"state='queued'")&&str_contains($review_o,'cleanup_breakouts'),'Bulk-job crash recovery and breakout-expiry ordering must be hardened.');

if($checks!==71)$fail[]='Expected 71 checks, got '.$checks;
if($fail){fwrite(STDERR,"Two-plan completion failures (".count($fail)."/$checks):\n - ".implode("\n - ",$fail)."\n");exit(1);}echo "Two-plan completion contracts: PASS ($checks checks)\n";