from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def replace(path: str, old: str, new: str) -> None:
    p = ROOT / path
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing replacement target: {path}: {old[:180]!r}")
    p.write_text(text.replace(old, new, 1))

# Part 6: archive inspection and authorization reads must fail closed on uncertainty.
replace(
    'sabri-network/includes/class-sn-file-transfer-part-6.php',
    "for($i=0;$i<$entries;$i++){$stat=$zip->statIndex($i);if(!is_array($stat))continue;$name=(string)($stat['name']??'');",
    "for($i=0;$i<$entries;$i++){$stat=$zip->statIndex($i);if(!is_array($stat)){$zip->close();@unlink($tmp);return new WP_Error('archive_entry_unreadable','An archive entry could not be inspected safely.',['status'=>422]);}$name=(string)($stat['name']??'');"
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-6.php',
    "$changed=$wpdb->query($wpdb->prepare(\"UPDATE \".self::sessions_table().\" SET status='rejected',scan_status='rejected',failure_code=%s,revoked_at=%s,version=version+1,updated_at=%s WHERE id=%d AND revoked_at IS NULL\",sanitize_key($code),$now,$now,(int)$row->id));if($changed!==1){$fresh=self::session((string)$row->public_id);if(!$fresh||(string)$fresh->status!=='rejected')throw new RuntimeException('transfer_rejection_persist_failed');}",
    "$changed=$wpdb->query($wpdb->prepare(\"UPDATE \".self::sessions_table().\" SET status='rejected',scan_status='rejected',failure_code=%s,revoked_at=%s,version=version+1,updated_at=%s WHERE id=%d AND revoked_at IS NULL\",sanitize_key($code),$now,$now,(int)$row->id));if($changed!==1){$fresh=self::session((string)$row->public_id);if($wpdb->last_error!=='')throw new RuntimeException('transfer_rejection_state_unavailable');if(!$fresh||(string)$fresh->status!=='rejected')throw new RuntimeException('transfer_rejection_persist_failed');}"
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-6.php',
    "private static function can_access(object $row,int $user): bool {if((int)$row->sender_id===$user)return true;global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::recipients_table().' WHERE transfer_id=%d AND user_id=%d AND revoked_at IS NULL',(int)$row->id,$user));}",
    "private static function can_access(object $row,int $user): bool|WP_Error {if((int)$row->sender_id===$user)return true;global $wpdb;$allowed=(bool)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::recipients_table().' WHERE transfer_id=%d AND user_id=%d AND revoked_at IS NULL',(int)$row->id,$user));if($wpdb->last_error!==''){SN_DB::audit('file_transfer_access_read_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$user);return new WP_Error('transfer_state_unavailable','Transfer authorization state could not be verified safely.',['status'=>503]);}return $allowed;}"
)

# Part 4: status/grant and post-finalize state must not convert database uncertainty into 404/success.
replace(
    'sabri-network/includes/class-sn-file-transfer-part-4.php',
    "    public static function status(WP_REST_Request $request): WP_REST_Response|WP_Error {$row=self::session((string)$request['public_id']);$user=get_current_user_id();if(!$row||!self::can_access($row,$user))return self::not_found();$policy=self::revalidate($row,$user,(int)$row->sender_id===$user);if(is_wp_error($policy))return $policy;return rest_ensure_response(['transfer'=>self::format($row,$user)]);}\n    public static function grant(WP_REST_Request $request): WP_REST_Response|WP_Error {$row=self::session((string)$request['public_id']);$user=get_current_user_id();if(!$row||!self::can_access($row,$user))return self::not_found();$policy=self::revalidate($row,$user,(int)$row->sender_id===$user);if(is_wp_error($policy))return $policy;if((string)$row->status!=='ready'||(string)$row->scan_status!=='clean'||$row->revoked_at||strtotime((string)$row->expires_at)<=time())return new WP_Error('transfer_not_ready','The private transfer is not available for download.',['status'=>409]);$exp=time()+self::GRANT_TTL;$token=SN_Communication_Crypto::sign(['transfer'=>(string)$row->public_id,'user'=>$user,'version'=>(int)$row->version,'exp'=>$exp],'file-transfer-download');$url=add_query_arg(['sn_file17_transfer_download'=>(string)$row->public_id,'grant'=>$token],home_url('/'));return rest_ensure_response(['url'=>esc_url_raw($url),'expires_at'=>gmdate('c',$exp)]);}",
    "    public static function status(WP_REST_Request $request): WP_REST_Response|WP_Error {global $wpdb;$row=self::session((string)$request['public_id']);$user=get_current_user_id();if($wpdb->last_error!=='')return new WP_Error('transfer_state_unavailable','Transfer state could not be verified safely.',['status'=>503]);if(!$row)return self::not_found();$access=self::can_access($row,$user);if(is_wp_error($access))return $access;if(!$access)return self::not_found();$policy=self::revalidate($row,$user,(int)$row->sender_id===$user);if(is_wp_error($policy))return $policy;return rest_ensure_response(['transfer'=>self::format($row,$user)]);}\n    public static function grant(WP_REST_Request $request): WP_REST_Response|WP_Error {global $wpdb;$row=self::session((string)$request['public_id']);$user=get_current_user_id();if($wpdb->last_error!=='')return new WP_Error('transfer_state_unavailable','Transfer state could not be verified safely.',['status'=>503]);if(!$row)return self::not_found();$access=self::can_access($row,$user);if(is_wp_error($access))return $access;if(!$access)return self::not_found();$policy=self::revalidate($row,$user,(int)$row->sender_id===$user);if(is_wp_error($policy))return $policy;if((string)$row->status!=='ready'||(string)$row->scan_status!=='clean'||$row->revoked_at||strtotime((string)$row->expires_at)<=time())return new WP_Error('transfer_not_ready','The private transfer is not available for download.',['status'=>409]);$exp=time()+self::GRANT_TTL;$token=SN_Communication_Crypto::sign(['transfer'=>(string)$row->public_id,'user'=>$user,'version'=>(int)$row->version,'exp'=>$exp],'file-transfer-download');$url=add_query_arg(['sn_file17_transfer_download'=>(string)$row->public_id,'grant'=>$token],home_url('/'));return rest_ensure_response(['url'=>esc_url_raw($url),'expires_at'=>gmdate('c',$exp)]);}" 
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-4.php',
    "            if($changed===false)return new WP_Error('transfer_quarantine_failed','The transfer could not be placed into fail-closed quarantine.',['status'=>500]);\n            SN_DB::audit('file_transfer_quarantined','file_transfer',(int)$row->id,'failure',['reason'=>'scanner_required'],$sender);return new WP_Error('transfer_quarantined','The file is encrypted and quarantined until the approved malware scanner clears it.',['status'=>503,'transfer'=>self::format(self::session((string)$row->public_id),$sender)]);",
    "            if($changed===false)return new WP_Error('transfer_quarantine_failed','The transfer could not be placed into fail-closed quarantine.',['status'=>500]);\n            $quarantined=self::session((string)$row->public_id);if($wpdb->last_error!==''||!$quarantined){SN_DB::audit('file_transfer_quarantine_reread_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$sender);return new WP_Error('transfer_state_unavailable','The quarantine state could not be re-read safely.',['status'=>503]);}if($changed!==1&&!((string)$quarantined->status==='quarantined'&&(string)$quarantined->scan_status==='scanner_unavailable'))return new WP_Error('transfer_state_changed','The transfer state changed while quarantine was being persisted.',['status'=>409]);\n            SN_DB::audit('file_transfer_quarantined','file_transfer',(int)$row->id,'failure',['reason'=>'scanner_required'],$sender);return new WP_Error('transfer_quarantined','The file is encrypted and quarantined until the approved malware scanner clears it.',['status'=>503,'transfer'=>self::format($quarantined,$sender)]);"
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-4.php',
    "                if($wpdb->last_error!=='')SN_DB::audit('file_transfer_finalize_reconciliation_read_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$sender);\n                if($recipient_ok)return rest_ensure_response(['transfer'=>self::format($fresh,$sender),'duplicate'=>true,'commit_reconciled'=>true]);",
    "                if($wpdb->last_error!==''){SN_DB::audit('file_transfer_finalize_reconciliation_read_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$sender);return new WP_Error('transfer_state_unavailable','Transfer recipient commit state could not be reconciled safely.',['status'=>503]);}\n                if($recipient_ok)return rest_ensure_response(['transfer'=>self::format($fresh,$sender),'duplicate'=>true,'commit_reconciled'=>true]);"
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-4.php',
    "        $recipient_ids=$wpdb->get_col($wpdb->prepare('SELECT user_id FROM '.self::recipients_table().' WHERE transfer_id=%d AND revoked_at IS NULL',(int)$row->id));\n        foreach($recipient_ids as $recipient){SN_DB::add_notification((int)$recipient,'file_transfer_ready','A private file is ready','','file_transfer',(int)$row->id);$wpdb->query($wpdb->prepare(\"UPDATE \".self::recipients_table().\" SET notified_at=COALESCE(notified_at,%s),updated_at=%s WHERE transfer_id=%d AND user_id=%d AND revoked_at IS NULL\",$now,$now,(int)$row->id,(int)$recipient));}\n        do_action('sn_network_event_queued',$event,'file-transfer.ready');SN_DB::audit('file_transfer_ready','file_transfer',(int)$row->id,'success',['bytes'=>(int)$row->total_bytes],$sender);\n        return rest_ensure_response(['transfer'=>self::format(self::session((string)$row->public_id),$sender)]);",
    "        do_action('sn_network_event_queued',$event,'file-transfer.ready');\n        $recipient_ids=$wpdb->get_col($wpdb->prepare('SELECT user_id FROM '.self::recipients_table().' WHERE transfer_id=%d AND revoked_at IS NULL',(int)$row->id));\n        if($wpdb->last_error!==''||!is_array($recipient_ids)){SN_DB::audit('file_transfer_ready_recipient_read_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$sender);return new WP_Error('transfer_state_unavailable','The committed recipient state could not be re-read safely.',['status'=>503]);}\n        foreach($recipient_ids as $recipient){SN_DB::add_notification((int)$recipient,'file_transfer_ready','A private file is ready','','file_transfer',(int)$row->id);$receipt=$wpdb->query($wpdb->prepare(\"UPDATE \".self::recipients_table().\" SET notified_at=COALESCE(notified_at,%s),updated_at=%s WHERE transfer_id=%d AND user_id=%d AND revoked_at IS NULL\",$now,$now,(int)$row->id,(int)$recipient));if($receipt===false)SN_DB::audit('file_transfer_notification_receipt_failed','file_transfer',(int)$row->id,'failure',['recipient_id'=>(int)$recipient],$sender);}\n        $committed=self::session((string)$row->public_id);if($wpdb->last_error!==''||!$committed){SN_DB::audit('file_transfer_ready_reread_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$sender);return new WP_Error('transfer_state_unavailable','The committed transfer state could not be re-read safely.',['status'=>503]);}\n        SN_DB::audit('file_transfer_ready','file_transfer',(int)$row->id,'success',['bytes'=>(int)$row->total_bytes],$sender);\n        return rest_ensure_response(['transfer'=>self::format($committed,$sender)]);"
)

# Part 5: download access database uncertainty is 503, and immutable encrypted chunks are authenticated before success headers.
replace(
    'sabri-network/includes/class-sn-file-transfer-part-5.php',
    "    public static function maybe_download(): void {\n        if(!isset($_GET['sn_file17_transfer_download'],$_GET['grant']))return;$public=sanitize_text_field(wp_unslash($_GET['sn_file17_transfer_download']));$token=sanitize_text_field(wp_unslash($_GET['grant']));$claims=SN_Communication_Crypto::verify($token,'file-transfer-download');\n        if(is_wp_error($claims)||!is_user_logged_in()||(int)($claims['user']??0)!==get_current_user_id()||!hash_equals((string)($claims['transfer']??''),$public)){status_header(403);exit('Private transfer access denied.');}\n        $row=self::session($public);$user=get_current_user_id();if(!$row||(int)($claims['version']??0)!==(int)$row->version||!self::can_access($row,$user)||(string)$row->status!=='ready'||(string)$row->scan_status!=='clean'||$row->revoked_at||strtotime((string)$row->expires_at)<=time()){status_header(404);exit('Private transfer unavailable.');}",
    "    public static function maybe_download(): void {\n        global $wpdb;if(!isset($_GET['sn_file17_transfer_download'],$_GET['grant']))return;$public=sanitize_text_field(wp_unslash($_GET['sn_file17_transfer_download']));$token=sanitize_text_field(wp_unslash($_GET['grant']));$claims=SN_Communication_Crypto::verify($token,'file-transfer-download');\n        if(is_wp_error($claims)||!is_user_logged_in()||(int)($claims['user']??0)!==get_current_user_id()||!hash_equals((string)($claims['transfer']??''),$public)){status_header(403);exit('Private transfer access denied.');}\n        $row=self::session($public);$user=get_current_user_id();if($wpdb->last_error!==''){status_header(503);exit('Private transfer state temporarily unavailable.');}if(!$row){status_header(404);exit('Private transfer unavailable.');}$access=self::can_access($row,$user);if(is_wp_error($access)){status_header(503);exit('Private transfer state temporarily unavailable.');}if((int)($claims['version']??0)!==(int)$row->version||!$access||(string)$row->status!=='ready'||(string)$row->scan_status!=='clean'||$row->revoked_at||strtotime((string)$row->expires_at)<=time()){status_header(404);exit('Private transfer unavailable.');}"
)
replace(
    'sabri-network/includes/class-sn-file-transfer-part-5.php',
    "        $chunks=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::chunks_table().' WHERE transfer_id=%d ORDER BY chunk_index ASC',(int)$row->id));if($wpdb->last_error!==''||!is_array($chunks)||count($chunks)!==(int)$row->total_chunks){SN_DB::audit('file_transfer_download_snapshot_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$user);status_header(503);nocache_headers();return;}\n        status_header($status);",
    "        $chunks=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::chunks_table().' WHERE transfer_id=%d ORDER BY chunk_index ASC',(int)$row->id));if($wpdb->last_error!==''||!is_array($chunks)||count($chunks)!==(int)$row->total_chunks){SN_DB::audit('file_transfer_download_snapshot_failed','file_transfer',(int)$row->id,'failure',['reason'=>(string)$wpdb->last_error],$user);status_header(503);nocache_headers();return;}\n        $preflight_index=0;$preflight_bytes=0;foreach($chunks as $chunk){if((int)$chunk->chunk_index!==$preflight_index++){SN_DB::audit('file_transfer_download_preflight_failed','file_transfer',(int)$row->id,'failure',['reason'=>'chunk_sequence'],$user);status_header(503);nocache_headers();return;}$path=self::existing_storage_path((string)$chunk->storage_key);if(is_wp_error($path)){SN_DB::audit('file_transfer_download_preflight_failed','file_transfer',(int)$row->id,'failure',['reason'=>$path->get_error_code()],$user);status_header(503);nocache_headers();return;}$plain=SN_Communication_Crypto::read_encrypted_file($path,self::chunk_context($row,(int)$chunk->chunk_index));if(is_wp_error($plain)||strlen($plain)!==(int)$chunk->byte_count||!hash_equals((string)$chunk->sha256,hash('sha256',is_wp_error($plain)?'':$plain))){SN_DB::audit('file_transfer_download_preflight_failed','file_transfer',(int)$row->id,'failure',['reason'=>'chunk_integrity'],$user);status_header(503);nocache_headers();return;}$preflight_bytes+=strlen($plain);unset($plain);}if($preflight_bytes!==$total){SN_DB::audit('file_transfer_download_preflight_failed','file_transfer',(int)$row->id,'failure',['reason'=>'byte_count','bytes'=>$preflight_bytes],$user);status_header(503);nocache_headers();return;}\n        status_header($status);"
)

# Part 7: health must expose DB probe uncertainty rather than treating it as ordinary missing schema.
replace(
    'sabri-network/includes/class-sn-file-transfer-part-7.php',
    "    public static function health(): WP_REST_Response {global $wpdb;$missing=[];foreach([self::sessions_table(),self::chunks_table(),self::recipients_table()] as $table)if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))!==$table)$missing[]=$table;$storage=self::ensure_storage();$scanner_ready=apply_filters('sn_network_transfer_scanner_ready',false)===true;return rest_ensure_response(['ok'=>!$missing&&$storage&&$scanner_ready,'schema_version'=>self::SCHEMA_VERSION,'missing_tables'=>$missing,'max_file_bytes'=>self::MAX_FILE_BYTES,'storage_ready'=>$storage,'scanner_connected'=>$scanner_ready,'scanner_readiness_contract'=>'sn_network_transfer_scanner_ready']);}",
    "    public static function health(): WP_REST_Response {global $wpdb;$missing=[];$database_ready=true;foreach([self::sessions_table(),self::chunks_table(),self::recipients_table()] as $table){$found=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table));if($wpdb->last_error!==''){$database_ready=false;SN_DB::audit('file_transfer_health_db_probe_failed','file_transfer',0,'failure',['table_hash'=>hash('sha256',$table)]);continue;}if($found!==$table)$missing[]=$table;}$storage=self::ensure_storage();$scanner_ready=apply_filters('sn_network_transfer_scanner_ready',false)===true;return rest_ensure_response(['ok'=>$database_ready&&!$missing&&$storage&&$scanner_ready,'schema_version'=>self::SCHEMA_VERSION,'database_ready'=>$database_ready,'missing_tables'=>$missing,'max_file_bytes'=>self::MAX_FILE_BYTES,'storage_ready'=>$storage,'scanner_connected'=>$scanner_ready,'scanner_readiness_contract'=>'sn_network_transfer_scanner_ready']);}"
)

# Permanent Round 37 contracts.
test = ROOT / 'sabri-network/tests/ninth-fresh/ninth-fresh-forty-round-contracts.php'
text = test.read_text()
marker = '\nif ($fail) {'
if marker not in text:
    raise SystemExit('test insertion marker missing')
block = r'''

// Round 37 — transfer access, archive inspection, post-finalize truth and download integrity fail closed.
$t4=$read('includes/class-sn-file-transfer-part-4.php');$t5=$read('includes/class-sn-file-transfer-part-5.php');$t6=$read('includes/class-sn-file-transfer-part-6.php');$t7=$read('includes/class-sn-file-transfer-part-7.php');
$check(str_contains($t6,'file_transfer_access_read_failed') && str_contains($t6,'bool|WP_Error') && str_contains($t6,'archive_entry_unreadable'), 'Round 37: authorization DB uncertainty and unreadable archive entries must fail closed.');
$check(substr_count($t4,"$access=self::can_access")>=2 && substr_count($t4,'transfer_state_unavailable')>=4, 'Round 37: transfer status/grant must distinguish authorization/state DB uncertainty from ordinary not-found.');
$check(str_contains($t4,'file_transfer_quarantine_reread_failed') && str_contains($t4,'file_transfer_ready_recipient_read_failed') && str_contains($t4,'file_transfer_ready_reread_failed'), 'Round 37: quarantine and post-finalize committed state must be re-read truthfully.');
$check(str_contains($t5,'Private transfer state temporarily unavailable.') && str_contains($t5,'file_transfer_download_preflight_failed') && strpos($t5,'file_transfer_download_preflight_failed') < strpos($t5,'status_header($status)'), 'Round 37: downloads must authenticate the complete encrypted snapshot before success headers and expose state DB failure as unavailable.');
$check(str_contains($t7,'file_transfer_health_db_probe_failed') && str_contains($t7,"'database_ready'=>$database_ready") && str_contains($t7,"'ok'=>$database_ready&&!$missing&&$storage&&$scanner_ready"), 'Round 37: transfer health must distinguish DB probe uncertainty from an ordinary missing table.');
'''
if 'Round 37 — transfer access, archive inspection' not in text:
    test.write_text(text.replace(marker, block + marker, 1))
