<?php
/** Review round 46 — executable mentor/student office-hours and question workflow. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_S {
    public static function register(): void { add_action('rest_api_init', [self::class, 'routes'], 2120); }
    public static function routes(): void {
        register_rest_route('sabri-network/v2', '/future/mentorships/(?P<id>\d+)/workspace', ['methods'=>'GET','callback'=>[self::class,'workspace'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2', '/future/mentorships/(?P<id>\d+)/office-hours', [['methods'=>'GET','callback'=>[self::class,'office_hours'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'set_office_hours'],'permission_callback'=>[SN_REST::class,'access']]]);
        register_rest_route('sabri-network/v2', '/future/mentorships/(?P<id>\d+)/questions', [['methods'=>'GET','callback'=>[self::class,'questions'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'ask_question'],'permission_callback'=>[SN_REST::class,'access']]]);
        register_rest_route('sabri-network/v2', '/future/mentorships/(?P<id>\d+)/questions/(?P<question_id>\d+)/respond', ['methods'=>'POST','callback'=>[self::class,'respond'],'permission_callback'=>[SN_REST::class,'access']]);
    }

    public static function workspace(WP_REST_Request $r): WP_REST_Response|WP_Error {
        $ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if(!self::participant($ctx,$actor))return self::not_found();$current=self::revalidate($ctx,$actor);if(is_wp_error($current))return $current;
        return rest_ensure_response(['mentorship_id'=>$ctx['id'],'mentor_id'=>$ctx['mentor'],'student_id'=>$ctx['student'],'conversation_id'=>$ctx['conversation'],'office_hours'=>self::records($ctx['id'],'office_hours'),'questions'=>self::records($ctx['id'],'question'),'supervision_required'=>SN_Policy::age_state($ctx['student'])!=='adult','clinical_authority'=>false]);
    }
    public static function office_hours(WP_REST_Request $r): WP_REST_Response|WP_Error {$ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if(!self::participant($ctx,$actor))return self::not_found();$check=self::revalidate($ctx,$actor);if(is_wp_error($check))return $check;return rest_ensure_response(['items'=>self::records($ctx['id'],'office_hours')]);}
    public static function set_office_hours(WP_REST_Request $r): WP_REST_Response|WP_Error {
        $ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if($actor!==$ctx['mentor'])return self::error('forbidden','Only the current mentor may set office hours.',403);$check=self::revalidate($ctx,$actor);if(is_wp_error($check))return $check;
        $start=self::utc_time((string)$r->get_param('starts_at'),(string)$r->get_param('timezone'),90*DAY_IN_SECONDS);if(is_wp_error($start))return $start;$end=self::utc_time((string)$r->get_param('ends_at'),(string)$r->get_param('timezone'),90*DAY_IN_SECONDS);if(is_wp_error($end))return $end;if(strtotime($end)<=strtotime($start)||strtotime($end)-strtotime($start)>8*HOUR_IN_SECONDS)return self::error('sn_mentorship_office_hours_invalid','Office hours must end after start and may not exceed eight hours.',400);
        $id=self::insert($actor,$ctx['id'],['subtype'=>'office_hours','starts_at'=>$start,'ends_at'=>$end,'created_by'=>$actor]);if(is_wp_error($id))return $id;SN_DB::audit('future_mentorship_office_hours','future_record',$id,'success',['mentorship_id'=>$ctx['id'],'starts_at'=>$start,'ends_at'=>$end],$actor);return new WP_REST_Response(['id'=>$id,'starts_at'=>$start,'ends_at'=>$end],201);
    }
    public static function questions(WP_REST_Request $r): WP_REST_Response|WP_Error {$ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if(!self::participant($ctx,$actor))return self::not_found();$check=self::revalidate($ctx,$actor);if(is_wp_error($check))return $check;return rest_ensure_response(['items'=>self::records($ctx['id'],'question')]);}
    public static function ask_question(WP_REST_Request $r): WP_REST_Response|WP_Error {
        $ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if($actor!==$ctx['student'])return self::error('forbidden','Only the current student may submit a mentorship question.',403);$check=self::revalidate($ctx,$actor);if(is_wp_error($check))return $check;$body=mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('question'))),0,4000);if($body==='')return self::error('sn_mentorship_question_empty','Enter a mentorship question.',400);if(self::clinical($body)&&!(bool)apply_filters('sn_network_mentorship_clinical_question_allowed',false,$ctx['mentor'],$ctx['student'],$body))return self::error('sn_mentorship_clinical_guard','Clinical diagnosis or prescription questions are outside this educational mentorship workflow.',403);$refs=self::references($r,$actor,$ctx);if(is_wp_error($refs))return $refs;$id=self::insert($actor,$ctx['id'],['subtype'=>'question','question'=>$body,'references'=>$refs,'status'=>'open','asked_by'=>$actor,'asked_at'=>current_time('mysql',true),'clinical_authority'=>false]);if(is_wp_error($id))return $id;SN_DB::audit('future_mentorship_question','future_record',$id,'success',['mentorship_id'=>$ctx['id'],'reference_count'=>count($refs)],$actor);return new WP_REST_Response(['id'=>$id,'status'=>'open'],201);
    }
    public static function respond(WP_REST_Request $r): WP_REST_Response|WP_Error {
        global $wpdb;$ctx=self::context(absint($r['id']));if(is_wp_error($ctx))return $ctx;$actor=get_current_user_id();if($actor!==$ctx['mentor'])return self::error('forbidden','Only the current mentor may respond.',403);$check=self::revalidate($ctx,$actor);if(is_wp_error($check))return $check;$qid=absint($r['question_id']);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}sn_future_records WHERE id=%d AND feature_id='F17-FUT-14' AND scope_type='mentorship' AND scope_id=%d AND state='active' LIMIT 1",$qid,$ctx['id']));if(!$row)return self::not_found();$data=self::decode($row);if(is_wp_error($data)||($data['subtype']??'')!=='question')return self::not_found();$answer=mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('answer'))),0,8000);if($answer==='')return self::error('sn_mentorship_answer_empty','Enter a mentorship response.',400);if(self::clinical($answer)&&!(bool)apply_filters('sn_network_mentorship_clinical_answer_allowed',false,$ctx['mentor'],$ctx['student'],$answer))return self::error('sn_mentorship_clinical_guard','Clinical diagnosis or prescription is outside this educational mentorship workflow.',403);$refs=self::references($r,$actor,$ctx);if(is_wp_error($refs))return $refs;$data['answer']=$answer;$data['answer_references']=$refs;$data['status']='answered';$data['answered_by']=$actor;$data['answered_at']=current_time('mysql',true);$data['clinical_authority']=false;$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>$qid,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)return self::error('sn_mentorship_question_stale','Question changed concurrently.',409);SN_DB::audit('future_mentorship_response','future_record',$qid,'success',['mentorship_id'=>$ctx['id'],'reference_count'=>count($refs)],$actor);return rest_ensure_response(['id'=>$qid,'status'=>'answered','version'=>(int)$row->version+1]);
    }

    private static function context(int $id): array|WP_Error {global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}sn_future_records WHERE id=%d AND feature_id='F17-FUT-14' AND state='active' LIMIT 1",$id));if(!$row)return self::not_found();$d=self::decode($row);if(is_wp_error($d))return $d;return ['id'=>$id,'row'=>$row,'mentor'=>absint($d['mentor_id']??$row->owner_id),'student'=>absint($d['student_id']??$row->scope_id),'conversation'=>absint($d['conversation_id']??0)];}
    private static function participant(array $ctx,int $actor):bool{return in_array($actor,[$ctx['mentor'],$ctx['student']],true);}
    private static function revalidate(array $ctx,int $actor): bool|WP_Error {if(SN_Policy::is_suspended($ctx['mentor'])||SN_Policy::is_suspended($ctx['student'])||SN_DB::is_blocked($ctx['mentor'],$ctx['student']))return self::error('sn_mentorship_no_longer_eligible','Mentorship eligibility changed.',409);if(!has_filter('sn_network_mentor_eligible')||!(bool)apply_filters('sn_network_mentor_eligible',false,$ctx['mentor'],$ctx['student']))return self::error('sn_mentor_eligibility_unavailable','Current mentor eligibility could not be verified.',503);if($ctx['conversation']>0&&(!SN_DB::is_member($ctx['conversation'],$ctx['mentor'])||!SN_DB::is_member($ctx['conversation'],$ctx['student'])))return self::error('sn_mentorship_conversation_invalid','The linked conversation is no longer shared.',409);if(SN_Policy::age_state($ctx['student'])!=='adult'&&!(bool)apply_filters('sn_network_guardian_communication_approved',false,$ctx['student'],$ctx['mentor'],'mentorship_runtime'))return self::error('sn_guardian_approval_required','Current guardian approval is required.',403);return true;}
    private static function records(int $mentorship,string $subtype):array{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}sn_future_records WHERE feature_id='F17-FUT-14' AND scope_type='mentorship' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 200",$mentorship));$out=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d)||($d['subtype']??'')!==$subtype)continue;$out[]=['id'=>(int)$row->id,'version'=>(int)$row->version,'data'=>$d];}return $out;}
    private static function references(WP_REST_Request $r,int $actor,array $ctx):array|WP_Error{$raw=(array)$r->get_param('reference_ids');$ids=array_slice(array_values(array_unique(array_filter(array_map('sanitize_text_field',$raw)))),0,20);if(!$ids)return [];if(!has_filter('sn_network_mentorship_learning_reference_resolve'))return self::error('sn_mentorship_reference_provider_unavailable','Learning references require an approved canonical owner resolver.',503);$out=[];foreach($ids as $id){$resolved=apply_filters('sn_network_mentorship_learning_reference_resolve',null,$id,$actor,$ctx);if(!is_array($resolved)||empty($resolved['allowed'])||empty($resolved['canonical_id']))return self::error('sn_mentorship_reference_unavailable','A learning reference is unavailable.',404);$out[]=['canonical_id'=>mb_substr(sanitize_text_field((string)$resolved['canonical_id']),0,191),'owner'=>sanitize_key((string)($resolved['owner']??'')),'title'=>mb_substr(sanitize_text_field((string)($resolved['title']??'')),0,300)];}return $out;}
    private static function insert(int $owner,int $mentorship,array $data):int|WP_Error{global $wpdb;$dummy=(object)['feature_id'=>'F17-FUT-14','owner_id'=>$owner,'scope_type'=>'mentorship','scope_id'=>$mentorship];$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-14','owner_id'=>$owner,'scope_type'=>'mentorship','scope_id'=>$mentorship,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>hash('sha256','mentorship-workflow:'.$mentorship.':'.$owner.':'.wp_generate_uuid4()),'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Mentorship workflow data could not be stored safely.',500):(int)$wpdb->insert_id;}
    private static function utc_time(string $value,string $timezone,int $max):string|WP_Error{try{$tz=$timezone!==''?new DateTimeZone($timezone):null;if(!preg_match('/(?:Z|[+-]\d{2}:?\d{2})$/',$value)&&!$tz)return self::error('sn_mentorship_timezone_required','Provide an explicit timezone or UTC offset.',400);$dt=new DateTimeImmutable($value,$tz?:new DateTimeZone('UTC'));$ts=$dt->setTimezone(new DateTimeZone('UTC'))->getTimestamp();if($ts<=time()||$ts>time()+$max)return self::error('sn_mentorship_time_invalid','Choose a valid future time.',400);return gmdate('Y-m-d H:i:s',$ts);}catch(Throwable $e){return self::error('sn_mentorship_time_invalid','Office-hour time is invalid.',400);}}
    private static function clinical(string $text):bool{return(bool)preg_match('/\b(diagnos(?:e|is)|prescrib(?:e|ing)|prescription|dosage|dose|potency|take\s+\d|remedy\s+for|medicine\s+for)\b/i',$text);}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
