<?php
/** Review rounds 24+ — breakout lifecycle, host continuity and network-quality privacy. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_E {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1990);add_action('sn_cleanup_hourly',[self::class,'cleanup_breakouts'],40);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts',['methods'=>'POST','callback'=>[self::class,'create_breakouts'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts/move',['methods'=>'POST','callback'=>[self::class,'move_breakout'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts/close',['methods'=>'POST','callback'=>[self::class,'close_breakouts'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function create_breakouts(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);$rooms=is_array($r->get_param('rooms'))?$r->get_param('rooms'):[];if(!$rooms||count($rooms)>20)return self::error('sn_breakouts_invalid','Provide 1 to 20 breakout rooms.',400);$seen=[];$clean=[];$index=0;
        foreach($rooms as $room){$name=mb_substr(sanitize_text_field((string)($room['name']??'')),0,100);$users=array_values(array_unique(array_filter(array_map('absint',(array)($room['user_ids']??[])))));if($name===''||!$users)return self::error('sn_breakout_room_invalid','Each breakout room needs a name and participants.',400);foreach($users as $u){if(isset($seen[$u]))return self::error('sn_breakout_duplicate_participant','A participant may be assigned to only one breakout room.',409);if(!self::call_member($call,$u))return self::error('sn_breakout_participant_invalid','Every breakout participant must be an active call member.',409);$seen[$u]=true;}$clean[]=['room_id'=>'br-'.(++$index),'name'=>$name,'user_ids'=>$users,'state'=>'active'];}
        if(!(bool)apply_filters('sn_network_sfu_available',false,$actor,$call))return self::error('sn_breakout_provider_unavailable','Breakout rooms require an approved SFU adapter.',503);$provider=apply_filters('sn_network_breakout_create_result',null,$call,$clean,$actor);if($provider===null||$provider===false)return self::error('sn_breakout_provider_unavailable','Breakout rooms require an approved SFU adapter.',503);if(is_wp_error($provider))return $provider;
        $refs=[];foreach((array)($provider['room_refs']??[]) as $k=>$ref){$v=mb_substr(sanitize_text_field((string)$ref),0,191);if($v!=='')$refs[(string)$k]=$v;}$expires=gmdate('Y-m-d H:i:s',time()+max(15,min(480,absint($r->get_param('ttl_minutes'))?:120))*MINUTE_IN_SECONDS);$data=['parent_call_id'=>$call,'rooms'=>$clean,'provider_room_refs'=>$refs,'provider_result_hash'=>hash('sha256',(string)wp_json_encode($provider)),'created_by'=>$actor,'expires_at'=>$expires];$id=self::upsert_record('F17-FUT-19',0,'call',$call,$data,'breakouts:'.$call,$expires);if(is_wp_error($id))return $id;SN_DB::audit('future_breakouts_created','call',$call,'success',['breakout_record_id'=>$id,'room_count'=>count($clean),'expires_at'=>$expires],$actor);return rest_ensure_response(['call_id'=>$call,'breakout_record_id'=>$id,'rooms'=>$clean,'expires_at'=>$expires]);
    }
    public static function move_breakout(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);$target=absint($r->get_param('user_id'));$room=sanitize_key((string)$r->get_param('room_id'));if(!$target||!self::call_member($call,$target))return self::error('sn_breakout_participant_invalid','Participant is no longer in the parent call.',409);$row=self::active_record('F17-FUT-19',$call);if(!$row)return self::error('sn_breakouts_unavailable','No active breakout set exists.',409);$data=self::decode($row);if(is_wp_error($data))return $data;$valid=$room==='parent';if(!$valid)foreach((array)($data['rooms']??[]) as $entry)if((string)($entry['room_id']??'')===$room&&($entry['state']??'')==='active'){$valid=true;break;}if(!$valid)return self::error('sn_breakout_room_invalid','Select an active breakout or parent room.',409);$provider=apply_filters('sn_network_breakout_move_result',null,$call,$target,$room,$actor,$data);if($provider===null||$provider===false)return self::error('sn_breakout_provider_unavailable','The conference provider could not move this participant.',503);if(is_wp_error($provider))return $provider;$data['assignments'][(string)$target]=$room;$saved=self::save_row($row,$data);if(is_wp_error($saved))return $saved;SN_DB::audit('future_breakout_participant_moved','call',$call,'success',['user_id'=>$target,'room_id'=>$room],$actor);return rest_ensure_response(['call_id'=>$call,'user_id'=>$target,'room_id'=>$room]);
    }
    public static function close_breakouts(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);$row=self::active_record('F17-FUT-19',$call);if(!$row)return rest_ensure_response(['call_id'=>$call,'state'=>'closed']);$data=self::decode($row);if(is_wp_error($data))return $data;$provider=apply_filters('sn_network_breakout_close_result',null,$call,$actor,$data);if($provider===null||$provider===false)return self::error('sn_breakout_provider_unavailable','The conference provider could not close the breakouts safely.',503);if(is_wp_error($provider))return $provider;return self::close_record($row,'closed',$actor);
    }
    public static function cleanup_breakouts():void{
        global $wpdb;$now=current_time('mysql',true);$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-19' AND scope_type='call' AND state='active' AND expires_at IS NOT NULL AND expires_at<=%s ORDER BY id ASC LIMIT 100",$now));
        foreach(is_array($rows)?$rows:[] as $row){
            $data=self::decode($row);if(is_wp_error($data))continue;
            $provider=apply_filters('sn_network_breakout_close_result',null,(int)$row->scope_id,0,$data);
            if($provider===null||$provider===false||is_wp_error($provider)){
                SN_DB::audit('future_breakouts_expiry_cleanup_deferred','call',(int)$row->scope_id,'failure',['record_id'=>(int)$row->id,'provider_confirmed'=>false],0);
                continue;
            }
            do_action('sn_network_breakout_expired',(int)$row->scope_id,(int)$row->id,$data);
            self::close_record($row,'expired',0);
        }
    }
    private static function close_record(object $row,string $state,int $actor):WP_REST_Response|WP_Error{global $wpdb;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>$state,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)return self::error('sn_breakout_conflict','Breakout state changed concurrently.',409);SN_DB::audit('future_breakouts_'.$state,'call',(int)$row->scope_id,'success',['record_id'=>(int)$row->id],$actor);return rest_ensure_response(['call_id'=>(int)$row->scope_id,'state'=>$state]);}
    private static function active_record(string $feature,int $call):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id=%s AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$feature,$call));return is_object($row)?$row:null;}
    private static function upsert_record(string $feature,int $owner,string $scope_type,int $scope_id,array $data,string $client,?string $expires):int|WP_Error{global $wpdb;$key=hash('sha256',$client);$row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'sn_future_records WHERE client_key=%s LIMIT 1',$key));$dummy=$row?:((object)['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>$scope_type,'scope_id'=>$scope_id,'version'=>0]);$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);if($row){$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'state'=>'active','expires_at'=>$expires,'updated_at'=>$now,'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?(int)$row->id:self::error('sn_future_conflict','Advanced communication state changed concurrently.',409);}$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>$scope_type,'scope_id'=>$scope_id,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'expires_at'=>$expires,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Advanced communication change could not be stored safely.',500):(int)$wpdb->insert_id;}
    private static function save_row(object $row,array $data):bool|WP_Error{global $wpdb;$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?true:self::error('sn_future_conflict','Advanced communication state changed concurrently.',409);}
    private static function call_member(int $call,int $u):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status IN ('invited','joined') LIMIT 1",$call,$u));}
    private static function call_manager(int $call,int $u):bool{global $wpdb;$c=(int)$wpdb->get_var($wpdb->prepare('SELECT conversation_id FROM '.SN_DB::table('calls').' WHERE id=%d',$call));if(!$c)return false;$host=self::active_record('F17-FUT-20',$call);if($host){$d=self::decode($host);if(!is_wp_error($d)&&(int)($d['host_id']??0)===$u)return true;}return in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||current_user_can('manage_options');}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
