<?php
/** Review round 33+ — delegated team-inbox and handoff governance. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_K {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1999);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/future/team-inbox',[ 'methods'=>'GET','callback'=>[self::class,'list_team_inbox'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/team-inbox/(?P<id>\d+)',[['methods'=>'GET','callback'=>[self::class,'get_team_inbox'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'set_team_inbox'],'permission_callback'=>[SN_REST::class,'access']]],true);
        register_rest_route('sabri-network/v2','/future/team-inbox/(?P<id>\d+)/notes',[['methods'=>'GET','callback'=>[self::class,'list_notes'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'add_note'],'permission_callback'=>[SN_REST::class,'access']]]);
    }
    public static function get_team_inbox(WP_REST_Request $r):WP_REST_Response|WP_Error{$conversation=absint($r['id']);$user=get_current_user_id();if(!self::delegated($conversation,$user,'view'))return self::not_found();$row=self::team_row($conversation);$data=$row?self::decode($row):['enabled'=>false,'assignee_id'=>0,'status'=>'open','version'=>0];if(is_wp_error($data))return $data;return rest_ensure_response(['conversation_id'=>$conversation,'team_inbox'=>$data,'version'=>$row?(int)$row->version:0,'delegation_revalidated'=>true]);}
    public static function set_team_inbox(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $conversation=absint($r['id']);$actor=get_current_user_id();if(!self::conversation_manager($conversation,$actor)||!self::delegated($conversation,$actor,'manage'))return self::error('forbidden','Current delegated team-inbox management authority is required.',403);$assignee=absint($r->get_param('assignee_id'));if($assignee&&!SN_DB::is_member($conversation,$assignee))return self::error('sn_assignment_member_required','The assignee must be a current conversation member.',409);if($assignee&&!self::delegated($conversation,$assignee,'work'))return self::error('sn_assignment_delegation_required','The assignee lacks a current delegated work assertion.',403);$row=self::team_row($conversation);$expected=absint($r->get_param('expected_version'));if($row&&$expected>0&&$expected!==(int)$row->version)return self::error('sn_team_inbox_stale','Team inbox changed; refresh before updating.',409);$data=['enabled'=>rest_sanitize_boolean($r->get_param('enabled')),'assignee_id'=>$assignee,'status'=>self::enum((string)$r->get_param('status'),['open','pending','resolved'],'open'),'updated_by'=>$actor,'updated_at'=>current_time('mysql',true)];$saved=self::save_team($conversation,$row,$data);if(is_wp_error($saved))return $saved;SN_DB::audit('future_team_inbox_updated','conversation',$conversation,'success',['assignee_id'=>$assignee,'status'=>$data['status'],'version'=>$saved['version']],$actor);return rest_ensure_response(['conversation_id'=>$conversation,'team_inbox'=>$data,'version'=>$saved['version']]);}
    public static function list_team_inbox(WP_REST_Request $r):WP_REST_Response{
        global $wpdb;$user=get_current_user_id();$status=sanitize_key((string)$r->get_param('status'));$assigned=rest_sanitize_boolean($r->get_param('assigned_to_me'));$rows=$wpdb->get_results("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-05' AND owner_id=0 AND scope_type='conversation' AND state='active' ORDER BY updated_at DESC,id DESC LIMIT 300");$items=[];foreach(is_array($rows)?$rows:[] as $row){$conversation=(int)$row->scope_id;if(!SN_DB::is_member($conversation,$user)||!self::delegated($conversation,$user,'view'))continue;$d=self::decode($row);if(is_wp_error($d)||empty($d['enabled']))continue;if($status!==''&&($d['status']??'')!==$status)continue;if($assigned&&(int)($d['assignee_id']??0)!==$user)continue;$member=$wpdb->get_row($wpdb->prepare('SELECT last_read_message_id FROM '.SN_DB::table('members').' WHERE conversation_id=%d AND user_id=%d AND left_at IS NULL',$conversation,$user));$last=(int)$wpdb->get_var($wpdb->prepare('SELECT last_message_id FROM '.SN_DB::table('conversations').' WHERE id=%d',$conversation));$items[]=['conversation_id'=>$conversation,'assignee_id'=>(int)($d['assignee_id']??0),'status'=>(string)($d['status']??'open'),'unread'=>$member?$last>(int)$member->last_read_message_id:false,'version'=>(int)$row->version];}return rest_ensure_response(['items'=>$items,'delegation_revalidated'=>true]);
    }
    public static function add_note(WP_REST_Request $r):WP_REST_Response|WP_Error{$conversation=absint($r['id']);$actor=get_current_user_id();if(!self::delegated($conversation,$actor,'work')||!SN_DB::is_member($conversation,$actor))return self::not_found();$text=mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('note'))),0,4000);if($text==='')return self::error('sn_team_note_empty','Enter an internal note.',400);$id=self::create_note($conversation,$actor,$text);if(is_wp_error($id))return $id;SN_DB::audit('future_team_note_added','conversation',$conversation,'success',['note_id'=>$id],$actor);return new WP_REST_Response(['id'=>$id,'conversation_id'=>$conversation],201);}
    public static function list_notes(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$conversation=absint($r['id']);$user=get_current_user_id();if(!self::delegated($conversation,$user,'work')||!SN_DB::is_member($conversation,$user))return self::not_found();$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-05' AND scope_type='conversation' AND scope_id=%d AND owner_id<>0 AND state='active' ORDER BY id DESC LIMIT 100",$conversation));$items=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d)||($d['subtype']??'')!=='internal_note')continue;$items[]=['id'=>(int)$row->id,'author_id'=>(int)$row->owner_id,'note'=>(string)($d['note']??''),'created_at'=>(string)$row->created_at];}return rest_ensure_response(['items'=>$items,'internal_only'=>true]);}
    private static function delegated(int $conversation,int $user,string $purpose):bool{return SN_DB::is_member($conversation,$user)&&has_filter('sn_network_team_inbox_delegation_allowed')&&(bool)apply_filters('sn_network_team_inbox_delegation_allowed',false,$conversation,$user,$purpose);}
    private static function conversation_manager(int $c,int $u):bool{return $c>0&&(in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||current_user_can('manage_options'));}
    private static function team_row(int $c):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-05' AND owner_id=0 AND scope_type='conversation' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$c));return is_object($row)?$row:null;}
    private static function save_team(int $c,?object $row,array $data):array|WP_Error{global $wpdb;$dummy=$row?:((object)['feature_id'=>'F17-FUT-05','owner_id'=>0,'scope_type'=>'conversation','scope_id'=>$c,'version'=>0]);$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);if($row){$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>$now,'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);return $ok===1?['id'=>(int)$row->id,'version'=>(int)$row->version+1]:self::error('sn_team_inbox_conflict','Team inbox changed concurrently.',409);}$key=hash('sha256','team:'.$c);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-05','owner_id'=>0,'scope_type'=>'conversation','scope_id'=>$c,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Team inbox could not be stored safely.',500):['id'=>(int)$wpdb->insert_id,'version'=>1];}
    private static function create_note(int $c,int $actor,string $text):int|WP_Error{global $wpdb;$dummy=(object)['feature_id'=>'F17-FUT-05','owner_id'=>$actor,'scope_type'=>'conversation','scope_id'=>$c];$cipher=self::encode($dummy,['subtype'=>'internal_note','note'=>$text,'created_by'=>$actor]);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-05','owner_id'=>$actor,'scope_type'=>'conversation','scope_id'=>$c,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>hash('sha256','team-note:'.$c.':'.$actor.':'.wp_generate_uuid4()),'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Internal note could not be stored safely.',500):(int)$wpdb->insert_id;}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function enum(string $v,array $a,string $d):string{$v=sanitize_key($v);return in_array($v,$a,true)?$v:$d;}private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
