<?php
/** Review round 29+ — standards-based interoperability with replay, quarantine and kill-switch controls. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_H {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1998);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/future/interop',[['methods'=>'GET','callback'=>[self::class,'list_bridges'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'create_bridge'],'permission_callback'=>[SN_REST::class,'access']]],true);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)',['methods'=>'DELETE','callback'=>[self::class,'revoke_bridge'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)/inbound',['methods'=>'POST','callback'=>[self::class,'inbound'],'permission_callback'=>[self::class,'inbound_permission']]);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)/outbound',['methods'=>'POST','callback'=>[self::class,'outbound'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function inbound_permission(WP_REST_Request $r):bool|WP_Error{return (bool)apply_filters('sn_network_interop_inbound_authorized',false,absint($r['id']),$r)?:self::error('sn_interop_inbound_unauthorized','Interoperability adapter authentication failed.',403);}
    public static function create_bridge(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $actor=get_current_user_id();$conversation=absint($r->get_param('conversation_id'));if(!self::conversation_manager($conversation,$actor))return self::error('forbidden','Conversation management permission is required.',403);$protocol=sanitize_key((string)$r->get_param('protocol'));if(!in_array($protocol,['matrix','activitypub','custom-approved'],true))return self::error('sn_interop_protocol_invalid','Select an approved interoperability protocol.',400);$remote=esc_url_raw((string)$r->get_param('remote_endpoint'),['https']);if($remote===''||wp_parse_url($remote,PHP_URL_SCHEME)!=='https')return self::error('sn_interop_endpoint_invalid','A secure HTTPS endpoint is required.',400);if(!(bool)apply_filters('sn_network_interop_remote_allowed',false,$remote,$protocol,$conversation,$actor)||!(bool)apply_filters('sn_network_interop_provider_ready',false,$protocol,$conversation,$actor))return self::error('sn_interop_not_approved','Interoperability provider or destination is not approved.',503);$direction=sanitize_key((string)$r->get_param('direction'));if(!in_array($direction,['outbound','bidirectional'],true))$direction='outbound';$credential=mb_substr(sanitize_text_field((string)$r->get_param('credential_ref')),0,191);if(preg_match('/(bearer|password|secret|token=)/i',$credential))return self::error('sn_interop_secret_ref_invalid','Store only an opaque credential reference, never a secret.',400);$data=['subtype'=>'bridge','protocol'=>$protocol,'remote_endpoint'=>$remote,'remote_room'=>mb_substr(sanitize_text_field((string)$r->get_param('remote_room')),0,191),'credential_ref'=>$credential,'direction'=>$direction,'identity_authority'=>'file-00/02-local','created_by'=>$actor,'kill_switch'=>false];$record=self::create_record_once(0,$conversation,$data,'interop-bridge:'.$conversation.':'.$protocol.':'.hash('sha256',$remote.'|'.$data['remote_room']));if(is_wp_error($record))return $record;$id=(int)$record['id'];$response_data=$data;if(!$record['created']){$stored=self::receipt_by_id($id);if(!$stored||(int)$stored->scope_id!==$conversation)return self::error('sn_interop_idempotency_conflict','The existing interoperability bridge identity does not match this conversation.',409);$committed=self::decode($stored);if(is_wp_error($committed))return $committed;if(!self::same_bridge_configuration($committed,$data))return self::error('sn_interop_idempotency_conflict','The same interoperability bridge identity was reused with different configuration.',409);$response_data=$committed;}SN_DB::audit('future_interop_bridge_created','conversation',$conversation,'success',['bridge_id'=>$id,'protocol'=>$protocol,'direction'=>(string)($response_data['direction']??$direction),'idempotent'=>!$record['created']],$actor);return new WP_REST_Response(['id'=>$id,'bridge'=>self::public_bridge($response_data),'canonical_truth'=>'file-17','idempotent'=>!$record['created']],$record['created']?201:200);
    }
    public static function list_bridges(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$actor=get_current_user_id();$conversation=absint($r->get_param('conversation_id'));if(!self::conversation_manager($conversation,$actor))return self::error('forbidden','Conversation management permission is required.',403);$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-24' AND scope_type='conversation' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 100",$conversation));$items=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d)||($d['subtype']??'')!=='bridge')continue;$items[]=['id'=>(int)$row->id,'bridge'=>self::public_bridge($d),'available'=>empty($d['kill_switch'])];}return rest_ensure_response(['conversation_id'=>$conversation,'items'=>$items]);}
    public static function revoke_bridge(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$actor=get_current_user_id();$id=absint($r['id']);$lock=self::bridge_lock($id);if(is_wp_error($lock))return $lock;try{$row=self::bridge($id);if(!$row)return self::not_found();if(!self::conversation_manager((int)$row->scope_id,$actor))return self::error('forbidden','Conversation management permission is required.',403);$d=self::decode($row);if(is_wp_error($d))return $d;if(!empty($d['kill_switch']))return self::error('sn_interop_bridge_busy','Bridge shutdown is already in progress.',409);$d['kill_switch']=true;$d['shutdown_state']='pending_provider';$marked=self::save_bridge($row,$d);if(is_wp_error($marked))return $marked;$row=self::bridge($id);if(!$row)return self::error('sn_interop_conflict','Bridge state disappeared during shutdown.',409);$provider=apply_filters('sn_network_interop_kill_switch_result',null,$id,$d,(int)$row->scope_id,$actor);if($provider===null||$provider===false||is_wp_error($provider)){$d['kill_switch']=false;$d['shutdown_state']=null;self::save_bridge($row,$d);return is_wp_error($provider)?$provider:self::error('sn_interop_kill_switch_unavailable','Provider could not confirm bridge shutdown.',503);}$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>'revoked','updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>$id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1){SN_DB::audit('future_interop_shutdown_reconcile_required','conversation',(int)$row->scope_id,'failure',['bridge_id'=>$id],$actor);return self::error('sn_interop_reconcile_required','Provider shutdown succeeded; local bridge remains fail-closed and requires reconciliation.',503);}SN_DB::audit('future_interop_bridge_revoked','conversation',(int)$row->scope_id,'success',['bridge_id'=>$id],$actor);return rest_ensure_response(['id'=>$id,'state'=>'revoked']);}finally{self::bridge_unlock($lock);}
    }
    public static function inbound(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$bridge=self::bridge(absint($r['id']));if(!$bridge)return self::not_found();$d=self::decode($bridge);if(is_wp_error($d)||!empty($d['kill_switch'])||($d['direction']??'outbound')!=='bidirectional')return self::error('sn_interop_inbound_disabled','Inbound interoperability is disabled for this bridge.',403);if(!SN_Policy::consume_rate_limit('interop_inbound',(string)$bridge->id,120,MINUTE_IN_SECONDS))return self::error('sn_interop_rate_limited','Interoperability rate limit exceeded.',429);$event_id=mb_substr(sanitize_text_field((string)$r->get_param('event_id')),0,191);if($event_id==='')return self::error('sn_interop_event_id_required','A stable external event identifier is required.',400);$payload=$r->get_param('payload');if(!is_array($payload))return self::error('sn_interop_payload_invalid','Inbound payload must be a structured object.',400);
        $key='interop-inbound:'.$bridge->id.':'.$event_id;$lock=self::operation_lock($key);if(is_wp_error($lock))return $lock;try{$receipt=self::receipt_by_key($key);if($receipt)return rest_ensure_response(['accepted'=>self::receipt_decision($receipt)==='allow','quarantined'=>self::receipt_decision($receipt)==='quarantine','duplicate'=>true,'receipt_id'=>(int)$receipt->id]);$bridge=self::bridge((int)$bridge->id);if(!$bridge)return self::not_found();$d=self::decode($bridge);if(is_wp_error($d)||!empty($d['kill_switch']))return self::error('sn_interop_inbound_disabled','Inbound interoperability is disabled for this bridge.',403);$decision=apply_filters('sn_network_interop_inbound_filter',null,$payload,$d,(int)$bridge->scope_id,(int)$bridge->id);if(!is_array($decision)||!in_array(($decision['decision']??''),['allow','quarantine','deny'],true))return self::error('sn_interop_filter_unavailable','Inbound interoperability filter is unavailable.',503);$state=(string)$decision['decision'];$meta=['subtype'=>'receipt','direction'=>'inbound','bridge_id'=>(int)$bridge->id,'event_id_hash'=>hash('sha256',$event_id),'payload_hash'=>hash('sha256',(string)wp_json_encode($payload)),'decision'=>$state,'reason'=>mb_substr(sanitize_text_field((string)($decision['reason']??'')),0,191)];$created=self::create_record_once(0,(int)$bridge->scope_id,$meta,$key);if(is_wp_error($created))return $created;$id=(int)$created['id'];if(!$created['created'])return rest_ensure_response(['accepted'=>self::receipt_decision_by_id($id)==='allow','quarantined'=>self::receipt_decision_by_id($id)==='quarantine','duplicate'=>true,'receipt_id'=>$id]);if($state==='allow'){do_action('sn_network_interop_inbound_accepted',['bridge_id'=>(int)$bridge->id,'conversation_id'=>(int)$bridge->scope_id,'external_event_id'=>$event_id,'sanitized_payload'=>is_array($decision['payload']??null)?$decision['payload']:[],'receipt_id'=>$id]);}SN_DB::audit('future_interop_inbound','conversation',(int)$bridge->scope_id,$state==='allow'?'success':'failure',['bridge_id'=>(int)$bridge->id,'receipt_id'=>$id,'decision'=>$state],0);return new WP_REST_Response(['accepted'=>$state==='allow','quarantined'=>$state==='quarantine','receipt_id'=>$id],$state==='allow'?202:($state==='quarantine'?202:403));}finally{self::operation_unlock($lock);}
    }
    public static function outbound(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$actor=get_current_user_id();$bridge=self::bridge(absint($r['id']));if(!$bridge)return self::not_found();if(!self::conversation_manager((int)$bridge->scope_id,$actor))return self::error('forbidden','Conversation management permission is required.',403);$d=self::decode($bridge);if(is_wp_error($d)||!empty($d['kill_switch']))return self::error('sn_interop_outbound_disabled','Outbound interoperability is disabled for this bridge.',403);if(!SN_Policy::consume_rate_limit('interop_outbound',(string)$bridge->id,120,MINUTE_IN_SECONDS))return self::error('sn_interop_rate_limited','Interoperability rate limit exceeded.',429);$message=absint($r->get_param('message_id'));$idem=trim((string)$r->get_header('Idempotency-Key'));if($idem==='')$idem='message:'.$message;$key='interop-outbound:'.$bridge->id.':'.$actor.':'.hash('sha256',$idem);$lock=self::operation_lock($key);if(is_wp_error($lock))return $lock;
        try{$existing=self::receipt_by_key($key);if($existing){$ed=self::decode($existing);if(!is_wp_error($ed)&&($ed['delivery_state']??'')==='sent')return rest_ensure_response(['queued'=>true,'duplicate'=>true,'bridge_id'=>(int)$bridge->id,'message_id'=>$message,'receipt_id'=>(int)$existing->id]);}
            $bridge=self::bridge((int)$bridge->id);if(!$bridge)return self::not_found();$d=self::decode($bridge);if(is_wp_error($d)||!empty($d['kill_switch']))return self::error('sn_interop_outbound_disabled','Outbound interoperability is disabled for this bridge.',403);if(!self::conversation_manager((int)$bridge->scope_id,$actor))return self::error('forbidden','Conversation management permission changed before send.',403);$m=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.SN_DB::table('messages').' WHERE id=%d',$message));if(!$m||(int)$m->conversation_id!==(int)$bridge->scope_id||!empty($m->deleted_at)||SN_Message_Operations::is_hidden($actor,$message))return self::not_found();$decision=apply_filters('sn_network_interop_outbound_filter',null,$message,$m,$d,$actor);if(!is_array($decision)||empty($decision['allow']))return self::error('sn_interop_outbound_denied','Outbound bridge policy did not approve this message.',403);
            $meta=['subtype'=>'receipt','direction'=>'outbound','bridge_id'=>(int)$bridge->id,'message_id'=>$message,'requester_id'=>$actor,'delivery_state'=>'sending','decision_hash'=>hash('sha256',(string)wp_json_encode($decision))];if($existing){$receipt=$existing;$saved=self::update_receipt($receipt,$meta);if(is_wp_error($saved))return $saved;$receipt=self::receipt_by_key($key);}else{$created=self::create_record_once($actor,(int)$bridge->scope_id,$meta,$key);if(is_wp_error($created))return $created;$receipt=self::receipt_by_id((int)$created['id']);}
            // Final visibility/kill-switch check immediately before external side effect.
            $bridge=self::bridge((int)$bridge->id);$current=$bridge?self::decode($bridge):self::error('not_found','Bridge unavailable.',404);$m=$wpdb->get_row($wpdb->prepare('SELECT id,conversation_id,deleted_at FROM '.SN_DB::table('messages').' WHERE id=%d',$message));if(!$bridge||is_wp_error($current)||!empty($current['kill_switch'])||!$m||!empty($m->deleted_at)||SN_Message_Operations::is_hidden($actor,$message)){if($receipt)self::set_receipt_state($receipt,'cancelled');return self::not_found();}
            $provider=apply_filters('sn_network_interop_outbound_result',null,$current,$decision,$message,$actor,['idempotency_key'=>$key,'receipt_id'=>$receipt?(int)$receipt->id:0]);if($provider===null||$provider===false||is_wp_error($provider)){if($receipt)self::set_receipt_state($receipt,'failed');return is_wp_error($provider)?$provider:self::error('sn_interop_provider_unavailable','Interoperability provider is unavailable.',503);}if($receipt)self::set_receipt_state($receipt,'sent');SN_DB::audit('future_interop_outbound','message',$message,'success',['bridge_id'=>(int)$bridge->id,'receipt_id'=>$receipt?(int)$receipt->id:0,'payload_hash'=>hash('sha256',(string)wp_json_encode($decision))],$actor);return rest_ensure_response(['queued'=>true,'bridge_id'=>(int)$bridge->id,'message_id'=>$message,'receipt_id'=>$receipt?(int)$receipt->id:0]);}finally{self::operation_unlock($lock);}
    }
    private static function bridge(int $id):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-24' AND scope_type='conversation' AND state='active' LIMIT 1",$id));return is_object($row)?$row:null;}
    private static function save_bridge(object $row,array $data):array|WP_Error{global $wpdb;$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);return $ok===1?['version'=>(int)$row->version+1]:self::error('sn_interop_conflict','Bridge changed concurrently.',409);}
    private static function create_record_once(int $owner,int $conversation,array $data,string $client):array|WP_Error{global $wpdb;$key=hash('sha256',$client);$existing=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.$wpdb->prefix.'sn_future_records WHERE client_key=%s',$key));if($existing)return ['id'=>$existing,'created'=>false];$dummy=(object)['feature_id'=>'F17-FUT-24','owner_id'=>$owner,'scope_type'=>'conversation','scope_id'=>$conversation];$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-24','owner_id'=>$owner,'scope_type'=>'conversation','scope_id'=>$conversation,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);if($ok===1)return ['id'=>(int)$wpdb->insert_id,'created'=>true];$existing=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.$wpdb->prefix.'sn_future_records WHERE client_key=%s',$key));return $existing?['id'=>$existing,'created'=>false]:self::error('database_error','Interoperability state could not be stored safely.',500);}
    private static function receipt_by_key(string $client):?object{global $wpdb;$key=hash('sha256',$client);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-24' AND client_key=%s LIMIT 1",$key));return is_object($row)?$row:null;}
    private static function receipt_by_id(int $id):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-24' LIMIT 1",$id));return is_object($row)?$row:null;}
    private static function receipt_decision(object $row):string{$d=self::decode($row);return is_wp_error($d)?'deny':(string)($d['decision']??'deny');}private static function receipt_decision_by_id(int $id):string{$r=self::receipt_by_id($id);return $r?self::receipt_decision($r):'deny';}
    private static function update_receipt(object $row,array $data):array|WP_Error{global $wpdb;$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?['version'=>(int)$row->version+1]:self::error('sn_interop_receipt_conflict','Interoperability receipt changed concurrently.',409);}
    private static function set_receipt_state(object $row,string $state):void{$d=self::decode($row);if(is_wp_error($d))return;$d['delivery_state']=$state;$d[$state.'_at']=current_time('mysql',true);self::update_receipt($row,$d);}
    private static function public_bridge(array $d):array{return ['protocol'=>(string)($d['protocol']??''),'remote_endpoint'=>(string)($d['remote_endpoint']??''),'remote_room'=>(string)($d['remote_room']??''),'direction'=>(string)($d['direction']??'outbound'),'identity_authority'=>'file-00/02-local'];}
    private static function same_bridge_configuration(array $stored,array $requested):bool{foreach(['subtype','protocol','remote_endpoint','remote_room','credential_ref','direction','identity_authority'] as $key){if((string)($stored[$key]??'')!==(string)($requested[$key]??''))return false;}return true;}
    private static function conversation_manager(int $c,int $u):bool{return $c>0&&(in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||user_can($u,'manage_options'));}
    private static function operation_lock(string $key):string|WP_Error{global $wpdb;$name='sn:f17:interop-op:'.substr(hash('sha256',$key),0,40);$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$name,5));return $got===1?$name:self::error('sn_interop_busy','An identical interoperability operation is already in progress.',409);}private static function operation_unlock(string|WP_Error $lock):void{if(is_wp_error($lock))return;global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}
    private static function bridge_lock(int $id):string|WP_Error{return self::operation_lock('bridge-shutdown:'.$id);}private static function bridge_unlock(string|WP_Error $lock):void{self::operation_unlock($lock);}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
