<?php
/** Review round 25+ — serialized co-host and provider-consistent host-transfer lifecycle. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_F {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1995);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/cohosts',['methods'=>'POST','callback'=>[self::class,'cohost'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-transfer',['methods'=>'POST','callback'=>[self::class,'propose_transfer'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-transfer/confirm',['methods'=>'POST','callback'=>[self::class,'confirm_transfer'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-takeover',['methods'=>'POST','callback'=>[self::class,'disconnect_takeover'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function cohost(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();$target=absint($r->get_param('user_id'));$action=sanitize_key((string)$r->get_param('action'));if(!in_array($action,['grant','revoke'],true))return self::error('sn_call_cohost_action_invalid','Use grant or revoke.',400);if(!self::call_manager($call,$actor))return self::error('forbidden','Current host permission is required.',403);if(!$target||!self::call_member($call,$target))return self::error('sn_call_cohost_invalid','Select an active call member.',409);
        $lock=self::host_lock($call);if(is_wp_error($lock))return $lock;try{if(!self::call_manager($call,$actor)||!self::call_member($call,$target))return self::error('sn_call_cohost_stale','Host authority or target membership changed.',409);$row=self::host_row($call);$data=$row?self::decode($row):['host_id'=>$actor,'cohosts'=>[],'epoch'=>1,'transition'=>null];if(is_wp_error($data))return $data;if(!empty($data['transition']))return self::error('sn_call_host_busy','A host lifecycle transition is already in progress.',409);$cohosts=array_values(array_unique(array_filter(array_map('absint',(array)($data['cohosts']??[])))));if($action==='grant'&&!in_array($target,$cohosts,true))$cohosts[]=$target;if($action==='revoke')$cohosts=array_values(array_diff($cohosts,[$target]));$data['cohosts']=$cohosts;$data['updated_by']=$actor;$saved=self::save_host($call,$row,$data);if(is_wp_error($saved))return $saved;SN_DB::audit('future_call_cohost_'.$action,'call',$call,'success',['user_id'=>$target,'epoch'=>(int)($data['epoch']??1)],$actor);return rest_ensure_response(['call_id'=>$call,'host_id'=>(int)($data['host_id']??0),'cohosts'=>$cohosts,'version'=>$saved['version']]);}finally{self::host_unlock($lock);}
    }
    public static function propose_transfer(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();$target=absint($r->get_param('user_id'));if(!self::call_manager($call,$actor))return self::error('forbidden','Current host permission is required.',403);if(!$target||$target===$actor||!self::call_member($call,$target))return self::error('sn_call_host_invalid','Select another active call member.',409);$lock=self::host_lock($call);if(is_wp_error($lock))return $lock;
        try{
            if(!self::call_manager($call,$actor)||!self::call_member($call,$target))return self::error('sn_call_host_stale','Host authority or target membership changed.',409);$row=self::host_row($call);$data=$row?self::decode($row):['host_id'=>$actor,'cohosts'=>[],'epoch'=>1,'transition'=>null];if(is_wp_error($data))return $data;if(!empty($data['transition']))return self::error('sn_call_host_busy','A host lifecycle transition is already in progress.',409);$expected=absint($r->get_param('expected_version'));if($row&&$expected>0&&$expected!==(int)$row->version)return self::error('sn_call_host_stale','Host state changed; refresh before transferring.',409);$existing=(array)($data['pending_transfer']??[]);if($existing&&time()<=(int)($existing['expires_at']??0))return self::error('sn_call_host_busy','Another host transfer is already pending.',409);
            $nonce=wp_generate_uuid4();$data['pending_transfer']=['from'=>(int)($data['host_id']??$actor),'to'=>$target,'nonce'=>$nonce,'expires_at'=>time()+300,'provider_prepared'=>false];$data['transition']='transfer_preparing';$saved=self::save_host($call,$row,$data);if(is_wp_error($saved))return $saved;$row=self::host_row($call);if(!$row)return self::error('sn_call_host_conflict','Host state could not be reloaded.',409);
            $provider=apply_filters('sn_network_call_host_transfer_prepare',null,$call,$actor,$target,$data+['idempotency_key'=>'file17-host-prepare:'.$call.':'.$nonce]);if($provider===null||$provider===false||is_wp_error($provider)){self::reset_prepare($call,$row);return is_wp_error($provider)?$provider:self::error('sn_call_host_transfer_unavailable','Host transfer requires an approved conference adapter.',503);}
            $data=self::decode($row);if(is_wp_error($data))return $data;$data['pending_transfer']['provider_prepared']=true;$data['pending_transfer']['provider_prepare_hash']=hash('sha256',(string)wp_json_encode($provider));$data['transition']=null;$final=self::save_host($call,$row,$data);if(is_wp_error($final)){$abort=apply_filters('sn_network_call_host_transfer_abort',null,$call,$actor,$target,['nonce'=>$nonce,'reason'=>'local_finalize_failed']);if($abort!==null&&$abort!==false&&!is_wp_error($abort))self::force_clear_transition($call);else self::force_reconcile($call,['kind'=>'prepare','from'=>$actor,'to'=>$target,'nonce'=>$nonce]);return self::error('sn_call_host_reconcile_required','Provider prepared the transfer but local finalization requires reconciliation.',503);}SN_DB::audit('future_call_host_transfer_proposed','call',$call,'success',['to'=>$target,'version'=>$final['version']],$actor);return rest_ensure_response(['call_id'=>$call,'pending'=>true,'target_id'=>$target,'nonce'=>$nonce,'expires_in'=>300,'version'=>$final['version']]);
        }finally{self::host_unlock($lock);}
    }
    public static function confirm_transfer(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();$lock=self::host_lock($call);if(is_wp_error($lock))return $lock;
        try{
            $row=self::host_row($call);if(!$row)return self::error('sn_call_host_transfer_missing','No transfer is pending.',409);$data=self::decode($row);if(is_wp_error($data))return $data;if(!empty($data['transition']))return self::error('sn_call_host_busy','A host lifecycle transition is already in progress.',409);$pending=is_array($data['pending_transfer']??null)?$data['pending_transfer']:[];$from=absint($pending['from']??0);if((int)($pending['to']??0)!==$actor||empty($pending['provider_prepared'])||!hash_equals((string)($pending['nonce']??''),(string)$r->get_param('nonce'))||time()>(int)($pending['expires_at']??0)||!self::call_member($call,$actor)||(int)($data['host_id']??0)!==$from)return self::error('sn_call_host_transfer_invalid','Host transfer is invalid, stale or expired.',409);
            $before=$data;$data['transition']='transfer_committing';$marked=self::save_host($call,$row,$data);if(is_wp_error($marked))return $marked;$row=self::host_row($call);if(!$row)return self::error('sn_call_host_conflict','Host state could not be reloaded.',409);
            $provider=apply_filters('sn_network_call_host_transfer_commit',null,$call,$from,$actor,$pending+['idempotency_key'=>'file17-host-commit:'.$call.':'.(string)$pending['nonce']]);if($provider===null||$provider===false||is_wp_error($provider)){self::force_restore_host_data($call,$before);return is_wp_error($provider)?$provider:self::error('sn_call_host_transfer_unavailable','Conference provider could not commit the host transfer.',503);}
            $data=self::decode($row);if(is_wp_error($data))return $data;$data['host_id']=$actor;$data['epoch']=max(1,(int)($data['epoch']??1))+1;$data['pending_transfer']=null;$data['transition']=null;$data['cohosts']=array_values(array_diff(array_map('absint',(array)($data['cohosts']??[])),[$actor]));$saved=self::save_host($call,$row,$data);if(is_wp_error($saved)){$rollback=apply_filters('sn_network_call_host_transfer_rollback',null,$call,$actor,$from,['nonce'=>(string)$pending['nonce'],'reason'=>'local_finalize_failed']);if($rollback!==null&&$rollback!==false&&!is_wp_error($rollback))self::force_restore_host_data($call,$before);else self::force_reconcile($call,['kind'=>'commit','provider_host'=>$actor,'expected_host'=>$from,'nonce'=>(string)$pending['nonce']]);return self::error('sn_call_host_reconcile_required','Provider host changed but local host state requires reconciliation.',503);}SN_DB::audit('future_call_host_transferred','call',$call,'success',['from'=>$from,'to'=>$actor,'epoch'=>$data['epoch']],$actor);return rest_ensure_response(['call_id'=>$call,'host_id'=>$actor,'epoch'=>$data['epoch'],'version'=>$saved['version']]);
        }finally{self::host_unlock($lock);}
    }
    public static function disconnect_takeover(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();$lock=self::host_lock($call);if(is_wp_error($lock))return $lock;
        try{$row=self::host_row($call);if(!$row)return self::error('sn_call_host_state_missing','No governed host state exists.',409);$data=self::decode($row);if(is_wp_error($data))return $data;if(!empty($data['transition']))return self::error('sn_call_host_busy','A host lifecycle transition is already in progress.',409);$cohosts=array_map('absint',(array)($data['cohosts']??[]));if(!in_array($actor,$cohosts,true)||!self::call_member($call,$actor))return self::error('forbidden','Only an active co-host may request governed takeover.',403);$old=absint($data['host_id']??0);if(!(bool)apply_filters('sn_network_call_host_disconnected',false,$call,$old,$actor))return self::error('sn_call_host_still_active','Authoritative provider state does not permit takeover.',409);$before=$data;$data['transition']='takeover_committing';$marked=self::save_host($call,$row,$data);if(is_wp_error($marked))return $marked;$row=self::host_row($call);$provider=apply_filters('sn_network_call_host_takeover_result',null,$call,$old,$actor,$data+['idempotency_key'=>'file17-host-takeover:'.$call.':'.(int)($data['epoch']??1)]);if($provider===null||$provider===false||is_wp_error($provider)){self::force_restore_host_data($call,$before);return is_wp_error($provider)?$provider:self::error('sn_call_host_takeover_unavailable','Conference provider could not commit the takeover.',503);}$data=$row?self::decode($row):self::error('sn_call_host_conflict','Host state disappeared.',409);if(is_wp_error($data))return $data;$data['host_id']=$actor;$data['epoch']=max(1,(int)($data['epoch']??1))+1;$data['pending_transfer']=null;$data['transition']=null;$data['cohosts']=array_values(array_diff($cohosts,[$actor]));$saved=self::save_host($call,$row,$data);if(is_wp_error($saved)){$rollback=apply_filters('sn_network_call_host_takeover_rollback',null,$call,$actor,$old,['reason'=>'local_finalize_failed']);if($rollback!==null&&$rollback!==false&&!is_wp_error($rollback))self::force_restore_host_data($call,$before);else self::force_reconcile($call,['kind'=>'takeover','provider_host'=>$actor,'expected_host'=>$old]);return self::error('sn_call_host_reconcile_required','Provider takeover succeeded but local host state requires reconciliation.',503);}SN_DB::audit('future_call_host_takeover','call',$call,'success',['from'=>$old,'to'=>$actor,'epoch'=>$data['epoch']],$actor);return rest_ensure_response(['call_id'=>$call,'host_id'=>$actor,'epoch'=>$data['epoch'],'version'=>$saved['version']]);}finally{self::host_unlock($lock);}
    }
    private static function host_row(int $call):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-20' AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$call));return is_object($row)?$row:null;}
    private static function save_host(int $call,?object $row,array $data):array|WP_Error{global $wpdb;$dummy=$row?:((object)['feature_id'=>'F17-FUT-20','owner_id'=>0,'scope_type'=>'call','scope_id'=>$call,'version'=>0]);$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);if($row){$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>$now,'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);return $ok===1?['id'=>(int)$row->id,'version'=>(int)$row->version+1]:self::error('sn_call_host_conflict','Host state changed concurrently.',409);}$key=hash('sha256','host:'.$call);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-20','owner_id'=>0,'scope_type'=>'call','scope_id'=>$call,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===1?['id'=>(int)$wpdb->insert_id,'version'=>1]:self::error('database_error','Host state could not be stored safely.',500);}
    private static function reset_prepare(int $call,object $row):void{$data=self::decode($row);if(is_wp_error($data))return;$data['pending_transfer']=null;$data['transition']=null;self::save_host($call,$row,$data);}
    private static function force_clear_transition(int $call):void{$row=self::host_row($call);if(!$row)return;$data=self::decode($row);if(is_wp_error($data))return;$data['pending_transfer']=null;$data['transition']=null;self::save_host($call,$row,$data);}
    private static function force_restore_host_data(int $call,array $before):void{$row=self::host_row($call);if(!$row)return;$before['transition']=null;self::save_host($call,$row,$before);}
    private static function force_reconcile(int $call,array $detail):void{$row=self::host_row($call);if(!$row)return;$data=self::decode($row);if(is_wp_error($data))return;$data['transition']='reconcile_required';$data['reconcile']=$detail;$saved=self::save_host($call,$row,$data);SN_DB::audit('future_call_host_reconcile_required','call',$call,'failure',['detail_hash'=>hash('sha256',(string)wp_json_encode($detail)),'state_saved'=>!is_wp_error($saved)],0);}
    private static function call_member(int $call,int $u):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status IN ('invited','joined') LIMIT 1",$call,$u));}
    private static function call_manager(int $call,int $u):bool{global $wpdb;$c=(int)$wpdb->get_var($wpdb->prepare('SELECT conversation_id FROM '.SN_DB::table('calls').' WHERE id=%d',$call));if(!$c)return false;$row=self::host_row($call);if($row){$d=self::decode($row);if(!is_wp_error($d)){if(($d['transition']??null)==='reconcile_required')return user_can($u,'manage_options');if(!empty($d['transition']))return false;if((int)($d['host_id']??0)===$u)return true;}}return in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||user_can($u,'manage_options');}
    private static function host_lock(int $call):string|WP_Error{global $wpdb;$name='sn:f17:host:'.$call;$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$name,5));return $got===1?$name:self::error('sn_call_host_busy','Host lifecycle is busy; retry.',409);}
    private static function host_unlock(string|WP_Error $lock):void{if(is_wp_error($lock))return;global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
