<?php
/** Review rounds 22–23 — conference lobby privacy and deterministic speaker-queue hardening. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_D {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1980);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/lobby',['methods'=>'GET','callback'=>[self::class,'call_lobby'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/hand-raise',['methods'=>'POST','callback'=>[self::class,'hand_raise'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/speaker-queue',[['methods'=>'GET','callback'=>[self::class,'speaker_queue'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'manage_speaker_queue'],'permission_callback'=>[SN_REST::class,'access']]]);
    }
    public static function call_lobby(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$call=absint($r['id']);$user=get_current_user_id();if(!self::call_member($call,$user))return self::not_found();$manager=self::call_manager($call,$user);$sql="SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-17' AND scope_type='call' AND scope_id=%d AND state='active'";$args=[$call];if(!$manager){$sql.=' AND owner_id=%d';$args[]=$user;}$sql.=' ORDER BY id ASC LIMIT 200';$rows=$wpdb->get_results($wpdb->prepare($sql,...$args));$items=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d))continue;$items[]=['user_id'=>(int)($d['user_id']??$row->owner_id),'state'=>(string)($d['state']??'waiting'),'moderated_by'=>$manager?(int)($d['moderated_by']??0):0];}return rest_ensure_response(['call_id'=>$call,'lobby'=>$items,'view'=>$manager?'moderator':'self','privacy_minimized'=>!$manager]);
    }
    public static function hand_raise(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$call=absint($r['id']);$user=get_current_user_id();if(!self::call_member($call,$user))return self::not_found();$lock=self::queue_lock($call);if(is_wp_error($lock))return $lock;try { if ($wpdb->query('START TRANSACTION') === false) throw new RuntimeException('transaction_start_failed');
            if(!self::call_member_locked($call,$user))throw new RuntimeException('membership_changed');$raised=rest_sanitize_boolean($r->get_param('raised'));$rows=self::feature_rows('F17-FUT-18',$call,true);$position=0;if($raised){foreach($rows as $row){$d=self::decode($row);if(!is_wp_error($d)&&!empty($d['raised']))$position=max($position,(int)($d['position']??0));}$position++;}
            $data=['user_id'=>$user,'raised'=>$raised,'position'=>$raised?$position:0,'speaking'=>false,'raised_at'=>$raised?current_time('mysql',true):null];$id=self::upsert('F17-FUT-18',$user,$call,$data,'hand:'.$call.':'.$user);if(is_wp_error($id))throw new RuntimeException($id->get_error_code());if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');SN_DB::audit('future_hand_raise','call',$call,'success',['raised'=>$raised,'position'=>$data['position']],$user);return rest_ensure_response(['call_id'=>$call,'raised'=>$raised,'position'=>$data['position']]);
        }catch(Throwable $e){$wpdb->query('ROLLBACK');return $e->getMessage()==='membership_changed'?self::not_found():new WP_Error('sn_speaker_queue_conflict','Speaker queue changed concurrently; retry.',['status'=>409]);}finally{self::queue_unlock($lock);}
    }
    public static function speaker_queue(WP_REST_Request $r):WP_REST_Response|WP_Error{$call=absint($r['id']);$user=get_current_user_id();if(!self::call_member($call,$user))return self::not_found();return rest_ensure_response(['call_id'=>$call,'items'=>self::queue_items($call),'ordered'=>true]);}
    public static function manage_speaker_queue(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return new WP_Error('forbidden','Call host permission is required.',['status'=>403]);$action=sanitize_key((string)$r->get_param('action'));if(!in_array($action,['reorder','next'],true))return new WP_Error('sn_speaker_queue_action_invalid','Use reorder or next.',['status'=>400]);
        $lock=self::queue_lock($call);if(is_wp_error($lock))return $lock;try { if ($wpdb->query('START TRANSACTION') === false) throw new RuntimeException('transaction_start_failed');
            if(!self::call_manager($call,$actor))throw new RuntimeException('authority_changed');
            if($action==='reorder'){
                $order=array_values(array_unique(array_filter(array_map('absint',(array)$r->get_param('user_ids')))));$rows=self::feature_rows('F17-FUT-18',$call,true);$map=[];foreach($rows as $row){$d=self::decode($row);if(!is_wp_error($d)&&!empty($d['raised']))$map[(int)($d['user_id']??$row->owner_id)]=$row;}if(array_diff(array_keys($map),$order)||array_diff($order,array_keys($map)))throw new RuntimeException('order_invalid');$pos=1;foreach($order as $uid){if(!self::call_member_locked($call,$uid))throw new RuntimeException('member_changed');$row=$map[$uid];$d=self::decode($row);if(is_wp_error($d))throw new RuntimeException('decode');$d['position']=$pos++;$ok=self::save_row($row,$d);if(is_wp_error($ok))throw new RuntimeException('conflict');}
                if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');SN_DB::audit('future_speaker_queue_reordered','call',$call,'success',['order'=>$order],$actor);return rest_ensure_response(['call_id'=>$call,'items'=>self::queue_items($call)]);
            }
            $items=self::queue_items_locked($call);if(!$items){if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');return rest_ensure_response(['call_id'=>$call,'speaker_id'=>0,'items'=>[]]);}$next=(int)$items[0]['user_id'];foreach(self::feature_rows('F17-FUT-18',$call,true) as $row){$d=self::decode($row);if(is_wp_error($d))throw new RuntimeException('decode');$uid=(int)($d['user_id']??$row->owner_id);$d['speaking']=$uid===$next;$d['raised']=$uid===$next?false:(bool)($d['raised']??false);if($uid===$next)$d['position']=0;$saved=self::save_row($row,$d);if(is_wp_error($saved))throw new RuntimeException('conflict');}
            if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');SN_DB::audit('future_speaker_advanced','call',$call,'success',['speaker_id'=>$next],$actor);return rest_ensure_response(['call_id'=>$call,'speaker_id'=>$next,'items'=>self::queue_items($call)]);
        }catch(Throwable $e){$wpdb->query('ROLLBACK');$code=$e->getMessage();if($code==='authority_changed')return new WP_Error('forbidden','Call host permission changed before the queue update.',['status'=>403]);if($code==='order_invalid')return new WP_Error('sn_speaker_queue_order_invalid','Reorder must contain each currently raised participant exactly once.',['status'=>409]);if($code==='member_changed')return new WP_Error('sn_speaker_queue_member_changed','A queued participant is no longer in the call.',['status'=>409]);return new WP_Error('sn_speaker_queue_conflict','Speaker queue changed concurrently; no partial update was committed.',['status'=>409]);}finally{self::queue_unlock($lock);}
    }
    private static function queue_items(int $call):array{return self::queue_items_from_rows($call,self::feature_rows('F17-FUT-18',$call));}
    private static function queue_items_locked(int $call):array{return self::queue_items_from_rows($call,self::feature_rows('F17-FUT-18',$call,true));}
    private static function queue_items_from_rows(int $call,array $rows):array{$items=[];foreach($rows as $row){$d=self::decode($row);if(is_wp_error($d)||empty($d['raised']))continue;$uid=(int)($d['user_id']??$row->owner_id);if(!self::call_member($call,$uid))continue;$items[]=['user_id'=>$uid,'position'=>(int)($d['position']??PHP_INT_MAX),'speaking'=>(bool)($d['speaking']??false),'raised_at'=>$d['raised_at']??null];}usort($items,static fn($a,$b)=>($a['position']<=>$b['position'])?:($a['user_id']<=>$b['user_id']));return $items;}
    private static function feature_rows(string $feature,int $call,bool $lock=false):array{global $wpdb;$sql="SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id=%s AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id ASC LIMIT 500".($lock?' FOR UPDATE':'');$rows=$wpdb->get_results($wpdb->prepare($sql,$feature,$call));return is_array($rows)?$rows:[];}
    private static function upsert(string $feature,int $owner,int $call,array $data,string $client):int|WP_Error{global $wpdb;$key=hash('sha256',$client);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE client_key=%s LIMIT 1 FOR UPDATE",$key));$dummy=$row?:((object)['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>'call','scope_id'=>$call,'version'=>0]);$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);if($row){$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'state'=>'active','updated_at'=>$now,'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?(int)$row->id:new WP_Error('sn_future_conflict','Advanced communication state changed concurrently.',['status'=>409]);}$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>'call','scope_id'=>$call,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?new WP_Error('database_error','Advanced communication change could not be stored safely.',['status'=>500]):(int)$wpdb->insert_id;}
    private static function save_row(object $row,array $data):bool|WP_Error{global $wpdb;$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?true:new WP_Error('sn_future_conflict','Advanced communication state changed concurrently.',['status'=>409]);}
    private static function call_member(int $call,int $u):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status IN ('invited','joined') LIMIT 1",$call,$u));}
    private static function call_member_locked(int $call,int $u):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status IN ('invited','joined') LIMIT 1 FOR UPDATE",$call,$u));}
    private static function call_manager(int $call,int $u):bool{global $wpdb;$c=(int)$wpdb->get_var($wpdb->prepare('SELECT conversation_id FROM '.SN_DB::table('calls').' WHERE id=%d',$call));if(!$c)return false;$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-20' AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$call));if($rows){$d=self::decode($rows[0]);if(!is_wp_error($d)&&(int)($d['host_id']??0)===$u)return true;}return in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||user_can($u,'manage_options');}
    private static function queue_lock(int $call):string|WP_Error{global $wpdb;$lock='sn:f17:speaker-queue:'.$call;$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$lock,5));return $got===1?$lock:new WP_Error('sn_speaker_queue_busy','Speaker queue is busy; retry the operation.',['status'=>409]);}
    private static function queue_unlock(string|WP_Error $lock):void{if(is_wp_error($lock))return;global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:new WP_Error('sn_future_record_invalid','Advanced communication data is invalid.',['status'=>500]);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function not_found():WP_Error{return new WP_Error('not_found','Requested communication object is unavailable.',['status'=>404]);}
}
