<?php
/** Review round 50 — single-authoritative-host enforcement and joined-only co-host/transfer targets. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_V {
    public static function register(): void { add_action('rest_api_init', [self::class, 'routes'], 2140); }
    public static function routes(): void {
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/cohosts',['methods'=>'POST','callback'=>[self::class,'cohost'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-transfer',['methods'=>'POST','callback'=>[self::class,'propose_transfer'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-transfer/confirm',['methods'=>'POST','callback'=>[self::class,'confirm_transfer'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/host-takeover',['methods'=>'POST','callback'=>[self::class,'takeover'],'permission_callback'=>[SN_REST::class,'access']],true);
    }
    public static function cohost(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();if(!self::authoritative_host($call,$actor))return self::error('forbidden','Only the current authoritative host may change co-host grants.',403);$target=absint($r->get_param('user_id'));$action=sanitize_key((string)$r->get_param('action'));if($target<=0)return self::error('sn_call_cohost_invalid','Select a co-host account.',400);if($action==='revoke'&&!self::joined($call,$target))return self::revoke_stale_cohost($call,$target,$actor);if($action==='grant'&&(!self::joined($call,$target)||SN_DB::is_blocked($actor,$target)))return self::error('sn_call_cohost_invalid','Co-host must be a currently joined, unblocked participant.',409);return SN_Future24_Review_Hardening_F::cohost($r);
    }
    public static function propose_transfer(WP_REST_Request $r):WP_REST_Response|WP_Error{$call=absint($r['id']);$actor=get_current_user_id();$target=absint($r->get_param('user_id'));if(!self::authoritative_host($call,$actor))return self::error('forbidden','Only the current authoritative host may propose host transfer.',403);if($target<=0||$target===$actor||!self::joined($call,$target)||SN_DB::is_blocked($actor,$target))return self::error('sn_call_host_invalid','Transfer target must be another currently joined, unblocked participant.',409);return SN_Future24_Review_Hardening_F::propose_transfer($r);}
    public static function confirm_transfer(WP_REST_Request $r):WP_REST_Response|WP_Error{$call=absint($r['id']);$actor=get_current_user_id();if(!self::joined($call,$actor))return self::error('sn_call_host_transfer_invalid','Transfer target is no longer joined.',409);return SN_Future24_Review_Hardening_F::confirm_transfer($r);}
    public static function takeover(WP_REST_Request $r):WP_REST_Response|WP_Error{$call=absint($r['id']);$actor=get_current_user_id();if(!self::joined($call,$actor))return self::error('forbidden','Only a currently joined co-host may take over.',403);return SN_Future24_Review_Hardening_F::disconnect_takeover($r);}

    private static function authoritative_host(int $call,int $actor):bool{global $wpdb;$row=self::host_row($call);if($row){$d=self::decode($row);return !is_wp_error($d)&&(int)($d['host_id']??0)===$actor;}$conversation=(int)$wpdb->get_var($wpdb->prepare('SELECT conversation_id FROM '.SN_DB::table('calls').' WHERE id=%d',$call));return $conversation>0&&(in_array(SN_DB::member_role($conversation,$actor),['owner','moderator'],true)||current_user_can('manage_options'));}
    private static function revoke_stale_cohost(int $call,int $target,int $actor):WP_REST_Response|WP_Error{global $wpdb;$row=self::host_row($call);if(!$row)return self::error('sn_call_host_state_missing','No governed host state exists.',409);$d=self::decode($row);if(is_wp_error($d))return $d;$cohosts=array_values(array_unique(array_filter(array_map('absint',(array)($d['cohosts']??[])))));$d['cohosts']=array_values(array_diff($cohosts,[$target]));$d['updated_by']=$actor;$cipher=self::encode($row,$d);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)return self::error('sn_call_host_conflict','Host state changed concurrently.',409);SN_DB::audit('future_call_cohost_revoke','call',$call,'success',['user_id'=>$target,'stale_participant'=>true],$actor);return rest_ensure_response(['call_id'=>$call,'host_id'=>(int)($d['host_id']??0),'cohosts'=>$d['cohosts'],'version'=>(int)$row->version+1]);}
    private static function host_row(int $call):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}sn_future_records WHERE feature_id='F17-FUT-20' AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$call));return is_object($row)?$row:null;}
    private static function joined(int $call,int $user):bool{global $wpdb;return $user>0&&(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status='joined' LIMIT 1",$call,$user));}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
