<?php
/** Review round 36 — governed saved replies/templates with team scope, versions and preview-only variable resolution. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_N {
    private const ALLOWED_VARIABLES=['first_name','display_name','clinic_name','doctor_name','appointment_time','language'];
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],2002);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/future/templates',[['methods'=>'GET','callback'=>[self::class,'list_templates'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'create_template'],'permission_callback'=>[SN_REST::class,'access']]],true);
        register_rest_route('sabri-network/v2','/future/templates/(?P<id>\d+)',[['methods'=>'POST','callback'=>[self::class,'update_template'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'DELETE','callback'=>[self::class,'delete_template'],'permission_callback'=>[SN_REST::class,'access']]]);
        register_rest_route('sabri-network/v2','/future/templates/(?P<id>\d+)/preview',['methods'=>'POST','callback'=>[self::class,'preview_template'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/templates/(?P<id>\d+)/versions',['methods'=>'GET','callback'=>[self::class,'versions'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function create_template(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $actor=get_current_user_id();$scope=self::scope($r,$actor);if(is_wp_error($scope))return $scope;$body=mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('body'))),0,8000);$title=mb_substr(sanitize_text_field((string)$r->get_param('title')),0,120);if($title===''||$body==='')return self::error('sn_template_invalid','A title and template body are required.',400);$valid=self::validate_variables($body);if(is_wp_error($valid))return $valid;if(self::clinical($body)&&!(bool)apply_filters('sn_network_professional_template_allowed',false,$actor,$body,$scope))return self::error('sn_template_clinical_guard','Clinical directive templates require an approved professional policy.',403);$data=['subtype'=>'template','title'=>$title,'body'=>$body,'favorite'=>rest_sanitize_boolean($r->get_param('favorite')),'scope'=>$scope['type'],'conversation_id'=>$scope['conversation_id'],'version'=>1,'updated_by'=>$actor,'updated_at'=>current_time('mysql',true)];$id=self::insert('F17-FUT-08',$scope['owner_id'],$scope['scope_type'],$scope['scope_id'],$data,'template:'.$actor.':'.wp_generate_uuid4());if(is_wp_error($id))return $id;SN_DB::audit('future_template_created','future_record',$id,'success',['scope'=>$scope['type'],'clinical'=>self::clinical($body)],$actor);return new WP_REST_Response(['id'=>$id,'template'=>self::public_data($data)],201);
    }
    public static function update_template(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$actor=get_current_user_id();$id=absint($r['id']);$pre=self::template($id);if(!$pre||!self::may_edit($pre,$actor))return self::not_found();$expected=absint($r->get_param('expected_version'));if($expected<=0)return self::error('sn_template_stale','Refresh this template and provide its current version before editing.',409);
        try { if ($wpdb->query('START TRANSACTION') === false) throw new RuntimeException('transaction_start_failed');
            $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-08' AND state='active' LIMIT 1 FOR UPDATE",$id));
            if(!$row||!self::may_edit_locked($row,$actor))throw new RuntimeException('authority');
            if($expected!==(int)$row->version)throw new RuntimeException('stale');
            $current=self::decode($row);if(is_wp_error($current)||($current['subtype']??'template')!=='template')throw new RuntimeException('decode');
            $title=$r->has_param('title')?mb_substr(sanitize_text_field((string)$r->get_param('title')),0,120):(string)$current['title'];$body=$r->has_param('body')?mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('body'))),0,8000):(string)$current['body'];if($title===''||$body==='')throw new RuntimeException('invalid');$valid=self::validate_variables($body);if(is_wp_error($valid)){$wpdb->query('ROLLBACK');return $valid;}if(self::clinical($body)&&!(bool)apply_filters('sn_network_professional_template_allowed',false,$actor,$body,['type'=>$current['scope']??'user','conversation_id'=>(int)($current['conversation_id']??0)]))throw new RuntimeException('clinical');
            $rev=self::insert('F17-FUT-08',(int)$row->owner_id,(string)$row->scope_type,(int)$row->scope_id,['subtype'=>'template_revision','template_id'=>(int)$row->id,'revision'=>(int)$row->version,'title'=>(string)$current['title'],'body'=>(string)$current['body'],'favorite'=>(bool)($current['favorite']??false),'saved_at'=>current_time('mysql',true),'saved_by'=>$actor],'template-revision:'.$row->id.':'.$row->version);if(is_wp_error($rev))throw new RuntimeException('revision');
            $next=$current;$next['title']=$title;$next['body']=$body;if($r->has_param('favorite'))$next['favorite']=rest_sanitize_boolean($r->get_param('favorite'));$next['version']=(int)$row->version+1;$next['updated_by']=$actor;$next['updated_at']=current_time('mysql',true);$cipher=self::encode($row,$next);if(is_wp_error($cipher))throw new RuntimeException('crypto');$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)throw new RuntimeException('stale');
            if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');SN_DB::audit('future_template_updated','future_record',(int)$row->id,'success',['revision_id'=>$rev,'version'=>(int)$row->version+1],$actor);return rest_ensure_response(['id'=>(int)$row->id,'template'=>self::public_data($next),'version'=>(int)$row->version+1]);
        }catch(Throwable $e){$wpdb->query('ROLLBACK');$code=$e->getMessage();if($code==='authority')return self::error('sn_template_authority_revoked','Team-template authority changed before the edit could commit.',403);if($code==='stale')return self::error('sn_template_stale','Template changed concurrently.',409);if($code==='invalid')return self::error('sn_template_invalid','A title and template body are required.',400);if($code==='clinical')return self::error('sn_template_clinical_guard','Clinical directive templates require an approved professional policy.',403);return self::error('sn_template_update_failed','Template edit could not be committed safely.',500);}
    }
    public static function delete_template(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$actor=get_current_user_id();$id=absint($r['id']);$pre=self::template($id);if(!$pre||!self::may_edit($pre,$actor))return self::not_found();try { if ($wpdb->query('START TRANSACTION') === false) throw new RuntimeException('transaction_start_failed');$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-08' AND state='active' LIMIT 1 FOR UPDATE",$id));if(!$row||!self::may_edit_locked($row,$actor))throw new RuntimeException('authority');$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>'deleted','updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)throw new RuntimeException('stale');if($wpdb->query('COMMIT')===false)throw new RuntimeException('commit');SN_DB::audit('future_template_deleted','future_record',(int)$row->id,'success',[],$actor);return rest_ensure_response(['id'=>(int)$row->id,'state'=>'deleted']);}catch(Throwable $e){$wpdb->query('ROLLBACK');return $e->getMessage()==='authority'?self::error('sn_template_authority_revoked','Team-template authority changed before deletion.',403):self::error('sn_template_stale','Template changed concurrently.',409);}
    }
    public static function preview_template(WP_REST_Request $r):WP_REST_Response|WP_Error{$actor=get_current_user_id();$row=self::template(absint($r['id']));if(!$row||!self::may_view($row,$actor))return self::not_found();$d=self::decode($row);if(is_wp_error($d))return $d;$values=is_array($r->get_param('variables'))?$r->get_param('variables'):[];$unknown=array_diff(array_keys($values),self::ALLOWED_VARIABLES);if($unknown)return self::error('sn_template_variable_invalid','Template preview contains an unapproved variable.',400);$resolved=(string)$d['body'];foreach(self::ALLOWED_VARIABLES as $name){$value=array_key_exists($name,$values)?mb_substr(sanitize_text_field((string)$values[$name]),0,300):'';$resolved=str_replace('{{'.$name.'}}',$value,$resolved);}if(preg_match('/{{[^}]+}}/',$resolved))return self::error('sn_template_variable_missing','Supply every variable required by this template.',400);return rest_ensure_response(['id'=>(int)$row->id,'preview'=>$resolved,'send_performed'=>false,'authorization_required_again_at_send'=>true]);}
    public static function list_templates(WP_REST_Request $r):WP_REST_Response{global $wpdb;$actor=get_current_user_id();$q=mb_substr(sanitize_text_field((string)$r->get_param('q')),0,100);$favorite=$r->has_param('favorite')?rest_sanitize_boolean($r->get_param('favorite')):null;$rows=$wpdb->get_results("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-08' AND state='active' ORDER BY updated_at DESC,id DESC LIMIT 300");$items=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d)||($d['subtype']??'template')!=='template'||!self::may_view($row,$actor))continue;if($favorite!==null&&(bool)($d['favorite']??false)!==$favorite)continue;if($q!==''&&stripos((string)($d['title']??''),$q)===false&&stripos((string)($d['body']??''),$q)===false)continue;$items[]=['id'=>(int)$row->id,'template'=>self::public_data($d),'version'=>(int)$row->version];}return rest_ensure_response(['items'=>$items]);}
    public static function versions(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$actor=get_current_user_id();$row=self::template(absint($r['id']));if(!$row||!self::may_view($row,$actor))return self::not_found();$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-08' AND owner_id=%d AND scope_type=%s AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 300",(int)$row->owner_id,(string)$row->scope_type,(int)$row->scope_id));$items=[];foreach(is_array($rows)?$rows:[] as $rev){$d=self::decode($rev);if(is_wp_error($d)||($d['subtype']??'')!=='template_revision'||(int)($d['template_id']??0)!==(int)$row->id)continue;$items[]=['revision'=>(int)($d['revision']??0),'title'=>(string)($d['title']??''),'body'=>(string)($d['body']??''),'saved_at'=>$d['saved_at']??null,'saved_by'=>(int)($d['saved_by']??0)];}return rest_ensure_response(['template_id'=>(int)$row->id,'versions'=>$items]);}
    private static function scope(WP_REST_Request $r,int $actor):array|WP_Error{$type=sanitize_key((string)$r->get_param('scope'));if($type!=='team')return ['type'=>'user','owner_id'=>$actor,'scope_type'=>'user','scope_id'=>$actor,'conversation_id'=>0];$conversation=absint($r->get_param('conversation_id'));if($conversation<=0||!SN_DB::is_member($conversation,$actor)||!has_filter('sn_network_team_inbox_delegation_allowed')||!(bool)apply_filters('sn_network_team_inbox_delegation_allowed',false,$conversation,$actor,'template_manage'))return self::error('sn_template_team_scope_forbidden','Current team-template delegation is required.',403);return ['type'=>'team','owner_id'=>0,'scope_type'=>'conversation','scope_id'=>$conversation,'conversation_id'=>$conversation];}
    private static function may_view(object $row,int $actor):bool{if((string)$row->scope_type==='user')return (int)$row->owner_id===$actor;$c=(int)$row->scope_id;return SN_DB::is_member($c,$actor)&&has_filter('sn_network_team_inbox_delegation_allowed')&&(bool)apply_filters('sn_network_team_inbox_delegation_allowed',false,$c,$actor,'template_view');}
    private static function may_edit(object $row,int $actor):bool{if((string)$row->scope_type==='user')return (int)$row->owner_id===$actor;$c=(int)$row->scope_id;return SN_DB::is_member($c,$actor)&&has_filter('sn_network_team_inbox_delegation_allowed')&&(bool)apply_filters('sn_network_team_inbox_delegation_allowed',false,$c,$actor,'template_manage');}
    private static function may_edit_locked(object $row,int $actor):bool{if((string)$row->scope_type==='user')return (int)$row->owner_id===$actor;global $wpdb;$c=(int)$row->scope_id;$member=$wpdb->get_var($wpdb->prepare('SELECT id FROM '.SN_DB::table('members').' WHERE conversation_id=%d AND user_id=%d AND left_at IS NULL LIMIT 1 FOR UPDATE',$c,$actor));return(bool)$member&&has_filter('sn_network_team_inbox_delegation_allowed')&&(bool)apply_filters('sn_network_team_inbox_delegation_allowed',false,$c,$actor,'template_manage');}
    private static function validate_variables(string $body):bool|WP_Error{preg_match_all('/{{\s*([a-zA-Z0-9_]+)\s*}}/',$body,$m);foreach(array_unique($m[1]??[]) as $name)if(!in_array($name,self::ALLOWED_VARIABLES,true))return self::error('sn_template_variable_invalid','Template contains an unapproved variable: '.$name,400);return true;}
    private static function clinical(string $body):bool{return(bool)preg_match('/\b(prescribe|prescription|dose|dosage|diagnose|diagnosis|take\s+\d|potency|medicine|remedy)\b/i',$body);}
    private static function template(int $id):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-08' AND state='active' LIMIT 1",$id));if(!$row)return null;$d=self::decode($row);return is_wp_error($d)||($d['subtype']??'template')!=='template'?null:$row;}
    private static function insert(string $feature,int $owner,string $type,int $scope,array $d,string $client):int|WP_Error{global $wpdb;$dummy=(object)['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>$type,'scope_id'=>$scope];$cipher=self::encode($dummy,$d);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>$feature,'owner_id'=>$owner,'scope_type'=>$type,'scope_id'=>$scope,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>hash('sha256',$client),'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Template could not be stored safely.',500):(int)$wpdb->insert_id;}
    private static function public_data(array $d):array{return ['title'=>(string)($d['title']??''),'body'=>(string)($d['body']??''),'favorite'=>(bool)($d['favorite']??false),'scope'=>(string)($d['scope']??'user'),'conversation_id'=>(int)($d['conversation_id']??0),'version'=>(int)($d['version']??1)];}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}private static function encode(object $row,array $d):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($d),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
