<?php
/** Review round 29+ — standards-based interoperability with replay, quarantine and kill-switch controls. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_H {
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1998);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/future/interop',[['methods'=>'GET','callback'=>[self::class,'list_bridges'],'permission_callback'=>[SN_REST::class,'access']],['methods'=>'POST','callback'=>[self::class,'create_bridge'],'permission_callback'=>[SN_REST::class,'access']]],true);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)',['methods'=>'DELETE','callback'=>[self::class,'revoke_bridge'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)/inbound',['methods'=>'POST','callback'=>[self::class,'inbound'],'permission_callback'=>[self::class,'inbound_permission']]);
        register_rest_route('sabri-network/v2','/future/interop/(?P<id>\d+)/outbound',['methods'=>'POST','callback'=>[self::class,'outbound'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function inbound_permission(WP_REST_Request $r):bool|WP_Error{return (bool)apply_filters('sn_network_interop_inbound_authorized',false,absint($r['id']),$r)?:self::error('sn_interop_inbound_unauthorized','Interoperability adapter authentication failed.',403);}
    public static function create_bridge(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $actor=get_current_user_id();$conversation=absint($r->get_param('conversation_id'));if(!self::conversation_manager($conversation,$actor))return self::error('forbidden','Conversation management permission is required.',403);$protocol=sanitize_key((string)$r->get_param('protocol'));if(!in_array($protocol,['matrix','activitypub','custom-approved'],true))return self::error('sn_interop_protocol_invalid','Select an approved interoperability protocol.',400);$remote=esc_url_raw((string)$r->get_param('remote_endpoint'),['https']);if($remote===''||wp_parse_url($remote,PHP_URL_SCHEME)!=='https')return self::error('sn_interop_endpoint_invalid','A secure HTTPS endpoint is required.',400);if(!(bool)apply_filters('sn_network_interop_remote_allowed',false,$remote,$protocol,$conversation,$actor)||!(bool)apply_filters('sn_network_interop_provider_ready',false,$protocol,$conversation,$actor))return self::error('sn_interop_not_approved','Interoperability provider or destination is not approved.',503);$direction=sanitize_key((string)$r->get_param('direction'));if(!in_array($direction,['outbound','bidirectional'],true))$direction='outbound';$credential=mb_substr(sanitize_text_field((string)$r->get_param('credential_ref')),0,191);if(preg_match('/(bearer|password|secret|token=)/i',$credential))return self::error('sn_interop_secret_ref_invalid','Store only an opaque credential reference, never a secret.',400);$data=['subtype'=>'bridge','protocol'=>$protocol,'remote_endpoint'=>$remote,'remote_room'=>mb_substr(sanitize_text_field((string)$r->get_param('remote_room')),0,191),'credential_ref'=>$credential,'direction'=>$direction,'identity_authority'=>'file-00/02-local','created_by'=>$actor,'kill_switch'=>false];$id=self::create_record(0,$conversation,$data,'interop-bridge:'.$conversation.':'.$protocol.':'.hash('sha256',$remote.'|'.$data['remote_room']));if(is_wp_error($id))return $id;SN_DB::audit('future_interop_bridge_created','conversation',$conversation,'success',['bridge_id'=>$id,'protocol'=>$protocol,'direction'=>$direction],$actor);return new WP_REST_Response(['id'=>$id,'bridge'=>self::public_bridge($data),'canonical_truth'=>'file-17'],201);
    }
    public static function list_bridges(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$actor=get_current_user_id();$conversation=absint($r->get_param('conversation_id'));if(!self::conversation_manager($conversation,$actor))return self::error('forbidden','Conversation management permission is required.',403);$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-24' AND scope_type='conversation' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 100",$conversation));$items=[];foreach(is_array($rows)?$rows:[] as $row){$d=self::decode($row);if(is_wp_error($d)||($d['subtype']??'')!=='bridge')continue;$items[]=['id'=>(int)$row->id,'bridge'=>self::public_bridge($d)];}return rest_ensure_response(['conversation_id'=>$conversation,'items'=>$items]);}
    public static function revoke_bridge(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$actor=get_current_user_id();$row=self::bridge(absint($r['id']));if(!$row)return self::not_found();if(!self::conversation_manager((int)$row->scope_id,$actor))return self::error('forbidden','Conversation management permission is required.',403);$d=self::decode($row);if(is_wp_error($d))return $d;$provider=apply_filters('sn_network_interop_kill_switch_result',null,(int)$row->id,$d,(int)$row->scope_id,$actor);if($provider===null||$provider===false)return self::error('sn_interop_kill_switch_unavailable','Provider could not confirm bridge shutdown.',503);if(is_wp_error($provider))return $provider;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>'revoked','updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>(int)$row->id,'state'=>'active','version'=>(int)$row->version]);if($ok!==1)return self::error('sn_interop_conflict','Bridge changed concurrently.',409);SN_DB::audit('future_interop_bridge_revoked','conversation',(int)$row->scope_id,'success',['bridge_id'=>(int)$row->id],$actor);return rest_ensure_response(['id'=>(int)$row->id,'state'=>'revoked']);}
    public static function inbound(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$bridge=self::bridge(absint($r['id']));if(!$bridge)return self::not_found();$d=self::decode($bridge);if(is_wp_error($d)||($d['direction']??'outbound')!=='bidirectional')return self::error('sn_interop_inbound_disabled','Inbound interoperability is disabled for this bridge.',403);if(!SN_Policy::consume_rate_limit('interop_inbound',(string)$bridge->id,120,MINUTE_IN_SECONDS))return self::error('sn_interop_rate_limited','Interoperability rate limit exceeded.',429);$event_id=mb_substr(sanitize_text_field((string)$r->get_param('event_id')),0,191);if($event_id==='')return self::error('sn_interop_event_id_required','A stable external event identifier is required.',400);$receipt=hash('sha256','interop-inbound:'.$bridge->id.':'.$event_id);if((bool)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.$wpdb->prefix.'sn_future_records WHERE client_key=%s LIMIT 1',$receipt)))return rest_ensure_response(['accepted'=>true,'duplicate'=>true]);$payload=$r->get_param('payload');if(!is_array($payload))return self::error('sn_interop_payload_invalid','Inbound payload must be a structured object.',400);$decision=apply_filters('sn_network_interop_inbound_filter',null,$payload,$d,(int)$bridge->scope_id,(int)$bridge->id);if(!is_array($decision)||!in_array(($decision['decision']??''),['allow','quarantine','deny'],true))return self::error('sn_interop_filter_unavailable','Inbound interoperability filter is unavailable.',503);$state=(string)$decision['decision'];$meta=['subtype'=>'receipt','bridge_id'=>(int)$bridge->id,'event_id_hash'=>hash('sha256',$event_id),'payload_hash'=>hash('sha256',(string)wp_json_encode($payload)),'decision'=>$state,'reason'=>mb_substr(sanitize_text_field((string)($decision['reason']??'')),0,191)];$id=self::create_record(0,(int)$bridge->scope_id,$meta,'interop-inbound:'.$bridge->id.':'.$event_id);if(is_wp_error($id))return $id;if($state==='allow'){do_action('sn_network_interop_inbound_accepted',['bridge_id'=>(int)$bridge->id,'conversation_id'=>(int)$bridge->scope_id,'external_event_id'=>$event_id,'sanitized_payload'=>$decision['payload']??[],'receipt_id'=>$id]);}SN_DB::audit('future_interop_inbound','conversation',(int)$bridge->scope_id,$state==='allow'?'success':'failure',['bridge_id'=>(int)$bridge->id,'receipt_id'=>$id,'decision'=>$state],0);return new WP_REST_Response(['accepted'=>$state==='allow','quarantined'=>$state==='quarantine','receipt_id'=>$id],$state==='allow'?202:($state==='quarantine'?202:403));}
    public static function outbound(WP_REST_Request $r):WP_REST_Response|WP_Error{global $wpdb;$actor=get_current_user_id();$bridge=self::bridge(absint($r['id']));if(!$bridge)return self::not_found();if(!self::conversation_manager((int)$bridge->scope_id,$actor))return self::error('forbidden','Conversation management permission is required.',403);if(!SN_Policy::consume_rate_limit('interop_outbound',(string)$bridge->id,120,MINUTE_IN_SECONDS))return self::error('sn_interop_rate_limited','Interoperability rate limit exceeded.',429);$message=absint($r->get_param('message_id'));$m=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.SN_DB::table('messages').' WHERE id=%d',$message));if(!$m||(int)$m->conversation_id!==(int)$bridge->scope_id||!empty($m->deleted_at)||SN_Message_Operations::is_hidden($actor,$message))return self::not_found();$d=self::decode($bridge);if(is_wp_error($d))return $d;$decision=apply_filters('sn_network_interop_outbound_filter',null,$message,$m,$d,$actor);if(!is_array($decision)||empty($decision['allow']))return self::error('sn_interop_outbound_denied','Outbound bridge policy did not approve this message.',403);$provider=apply_filters('sn_network_interop_outbound_result',null,$d,$decision,$message,$actor);if($provider===null||$provider===false)return self::error('sn_interop_provider_unavailable','Interoperability provider is unavailable.',503);if(is_wp_error($provider))return $provider;SN_DB::audit('future_interop_outbound','message',$message,'success',['bridge_id'=>(int)$bridge->id,'payload_hash'=>hash('sha256',(string)wp_json_encode($decision))],$actor);return rest_ensure_response(['queued'=>true,'bridge_id'=>(int)$bridge->id,'message_id'=>$message]);}
    private static function bridge(int $id):?object{global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-24' AND scope_type='conversation' AND state='active' LIMIT 1",$id));return is_object($row)?$row:null;}
    private static function create_record(int $owner,int $conversation,array $data,string $client):int|WP_Error{global $wpdb;$key=hash('sha256',$client);$existing=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.$wpdb->prefix.'sn_future_records WHERE client_key=%s',$key));if($existing)return $existing;$dummy=(object)['feature_id'=>'F17-FUT-24','owner_id'=>$owner,'scope_type'=>'conversation','scope_id'=>$conversation];$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-24','owner_id'=>$owner,'scope_type'=>'conversation','scope_id'=>$conversation,'state'=>'active','payload_cipher'=>$cipher,'client_key'=>$key,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===false?self::error('database_error','Interoperability state could not be stored safely.',500):(int)$wpdb->insert_id;}
    private static function public_bridge(array $d):array{return ['protocol'=>(string)($d['protocol']??''),'remote_endpoint'=>(string)($d['remote_endpoint']??''),'remote_room'=>(string)($d['remote_room']??''),'direction'=>(string)($d['direction']??'outbound'),'identity_authority'=>'file-00/02-local'];}
    private static function conversation_manager(int $c,int $u):bool{return $c>0&&(in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||current_user_can('manage_options'));}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
