<?php
/** Review rounds 31–32 — serialized, verifiable key-transparency ledger with revocation lifecycle. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_J {
    private const MAX_VERIFY_ROWS=10000;
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1999);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/future/device-keys',['methods'=>'POST','callback'=>[self::class,'register_device_key'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/future/device-keys/(?P<device_id>[A-Za-z0-9._:-]+)',['methods'=>'DELETE','callback'=>[self::class,'revoke_device_key'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/key-transparency/(?P<user_id>\d+)/verify',['methods'=>'GET','callback'=>[self::class,'verify_ledger'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/future/key-transparency/checkpoint',['methods'=>'GET','callback'=>[self::class,'checkpoint'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function register_device_key(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$user=get_current_user_id();$device=mb_substr(sanitize_text_field((string)$r->get_param('device_id')),0,96);if($device==='')return self::error('sn_device_key_invalid','A valid device identifier is required.',400);$lock='sn_f17_future_key_log_v1';$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,5)',$lock));if($got!==1)return self::error('sn_key_ledger_busy','Key transparency is temporarily busy; retry safely.',503);$wpdb->query('START TRANSACTION');try{$before=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->prefix.'sn_future_key_log WHERE user_id=%d AND device_id=%s',$user,$device));$response=SN_Future_Superset::register_device_key($r);if(is_wp_error($response)){$wpdb->query('ROLLBACK');return $response;}$after=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->prefix.'sn_future_key_log WHERE user_id=%d AND device_id=%s',$user,$device));if($after!==$before+1){$wpdb->query('ROLLBACK');return self::error('sn_key_ledger_write_failed','Device key was not committed because its transparency event could not be recorded.',500);}$integrity=self::verify_all(false);if(is_wp_error($integrity)||empty($integrity['valid'])){$wpdb->query('ROLLBACK');return self::error('sn_key_ledger_integrity_failed','Device key was not committed because transparency integrity verification failed.',500);}$wpdb->query('COMMIT');return $response;}catch(Throwable $e){$wpdb->query('ROLLBACK');return self::error('sn_key_ledger_write_failed','Device key update could not be committed safely.',500);}finally{$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}}
    public static function revoke_device_key(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$user=get_current_user_id();$device=mb_substr(sanitize_text_field((string)$r['device_id']),0,96);$lock='sn_f17_future_key_log_v1';$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,5)',$lock));if($got!==1)return self::error('sn_key_ledger_busy','Key transparency is temporarily busy; retry safely.',503);$wpdb->query('START TRANSACTION');try{$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_device_keys WHERE user_id=%d AND device_id=%s AND state='active' LIMIT 1 FOR UPDATE",$user,$device));if(!$row){$wpdb->query('ROLLBACK');return self::not_found();}$now=current_time('mysql',true);$ok=$wpdb->update($wpdb->prefix.'sn_future_device_keys',['state'=>'revoked','updated_at'=>$now,'revoked_at'=>$now],['id'=>(int)$row->id,'state'=>'active']);if($ok!==1)throw new RuntimeException('key_state_conflict');if(!self::append_log($user,$device,'revoked',(string)$row->fingerprint,(string)$row->fingerprint,$now))throw new RuntimeException('key_log_failed');$verify=self::verify_all(false);if(is_wp_error($verify)||empty($verify['valid']))throw new RuntimeException('key_log_invalid');$wpdb->query('COMMIT');SN_DB::audit('future_device_key_revoked','user',$user,'success',['device_hash'=>hash('sha256',$device),'fingerprint'=>(string)$row->fingerprint],$user);return rest_ensure_response(['device_id'=>$device,'state'=>'revoked','fingerprint'=>(string)$row->fingerprint]);}catch(Throwable $e){$wpdb->query('ROLLBACK');return self::error('sn_key_revoke_failed','Device key could not be revoked with ledger integrity.',500);}finally{$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}}
    public static function verify_ledger(WP_REST_Request $r):WP_REST_Response|WP_Error{$actor=get_current_user_id();$target=absint($r['user_id']);if($target<=0||($target!==$actor&&(SN_DB::is_blocked($actor,$target)||!SN_DB::share_active_conversation($actor,$target))))return self::not_found();$verify=self::verify_all(true);if(is_wp_error($verify))return $verify;return rest_ensure_response(['user_id'=>$target,'ledger_valid'=>(bool)$verify['valid'],'entries_verified'=>(int)$verify['count'],'latest_entry_hash'=>(string)$verify['latest'],'complete'=>(bool)$verify['complete']]);}
    public static function checkpoint():WP_REST_Response|WP_Error{$verify=self::verify_all(true);if(is_wp_error($verify))return $verify;if(empty($verify['valid'])||empty($verify['complete']))return self::error('sn_key_ledger_not_checkpointable','A complete valid ledger is required for a checkpoint.',409);$claims=['typ'=>'f17-key-transparency-checkpoint','count'=>(int)$verify['count'],'latest'=>(string)$verify['latest'],'iat'=>time(),'exp'=>time()+DAY_IN_SECONDS];$signed=SN_Communication_Crypto::sign($claims,'future-key-transparency-checkpoint');return rest_ensure_response(['checkpoint'=>$claims,'signed_checkpoint'=>$signed]);}
    private static function append_log(int $user,string $device,string $event,string $fp,string $prev,string $at):bool{global $wpdb;$last=(string)$wpdb->get_var('SELECT entry_hash FROM '.$wpdb->prefix.'sn_future_key_log ORDER BY id DESC LIMIT 1');$hash=hash('sha256',$last.'|'.$user.'|'.$device.'|'.$event.'|'.$fp.'|'.$prev.'|'.$at);return $wpdb->insert($wpdb->prefix.'sn_future_key_log',['user_id'=>$user,'device_id'=>$device,'event'=>$event,'fingerprint'=>$fp,'previous_fingerprint'=>$prev,'entry_hash'=>$hash,'created_at'=>$at])!==false;}
    private static function verify_all(bool $allow_limit):array|WP_Error{global $wpdb;$count=(int)$wpdb->get_var('SELECT COUNT(*) FROM '.$wpdb->prefix.'sn_future_key_log');if($count>self::MAX_VERIFY_ROWS)return $allow_limit?['valid'=>false,'count'=>self::MAX_VERIFY_ROWS,'latest'=>'','complete'=>false]:self::error('sn_key_ledger_too_large','Key ledger requires the background verifier before accepting another key change.',503);$rows=$wpdb->get_results('SELECT id,user_id,device_id,event,fingerprint,previous_fingerprint,entry_hash,created_at FROM '.$wpdb->prefix.'sn_future_key_log ORDER BY id ASC LIMIT '.self::MAX_VERIFY_ROWS);$last='';$seen=0;foreach(is_array($rows)?$rows:[] as $row){$expected=hash('sha256',$last.'|'.(int)$row->user_id.'|'.(string)$row->device_id.'|'.(string)$row->event.'|'.(string)$row->fingerprint.'|'.(string)$row->previous_fingerprint.'|'.(string)$row->created_at);if(!hash_equals($expected,(string)$row->entry_hash))return ['valid'=>false,'count'=>$seen,'latest'=>$last,'complete'=>true];$last=(string)$row->entry_hash;$seen++;}return ['valid'=>true,'count'=>$seen,'latest'=>$last,'complete'=>$seen===$count];}
    private static function not_found():WP_Error{return self::error('not_found','Requested communication object is unavailable.',404);}private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
