<?php
declare(strict_types=1); defined('ABSPATH') || exit;
trait SN_Future_Superset_Part_1 {
    public static function capabilities(): WP_REST_Response {
        $provider=(array)apply_filters('sn_network_e2ee_provider_status',[]); $items=[];
        $device_ready=has_filter('sn_network_device_public_key_valid') && apply_filters('sn_network_device_key_provider_ready',false)===true;
        $ai_ready=has_filter('sn_network_ai_assistant_result') && has_filter('sn_network_ai_context_authorized') && has_filter('sn_network_ai_context_redact') && apply_filters('sn_network_ai_provider_ready',false)===true;
        $semantic_ready=has_filter('sn_network_private_semantic_search_result') && apply_filters('sn_network_private_semantic_provider_ready',false)===true;
        foreach(self::features() as $id=>$f){$status='available'; if($id==='F17-FUT-01'&&(empty($provider['ready'])||empty($provider['audited'])))$status='provider-gated'; if(in_array($id,['F17-FUT-02','F17-FUT-03'],true)&&!$device_ready)$status='provider-gated'; if($id==='F17-FUT-22'&&!$ai_ready)$status='provider-gated'; if($id==='F17-FUT-23'&&!$semantic_ready)$status='provider-gated'; if(in_array($id,['F17-FUT-17','F17-FUT-18','F17-FUT-19','F17-FUT-20'],true)&&!(bool)apply_filters('sn_network_sfu_available',false,get_current_user_id(),0))$status='provider-gated'; $items[]=['id'=>$id]+$f+['status'=>$status];}
        return rest_ensure_response(['schema_version'=>self::SCHEMA_VERSION,'feature_count'=>self::FEATURE_COUNT,'items'=>$items]);
    }
    public static function set_e2ee_policy(WP_REST_Request $r): WP_REST_Response|WP_Error {
        $c=absint($r->get_param('conversation_id'));$u=get_current_user_id();if(!self::conversation_manager($c,$u))return self::error('forbidden','Conversation management permission is required.',403);$enabled=rest_sanitize_boolean($r->get_param('enabled'));$p=(array)apply_filters('sn_network_e2ee_provider_status',[],$c,$u);if($enabled&&(empty($p['ready'])||empty($p['audited'])||empty($p['protocol'])))return self::error('sn_e2ee_provider_unavailable','Audited E2EE cannot be enabled until an approved audited protocol provider is ready.',503);$data=['enabled'=>$enabled,'protocol'=>$enabled?sanitize_text_field((string)$p['protocol']):'','provider_audit_ref'=>$enabled?sanitize_text_field((string)($p['audit_ref']??'')):''];$id=self::upsert_record('F17-FUT-01',0,'conversation',$c,$data,'e2ee:'.$c,null);return is_wp_error($id)?$id:rest_ensure_response(['conversation_id'=>$c,'policy'=>$data]);
    }
    public static function register_device_key(WP_REST_Request $r): WP_REST_Response|WP_Error {
        global $wpdb;$u=get_current_user_id();$device=mb_substr(sanitize_text_field((string)$r->get_param('device_id')),0,96);$alg=mb_substr(sanitize_key((string)$r->get_param('algorithm')),0,48);$key=trim((string)$r->get_param('public_key'));if($device===''||$alg===''||$key===''||strlen($key)>16384)return self::error('sn_device_key_invalid','A valid device identifier, algorithm and public key are required.',400);if(!has_filter('sn_network_device_public_key_valid')||!(bool)apply_filters('sn_network_device_public_key_valid',false,$alg,$key,$u,$device))return self::error('sn_device_key_provider_unavailable','Device-key registration requires an approved key-validation provider.',503);$fp=hash('sha256',$alg.'|'.$key);$old=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::device_keys_table().' WHERE user_id=%d AND device_id=%s',$u,$device));$now=self::now();$ok=$old?$wpdb->update(self::device_keys_table(),['algorithm'=>$alg,'public_key'=>$key,'fingerprint'=>$fp,'state'=>'active','updated_at'=>$now,'revoked_at'=>null],['id'=>(int)$old->id]):$wpdb->insert(self::device_keys_table(),['user_id'=>$u,'device_id'=>$device,'algorithm'=>$alg,'public_key'=>$key,'fingerprint'=>$fp,'state'=>'active','created_at'=>$now,'updated_at'=>$now]);if($ok===false)return self::db_error();self::append_key_log($u,$device,$old?'rotated':'registered',$fp,$old?(string)$old->fingerprint:'');return rest_ensure_response(['device_id'=>$device,'fingerprint'=>self::pretty_fp($fp)]);
    }
    public static function list_device_keys(): WP_REST_Response {global $wpdb;$u=get_current_user_id();$rows=$wpdb->get_results($wpdb->prepare('SELECT device_id,algorithm,fingerprint,state,created_at,updated_at FROM '.self::device_keys_table().' WHERE user_id=%d ORDER BY id DESC',$u));return rest_ensure_response(['items'=>array_map(static fn($x)=>['device_id'=>(string)$x->device_id,'algorithm'=>(string)$x->algorithm,'fingerprint'=>self::pretty_fp((string)$x->fingerprint),'state'=>(string)$x->state,'created_at'=>(string)$x->created_at,'updated_at'=>(string)$x->updated_at],is_array($rows)?$rows:[])]);}
    public static function safety_number(WP_REST_Request $r): WP_REST_Response|WP_Error {
        global $wpdb;$u=get_current_user_id();$t=absint($r['user_id']);if($t<=0||SN_DB::is_blocked($u,$t)||!SN_DB::share_active_conversation($u,$t))return self::not_found();
        $a=array_map('strval',$wpdb->get_col($wpdb->prepare("SELECT fingerprint FROM ".self::device_keys_table()." WHERE user_id=%d AND state='active' ORDER BY fingerprint",$u)));
        $b=array_map('strval',$wpdb->get_col($wpdb->prepare("SELECT fingerprint FROM ".self::device_keys_table()." WHERE user_id=%d AND state='active' ORDER BY fingerprint",$t)));
        if(!$a||!$b)return self::error('sn_device_keys_incomplete','Both accounts need active device keys.',409);sort($a,SORT_STRING);sort($b,SORT_STRING);
        $participants=[['user_id'=>$u,'fingerprints'=>$a],['user_id'=>$t,'fingerprints'=>$b]];usort($participants,static fn(array $x,array $y):int=>$x['user_id']<=>$y['user_id']);
        $material=[];foreach($participants as $participant)$material[]=$participant['user_id'].':'.implode(',',$participant['fingerprints']);
        $num=hash('sha256','f17-safety-v1|'.implode('|',$material));return rest_ensure_response(['user_id'=>$t,'safety_number'=>strtoupper(implode(' ',str_split(substr($num,0,60),5)))]);
    }
    public static function key_transparency(WP_REST_Request $r): WP_REST_Response|WP_Error {global $wpdb;$u=get_current_user_id();$t=absint($r['user_id']);if($t<=0||($t!==$u&&(SN_DB::is_blocked($u,$t)||!SN_DB::share_active_conversation($u,$t))))return self::not_found();$rows=$wpdb->get_results($wpdb->prepare('SELECT id,device_id,event,fingerprint,previous_fingerprint,entry_hash,created_at FROM '.self::key_log_table().' WHERE user_id=%d ORDER BY id ASC LIMIT 500',$t));return rest_ensure_response(['user_id'=>$t,'entries'=>$rows?:[]]);}
    public static function set_conversation_lock(WP_REST_Request $r): WP_REST_Response|WP_Error {$c=absint($r['id']);$u=get_current_user_id();if(!self::conversation_member($c,$u))return self::not_found();$existing=self::active_record('F17-FUT-04',$u,'conversation',$c);if($existing){$old=self::decode($existing);if(!is_wp_error($old)&&!empty($old['enabled'])&&!(bool)apply_filters('sn_network_step_up_verified',false,$u,$c,'conversation_lock',max(60,min(3600,(int)($old['step_up_ttl']??900)))))return self::error('sn_conversation_step_up_required','Fresh step-up verification is required before changing this sensitive conversation lock.',403);}$data=['enabled'=>rest_sanitize_boolean($r->get_param('enabled')),'step_up_ttl'=>max(60,min(3600,absint($r->get_param('step_up_ttl'))?:900))];$id=self::upsert_record('F17-FUT-04',$u,'conversation',$c,$data,'lock:'.$u.':'.$c,null);return is_wp_error($id)?$id:rest_ensure_response($data);}
    public static function pre_dispatch($result,$server,WP_REST_Request $r){if($result!==null)return $result;$route=$r->get_route();if(!str_starts_with($route,'/sabri-network/v2/'))return $result;$u=get_current_user_id();if($u<=0)return $result;$c=0;$m=null;if(preg_match('#/conversations/(\d+)#',$route,$x))$c=(int)$x[1];elseif(preg_match('#/messages/(\d+)#',$route,$x)){$m=self::message_row((int)$x[1]);$c=$m?(int)$m->conversation_id:0;}elseif(preg_match('#/future/team-inbox/(\d+)#',$route,$x))$c=(int)$x[1];if($c<=0&&in_array($route,['/sabri-network/v2/future/e2ee-policy','/sabri-network/v2/future/reminders','/sabri-network/v2/future/citations','/sabri-network/v2/future/case-discussions','/sabri-network/v2/future/ai-assistant','/sabri-network/v2/future/semantic-search','/sabri-network/v2/future/interop'],true))$c=absint($r->get_param('conversation_id'));if($c<=0)return $result;$lock=self::active_record('F17-FUT-04',$u,'conversation',$c);if($lock){$d=self::decode($lock);if(!is_wp_error($d)&&!empty($d['enabled'])&&!(bool)apply_filters('sn_network_step_up_verified',false,$u,$c,'conversation_lock',(int)($d['step_up_ttl']??900)))return self::error('sn_conversation_step_up_required','This sensitive conversation requires fresh step-up verification.',403);}if($r->get_method()==='POST'&&preg_match('#^/sabri-network/v2/messages/\d+$#',$route)&&$m&&self::conversation_member($c,$u)&&!SN_Message_Operations::is_hidden($u,(int)$m->id)&&SN_Policy::can_edit_message($m,$u)){$new=trim(sanitize_textarea_field(wp_unslash((string)$r->get_param('body'))));$old=SN_Message_Body::decrypt_row($m);if(!is_wp_error($old)&&$new!==''&&hash('sha256',$old)!==hash('sha256',$new)){$id=self::capture_message_version($m,$u);if(is_wp_error($id))return $id;$r->set_param('_sn_future_snapshot_id',(int)$id);}}return $result;}
    public static function post_dispatch($response,$server,WP_REST_Request $r){$id=absint($r->get_param('_sn_future_snapshot_id'));if($id>0&&method_exists($response,'get_status')&&(int)$response->get_status()>=400){global $wpdb;$wpdb->delete(self::versions_table(),['id'=>$id],['%d']);}return $response;}
    public static function get_team_inbox(WP_REST_Request $r): WP_REST_Response|WP_Error {$c=absint($r['id']);$u=get_current_user_id();if(!self::conversation_member($c,$u))return self::not_found();$row=self::active_record('F17-FUT-05',0,'conversation',$c);$d=$row?self::decode($row):[];return is_wp_error($d)?$d:rest_ensure_response(['conversation_id'=>$c,'team_inbox'=>$d?:['enabled'=>false,'assignee_id'=>0,'status'=>'open']]);}
    public static function set_team_inbox(WP_REST_Request $r): WP_REST_Response|WP_Error {$c=absint($r['id']);$u=get_current_user_id();if(!self::conversation_manager($c,$u))return self::error('forbidden','Conversation management permission is required.',403);$a=absint($r->get_param('assignee_id'));if($a&&!self::conversation_member($c,$a))return self::error('sn_assignment_member_required','The assignee must be an active conversation member.',409);$d=['enabled'=>rest_sanitize_boolean($r->get_param('enabled')),'assignee_id'=>$a,'status'=>self::enum((string)$r->get_param('status'),['open','pending','resolved'],'open'),'updated_by'=>$u];$id=self::upsert_record('F17-FUT-05',0,'conversation',$c,$d,'team:'.$c,null);if(is_wp_error($id))return $id;self::upsert_record('F17-FUT-06',0,'conversation',$c,['assignee_id'=>$a,'handoff_by'=>$u,'status'=>$d['status']],'assignment:'.$c,null);return rest_ensure_response(['conversation_id'=>$c,'team_inbox'=>$d]);}
    public static function handoff_team_inbox(WP_REST_Request $r): WP_REST_Response|WP_Error {$r->set_param('enabled',true);return self::set_team_inbox($r);}
    public static function create_reminder(WP_REST_Request $r): WP_REST_Response|WP_Error {$u=get_current_user_id();$at=self::future_time((string)$r->get_param('remind_at'),365*DAY_IN_SECONDS);if(is_wp_error($at))return $at;$c=absint($r->get_param('conversation_id'));if($c&&!self::conversation_member($c,$u))return self::not_found();$id=self::create_record('F17-FUT-07',$u,'conversation',$c,['message_id'=>absint($r->get_param('message_id')),'label'=>mb_substr(sanitize_text_field((string)$r->get_param('label')),0,191)],self::client($r,$u,'reminder'),$at);return is_wp_error($id)?$id:new WP_REST_Response(['id'=>$id,'remind_at'=>$at],201);}
    public static function list_reminders(): WP_REST_Response {return rest_ensure_response(['items'=>self::owned('F17-FUT-07',get_current_user_id())]);}
    public static function save_template(WP_REST_Request $r): WP_REST_Response|WP_Error {$u=get_current_user_id();$title=mb_substr(sanitize_text_field((string)$r->get_param('title')),0,120);$body=mb_substr(sanitize_textarea_field(wp_unslash((string)$r->get_param('body'))),0,8000);if($title===''||$body==='')return self::error('sn_template_invalid','A title and template body are required.',400);if(self::looks_clinical_directive($body)&&!(bool)apply_filters('sn_network_professional_template_allowed',false,$u,$body))return self::error('sn_template_clinical_guard','Clinical directive templates require an approved professional policy.',403);$id=self::create_record('F17-FUT-08',$u,'user',$u,['title'=>$title,'body'=>$body],self::client($r,$u,'template'),null);return is_wp_error($id)?$id:new WP_REST_Response(['id'=>$id,'title'=>$title],201);}
    public static function list_templates(): WP_REST_Response {return rest_ensure_response(['items'=>self::owned('F17-FUT-08',get_current_user_id())]);}
}
