<?php
/** Review rounds 24+ — provider-consistent breakout lifecycle hardening. */
declare(strict_types=1);
defined('ABSPATH') || exit;

final class SN_Future24_Review_Hardening_E {
    private const RECONCILE_BATCH=100;
    public static function register():void{add_action('rest_api_init',[self::class,'routes'],1990);add_action('sn_cleanup_hourly',[self::class,'cleanup_breakouts'],40);}
    public static function routes():void{
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts',['methods'=>'POST','callback'=>[self::class,'create_breakouts'],'permission_callback'=>[SN_REST::class,'access']],true);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts/move',['methods'=>'POST','callback'=>[self::class,'move_breakout'],'permission_callback'=>[SN_REST::class,'access']]);
        register_rest_route('sabri-network/v2','/calls/(?P<id>\d+)/breakouts/close',['methods'=>'POST','callback'=>[self::class,'close_breakouts'],'permission_callback'=>[SN_REST::class,'access']]);
    }
    public static function create_breakouts(WP_REST_Request $r):WP_REST_Response|WP_Error{
        global $wpdb;$call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);
        $rooms=is_array($r->get_param('rooms'))?$r->get_param('rooms'):[];if(!$rooms||count($rooms)>20)return self::error('sn_breakouts_invalid','Provide 1 to 20 breakout rooms.',400);$seen=[];$clean=[];$index=0;
        foreach($rooms as $room){$name=mb_substr(sanitize_text_field((string)($room['name']??'')),0,100);$users=array_values(array_unique(array_filter(array_map('absint',(array)($room['user_ids']??[])))));if($name===''||!$users)return self::error('sn_breakout_room_invalid','Each breakout room needs a name and participants.',400);foreach($users as $u){if(isset($seen[$u]))return self::error('sn_breakout_duplicate_participant','A participant may be assigned to only one breakout room.',409);if(!self::call_member($call,$u))return self::error('sn_breakout_participant_invalid','Every breakout participant must be an active call member.',409);$seen[$u]=true;}$clean[]=['room_id'=>'br-'.(++$index),'name'=>$name,'user_ids'=>$users,'state'=>'active'];}
        if(!(bool)apply_filters('sn_network_sfu_available',false,$actor,$call))return self::error('sn_breakout_provider_unavailable','Breakout rooms require an approved SFU adapter.',503);
        $lock=self::lifecycle_lock($call);if(is_wp_error($lock))return $lock;
        try{
            if(!self::call_manager($call,$actor))return self::error('forbidden','Call host authority changed before breakout creation.',403);foreach(array_keys($seen) as $uid)if(!self::call_member($call,(int)$uid))return self::error('sn_breakout_participant_invalid','A participant left the parent call before breakout creation.',409);
            $expires=gmdate('Y-m-d H:i:s',time()+max(15,min(480,absint($r->get_param('ttl_minutes'))?:120))*MINUTE_IN_SECONDS);$operation=wp_generate_uuid4();$data=['parent_call_id'=>$call,'rooms'=>$clean,'assignments'=>[],'provider_room_refs'=>[],'created_by'=>$actor,'expires_at'=>$expires,'operation_id'=>$operation,'provider_phase'=>'provisioning'];
            $row=self::lifecycle_row($call,true);if($row&&in_array((string)$row->state,['active','moving','closing','provisioning','expiry_pending','reconcile_required'],true))return self::error('sn_breakout_conflict','Another breakout lifecycle is already active for this call.',409);
            $record=self::save_lifecycle($row,$call,$data,'provisioning',$expires);if(is_wp_error($record))return $record;$id=(int)$record['id'];$version=(int)$record['version'];
            $provider=apply_filters('sn_network_breakout_create_result',null,$call,$clean,$actor,['operation_id'=>$operation,'idempotency_key'=>'file17-breakout-create:'.$id.':'.$version]);
            if($provider===null||$provider===false||is_wp_error($provider)){self::transition_state($id,$version,'provisioning','provider_failed');return is_wp_error($provider)?$provider:self::error('sn_breakout_provider_unavailable','Breakout rooms require an approved SFU adapter.',503);}
            $refs=[];foreach((array)($provider['room_refs']??[]) as $k=>$ref){$v=mb_substr(sanitize_text_field((string)$ref),0,191);if($v!=='')$refs[(string)$k]=$v;}$data['provider_room_refs']=$refs;$data['provider_result_hash']=hash('sha256',(string)wp_json_encode($provider));$data['provider_phase']='active';
            $final=self::finalize_payload($id,$version,$data,'provisioning','active',$expires);if(is_wp_error($final)){$rolled=apply_filters('sn_network_breakout_close_result',null,$call,$actor,$data+['compensation_for'=>'create_finalize_failure']);if($rolled!==null&&$rolled!==false&&!is_wp_error($rolled))self::force_reconcile_terminal($id,'provider_rolled_back');else self::force_reconcile_required($id,$data+['reconcile_action'=>'close']);return self::error('sn_breakout_reconcile_required','Provider creation succeeded but local finalization failed; reconciliation was queued.',503);}
            SN_DB::audit('future_breakouts_created','call',$call,'success',['breakout_record_id'=>$id,'room_count'=>count($clean),'expires_at'=>$expires,'operation_id'=>$operation],$actor);return rest_ensure_response(['call_id'=>$call,'breakout_record_id'=>$id,'rooms'=>$clean,'expires_at'=>$expires]);
        }finally{self::lifecycle_unlock($lock);}
    }
    public static function move_breakout(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);$target=absint($r->get_param('user_id'));$room=sanitize_key((string)$r->get_param('room_id'));if(!$target||!self::call_member($call,$target))return self::error('sn_breakout_participant_invalid','Participant is no longer in the parent call.',409);
        $lock=self::lifecycle_lock($call);if(is_wp_error($lock))return $lock;
        try{
            if(!self::call_manager($call,$actor)||!self::call_member($call,$target))return self::error('sn_breakout_participant_invalid','Host authority or participant membership changed before move.',409);$row=self::lifecycle_row($call,true);if(!$row||(string)$row->state!=='active')return self::error('sn_breakouts_unavailable','No stable active breakout set exists.',409);$data=self::decode($row);if(is_wp_error($data))return $data;$valid=$room==='parent';if(!$valid)foreach((array)($data['rooms']??[]) as $entry)if((string)($entry['room_id']??'')===$room&&($entry['state']??'')==='active'){$valid=true;break;}if(!$valid)return self::error('sn_breakout_room_invalid','Select an active breakout or parent room.',409);
            $previous=(string)($data['assignments'][(string)$target]??'parent');$data['pending_move']=['user_id'=>$target,'from'=>$previous,'to'=>$room,'requested_by'=>$actor,'operation_id'=>wp_generate_uuid4()];$pending=self::finalize_payload((int)$row->id,(int)$row->version,$data,'active','moving',(string)$row->expires_at);if(is_wp_error($pending))return $pending;$version=(int)$row->version+1;
            $provider=apply_filters('sn_network_breakout_move_result',null,$call,$target,$room,$actor,$data);if($provider===null||$provider===false||is_wp_error($provider)){unset($data['pending_move']);$data['provider_phase']='active';self::finalize_payload((int)$row->id,$version,$data,'moving','active',(string)$row->expires_at);return is_wp_error($provider)?$provider:self::error('sn_breakout_provider_unavailable','The conference provider could not move this participant.',503);}
            $data['assignments'][(string)$target]=$room;unset($data['pending_move']);$data['provider_phase']='active';$saved=self::finalize_payload((int)$row->id,$version,$data,'moving','active',(string)$row->expires_at);if(is_wp_error($saved)){$rollback=apply_filters('sn_network_breakout_move_rollback_result',null,$call,$target,$previous,$actor,['failed_target'=>$room,'record_id'=>(int)$row->id]);if($rollback!==null&&$rollback!==false&&!is_wp_error($rollback))self::force_active_after_move_rollback((int)$row->id,$target,$previous);else self::force_reconcile_required((int)$row->id,['reconcile_action'=>'move_rollback','user_id'=>$target,'room_id'=>$previous,'failed_target'=>$room]);return self::error('sn_breakout_reconcile_required','Provider move succeeded but local finalization failed; reconciliation was queued.',503);}
            SN_DB::audit('future_breakout_participant_moved','call',$call,'success',['user_id'=>$target,'room_id'=>$room],$actor);return rest_ensure_response(['call_id'=>$call,'user_id'=>$target,'room_id'=>$room]);
        }finally{self::lifecycle_unlock($lock);}
    }
    public static function close_breakouts(WP_REST_Request $r):WP_REST_Response|WP_Error{
        $call=absint($r['id']);$actor=get_current_user_id();if(!self::call_manager($call,$actor))return self::error('forbidden','Call host permission is required.',403);$lock=self::lifecycle_lock($call);if(is_wp_error($lock))return $lock;
        try{if(!self::call_manager($call,$actor))return self::error('forbidden','Call host authority changed before close.',403);$row=self::lifecycle_row($call,true);if(!$row||in_array((string)$row->state,['closed','expired','provider_failed','provider_rolled_back'],true))return rest_ensure_response(['call_id'=>$call,'state'=>'closed']);if((string)$row->state!=='active')return self::error('sn_breakout_conflict','Breakout lifecycle is busy; retry close.',409);$data=self::decode($row);if(is_wp_error($data))return $data;$pending=self::transition_state((int)$row->id,(int)$row->version,'active','closing');if(is_wp_error($pending))return $pending;$provider=apply_filters('sn_network_breakout_close_result',null,$call,$actor,$data+['idempotency_key'=>'file17-breakout-close:'.(int)$row->id]);if($provider===null||$provider===false||is_wp_error($provider)){self::transition_state((int)$row->id,(int)$row->version+1,'closing','active');return is_wp_error($provider)?$provider:self::error('sn_breakout_provider_unavailable','The conference provider could not close the breakouts safely.',503);}$closed=self::transition_state((int)$row->id,(int)$row->version+1,'closing','closed');if(is_wp_error($closed)){self::force_reconcile_required((int)$row->id,$data+['reconcile_action'=>'close']);return self::error('sn_breakout_reconcile_required','Provider closed the breakouts but local finalization requires reconciliation.',503);}SN_DB::audit('future_breakouts_closed','call',$call,'success',['record_id'=>(int)$row->id],$actor);return rest_ensure_response(['call_id'=>$call,'state'=>'closed']);}finally{self::lifecycle_unlock($lock);}
    }
    public static function cleanup_breakouts():void{
        global $wpdb;$now=current_time('mysql',true);$batch=self::RECONCILE_BATCH;
        // Claim due active rows before generic Future-24 cleanup can expire them blindly.
        $wpdb->query($wpdb->prepare("UPDATE ".$wpdb->prefix."sn_future_records SET state='expiry_pending',updated_at=%s,version=version+1 WHERE feature_id='F17-FUT-19' AND state='active' AND expires_at IS NOT NULL AND expires_at<=%s LIMIT $batch",$now,$now));
        $rows=$wpdb->get_results("SELECT id,scope_id,state FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-19' AND state IN ('expiry_pending','closing','reconcile_required','provisioning','moving') ORDER BY id ASC LIMIT ".self::RECONCILE_BATCH);
        foreach(is_array($rows)?$rows:[] as $stub){$call=(int)$stub->scope_id;$lock=self::lifecycle_lock($call,0);if(is_wp_error($lock))continue;try{$row=self::row_by_id((int)$stub->id,true);if(!$row)continue;$data=self::decode($row);if(is_wp_error($data))continue;$state=(string)$row->state;if($state==='moving'){$pending=(array)($data['pending_move']??[]);$target=absint($pending['user_id']??0);$previous=sanitize_key((string)($pending['from']??'parent'));$rollback=apply_filters('sn_network_breakout_move_rollback_result',null,$call,$target,$previous,0,['record_id'=>(int)$row->id,'recovery'=>true]);if($rollback!==null&&$rollback!==false&&!is_wp_error($rollback))self::force_active_after_move_rollback((int)$row->id,$target,$previous);continue;}$provider=apply_filters('sn_network_breakout_close_result',null,$call,0,$data+['recovery'=>true,'state'=>$state]);if($provider===null||$provider===false||is_wp_error($provider)){self::force_reconcile_required((int)$row->id,$data+['reconcile_action'=>'close']);continue;}$terminal=$state==='expiry_pending'?'expired':($state==='closing'?'closed':'provider_rolled_back');self::force_reconcile_terminal((int)$row->id,$terminal);SN_DB::audit('future_breakouts_'.$terminal,'call',$call,'success',['record_id'=>(int)$row->id,'recovered'=>true],0);}finally{self::lifecycle_unlock($lock);}}
    }
    private static function lifecycle_row(int $call,bool $lock=false):?object{global $wpdb;$sql="SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-19' AND scope_type='call' AND scope_id=%d ORDER BY id DESC LIMIT 1".($lock?' FOR UPDATE':'');$row=$wpdb->get_row($wpdb->prepare($sql,$call));return is_object($row)?$row:null;}
    private static function row_by_id(int $id,bool $lock=false):?object{global $wpdb;$sql="SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE id=%d AND feature_id='F17-FUT-19' LIMIT 1".($lock?' FOR UPDATE':'');$row=$wpdb->get_row($wpdb->prepare($sql,$id));return is_object($row)?$row:null;}
    private static function save_lifecycle(?object $row,int $call,array $data,string $state,string $expires):array|WP_Error{global $wpdb;$dummy=$row?:((object)['feature_id'=>'F17-FUT-19','owner_id'=>0,'scope_type'=>'call','scope_id'=>$call,'version'=>0]);$cipher=self::encode($dummy,$data);if(is_wp_error($cipher))return $cipher;$now=current_time('mysql',true);if($row){$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'state'=>$state,'expires_at'=>$expires,'updated_at'=>$now,'version'=>(int)$row->version+1],['id'=>(int)$row->id,'version'=>(int)$row->version]);return $ok===1?['id'=>(int)$row->id,'version'=>(int)$row->version+1]:self::error('sn_breakout_conflict','Breakout state changed concurrently.',409);}$ok=$wpdb->insert($wpdb->prefix.'sn_future_records',['feature_id'=>'F17-FUT-19','owner_id'=>0,'scope_type'=>'call','scope_id'=>$call,'state'=>$state,'payload_cipher'=>$cipher,'client_key'=>hash('sha256','breakouts:'.$call),'expires_at'=>$expires,'created_at'=>$now,'updated_at'=>$now,'version'=>1]);return $ok===1?['id'=>(int)$wpdb->insert_id,'version'=>1]:self::error('database_error','Breakout lifecycle could not be stored safely.',500);}
    private static function finalize_payload(int $id,int $version,array $data,string $from,string $to,string $expires):bool|WP_Error{global $wpdb;$row=self::row_by_id($id,false);if(!$row)return self::error('sn_breakout_conflict','Breakout state changed concurrently.',409);$cipher=self::encode($row,$data);if(is_wp_error($cipher))return $cipher;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'state'=>$to,'expires_at'=>$expires,'updated_at'=>current_time('mysql',true),'version'=>$version+1],['id'=>$id,'state'=>$from,'version'=>$version]);return $ok===1?true:self::error('sn_breakout_conflict','Breakout state changed concurrently.',409);}
    private static function transition_state(int $id,int $version,string $from,string $to):bool|WP_Error{global $wpdb;$ok=$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>$to,'updated_at'=>current_time('mysql',true),'version'=>$version+1],['id'=>$id,'state'=>$from,'version'=>$version]);return $ok===1?true:self::error('sn_breakout_conflict','Breakout state changed concurrently.',409);}
    private static function force_reconcile_required(int $id,array $data):void{global $wpdb;$row=self::row_by_id($id,false);if(!$row)return;$cipher=self::encode($row,$data);$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>is_wp_error($cipher)?$row->payload_cipher:$cipher,'state'=>'reconcile_required','updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>$id,'version'=>(int)$row->version]);SN_DB::audit('future_breakout_reconcile_required','future_record',$id,'failure',['scope_id'=>(int)$row->scope_id],0);}
    private static function force_reconcile_terminal(int $id,string $state):void{global $wpdb;$row=self::row_by_id($id,false);if(!$row)return;$wpdb->update($wpdb->prefix.'sn_future_records',['state'=>$state,'updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>$id,'version'=>(int)$row->version]);}
    private static function force_active_after_move_rollback(int $id,int $target,string $previous):void{global $wpdb;$row=self::row_by_id($id,false);if(!$row)return;$data=self::decode($row);if(is_wp_error($data))return;$data['assignments'][(string)$target]=$previous;unset($data['pending_move']);$data['provider_phase']='active';$cipher=self::encode($row,$data);if(is_wp_error($cipher))return;$wpdb->update($wpdb->prefix.'sn_future_records',['payload_cipher'=>$cipher,'state'=>'active','updated_at'=>current_time('mysql',true),'version'=>(int)$row->version+1],['id'=>$id,'version'=>(int)$row->version]);}
    private static function call_member(int $call,int $u):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".SN_DB::table('call_members')." WHERE call_id=%d AND user_id=%d AND status IN ('invited','joined') LIMIT 1",$call,$u));}
    private static function call_manager(int $call,int $u):bool{global $wpdb;$c=(int)$wpdb->get_var($wpdb->prepare('SELECT conversation_id FROM '.SN_DB::table('calls').' WHERE id=%d',$call));if(!$c)return false;$host=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".$wpdb->prefix."sn_future_records WHERE feature_id='F17-FUT-20' AND scope_type='call' AND scope_id=%d AND state='active' ORDER BY id DESC LIMIT 1",$call));if($host){$d=self::decode($host);if(!is_wp_error($d)&&(int)($d['host_id']??0)===$u)return true;}return in_array(SN_DB::member_role($c,$u),['owner','moderator'],true)||user_can($u,'manage_options');}
    private static function lifecycle_lock(int $call,int $wait=5):string|WP_Error{global $wpdb;$name='sn:f17:breakout:'.$call;$got=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$name,$wait));return $got===1?$name:self::error('sn_breakout_busy','Breakout lifecycle is busy; retry.',409);}
    private static function lifecycle_unlock(string|WP_Error $lock):void{if(is_wp_error($lock))return;global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));}
    private static function decode(object $row):array|WP_Error{$p=SN_Communication_Crypto::decrypt((string)$row->payload_cipher,'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);if(is_wp_error($p))return $p;$d=json_decode($p,true);return is_array($d)?$d:self::error('sn_future_record_invalid','Advanced communication data is invalid.',500);}
    private static function encode(object $row,array $data):string|WP_Error{return SN_Communication_Crypto::encrypt((string)wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),'future-record|'.(string)$row->feature_id.'|'.(int)$row->owner_id.'|'.(string)$row->scope_type.'|'.(int)$row->scope_id);}
    private static function error(string $c,string $m,int $s):WP_Error{return new WP_Error($c,$m,['status'=>$s]);}
}
